In [25]:
import pandas as pd

In [26]:
# ملف results

In [27]:
results = pd.read_csv("data/raw/results.csv")
results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0,0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4,2,Friendly,London,England,False
2,1874-03-07,Scotland,England,2,1,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2,2,Friendly,London,England,False
4,1876-03-04,Scotland,England,3,0,Friendly,Glasgow,Scotland,False

In [28]:
results.tail()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49066,2026-01-18,Bolivia,Panama,1,1,Friendly,Tarija,Bolivia,False
49067,2026-01-18,Grenada,Jamaica,0,1,Friendly,St. George's,Grenada,False
49068,2026-01-22,Panama,Mexico,0,1,Friendly,Panama City,Panama,False
49069,2026-01-25,Bolivia,Mexico,0,1,Friendly,Santa Cruz,Bolivia,False
49070,2026-01-26,Uzbekistan,China PR,2,2,Friendly,Dubai,United Arab Emirates,True

In [29]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49071 entries, 0 to 49070
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49071 non-null  object
 1   home_team   49071 non-null  object
 2   away_team   49071 non-null  object
 3   home_score  49071 non-null  int64
 4   away_score  49071 non-null  int64
 5   tournament  49071 non-null  object
 6   city        49071 non-null  object
 7   country     49071 non-null  object
 8   neutral     49071 non-null  bool
dtypes: bool(1), int64(2), object(6)
memory usage: 3.0+ MB

In [30]:
print(f" عدد المباريات الكلي      : {len(results):,}")
print(f" عدد الأعمدة              : {len(results.columns)}")
print(f" أقدم مباراة              : {results['date'].min()}")
print(f" أحدث مباراة              : {results['date'].max()}")
print(f" عدد المنتخبات            : {pd.concat([results['home_team'], results['away_team']]).nunique()}")

 عدد المباريات الكلي      : 49,071
 عدد الأعمدة              : 9
 أقدم مباراة              : 1872-11-30
 أحدث مباراة              : 2026-01-26
 عدد المنتخبات            : 333

In [31]:
print(" أسماء الأعمدة:")
for col in results.columns:
    print(f"   - {col}")

 أسماء الأعمدة:
   - date
   - home_team
   - away_team
   - home_score
   - away_score
   - tournament
   - city
   - country
   - neutral

In [32]:
""" date → تاريخ المباراة

home_team → الفريق صاحب الأرض

away_team → الفريق الضيف

home_score → عدد أهداف الفريق صاحب الأرض

away_score → عدد أهداف الفريق الضيف

tournament → نوع البطولة (كأس عالم، تصفيات، مباراة ودية…)

city → المدينة التي لعبت فيها المباراة

country → الدولة التي أقيمت فيها المباراة

neutral → هل المباراة على أرض محايدة

TRUE = ملعب محايد

FALSE = ملعب الفريق صاحب الأرض"""

' date → تاريخ المباراة\n\nhome_team → الفريق صاحب الأرض\n\naway_team → الفريق الضيف\n\nhome_score → عدد أهداف الفريق صاحب الأرض\n\naway_score → عدد أهداف الفريق الضيف\n\ntournament → نوع البطولة (كأس عالم، تصفيات، مباراة ودية…)\n\ncity → المدينة التي لعبت فيها المباراة\n\ncountry → الدولة التي أقيمت فيها المباراة\n\nneutral → هل المباراة على أرض محايدة\n\nTRUE = ملعب محايد\n\nFALSE = ملعب الفريق صاحب الأرض'

In [33]:
# ملف هدافين كاس العالم 2026

In [34]:
wc_scorers = pd.read_csv(r"C:\Users\user\Desktop\project\data\raw\Players.Goal.csv", encoding='utf-8-sig')
wc_scorers.head()

            Player    Position  Goals
0    �lvaro Morata     Forward     34
1    Ferran Torres     Forward     21
2  Mikel Oyarzabal     Forward     12
3        Dani Olmo  Midfielder     10
4    Pablo Sarabia     Forward      9

In [35]:
print(f" عدد اللاعبين             : {len(wc_scorers):,}")
print(f" عدد الأعمدة              : {len(wc_scorers.columns)}")
print(f" المراكز الموجودة         : {wc_scorers['Position'].unique()}")

 عدد اللاعبين             : 414
 عدد الأعمدة              : 3
 المراكز الموجودة         : ['Forward' 'Midfielder' 'Defender']

In [36]:
print("أسماء الأعمدة:")
for col in wc_scorers.columns:
    print(f"   - {col}")

أسماء الأعمدة:
   - Player
   - Position
   - Goals

In [37]:
print("أكثر 10 هدافين:")
print(wc_scorers.sort_values('Goals', ascending=False).head(10).to_string(index=False))

أكثر 10 هدافين:
             Player Position  Goals
  Cristiano Ronaldo  Forward    128
       Lionel Messi  Forward    106
      Romelu Lukaku  Forward     83
 Robert Lewandowski  Forward     82
             Neymar  Forward     79
        Luis Su�rez  Forward     68
         Harry Kane  Forward     62
Aleksandar Mitrovi?  Forward     59
     Edinson Cavani  Forward     58
     Olivier Giroud  Forward     57

In [38]:
print("توزيع اللاعبين حسب المركز:")
print(wc_scorers['Position'].value_counts().to_string())

توزيع اللاعبين حسب المركز:
Position
Forward       203
Midfielder    125
Defender       86

In [39]:
print(wc_scorers.columns.tolist())

['Player', 'Position', 'Goals']

In [40]:
print(f" إجمالي الأهداف           : {wc_scorers['Goals'].sum():,}")
print(f" متوسط الأهداف للاعب      : {wc_scorers['Goals'].mean():.2f}")
print(f" أعلى هداف       : {wc_scorers.loc[wc_scorers['Goals'].idxmax(),'Player']} ({wc_scorers['Goals'].max()} أهداف)")

 إجمالي الأهداف           : 4,374
 متوسط الأهداف للاعب      : 10.57
 أعلى هداف       : Cristiano Ronaldo (128 أهداف)

In [41]:
"""
ملف هدافين كاس العالم 2026:
- يحتوي على بيانات اللاعبين المشاركين في كاس العالم
- الأعمدة: Player (اسم اللاعب), Position (المركز), Goals (عدد الأهداف)
- يختلف عن ملف goalscorers.csv القديم الذي يسجل كل هدف على حدة
- هذا الملف سيُستخدم في الواجهة لعرض إحصائيات الهدافين
"""

'\nملف هدافين كاس العالم 2026:\n- يحتوي على بيانات اللاعبين المشاركين في كاس العالم\n- الأعمدة: Player (اسم اللاعب), Position (المركز), Goals (عدد الأهداف)\n- يختلف عن ملف goalscorers.csv القديم الذي يسجل كل هدف على حدة\n- هذا الملف سيُستخدم في الواجهة لعرض إحصائيات الهدافين\n'

In [42]:
# ملف ترتيب المنتخبات 2025

In [43]:
ranking_2025 = pd.read_csv(r"C:\Users\user\Desktop\project\data\raw\fifa_ranking.csv", encoding='latin-1')
ranking_2025.head()

  Rank       Team   Points
0    1      Spain  1877.18
1    2  Argentina  1873.33
2    3     France     1870
3    4    England  1834.12
4    5     Brazil  1760.46

In [44]:
print(f" عدد المنتخبات            : {len(ranking_2025):,}")
print(f" عدد الأعمدة              : {len(ranking_2025.columns)}")
print(f" الأعمدة                  : {list(ranking_2025.columns)}")

 عدد المنتخبات            : 213
 عدد الأعمدة              : 3
 الأعمدة                  : ['Rank', 'Team', 'Points']

In [45]:
print("أعلى 20 منتخب في العالم 2025:")
print(ranking_2025.head(20).to_string(index=False))

أعلى 20 منتخب في العالم 2025:
Rank        Team  Points
   1       Spain 1877.18
   2   Argentina 1873.33
   3      France    1870
   4     England 1834.12
   5      Brazil 1760.46
   6    Portugal 1760.38
   7 Netherlands 1756.27
   8     Morocco 1736.57
   9     Belgium 1730.71
  10     Germany 1724.15
  11     Croatia 1716.88
  12     Senegal 1706.83
  13       Italy 1702.06
  14    Colombia  1701.3
  15         USA 1681.88
  16      Mexico 1675.75
  17     Uruguay 1672.62
  18 Switzerland 1654.69
  19       Japan 1650.12
  20        Iran 1617.02

In [46]:
# منتخبات كاس العالم 2026 في الترتيب
wc_teams = ['Spain','Argentina','France','England','Brazil','Portugal','Netherlands',
            'Morocco','Belgium','Germany','Croatia','Senegal','Italy','Colombia',
            'USA','Mexico','Uruguay','Switzerland','Japan','Iran','South Korea',
            'Ecuador','Austria','Canada','Australia','Norway','Algeria','Jordan',
            'Saudi Arabia','Uzbekistan','South Africa','Qatar']

wc_ranking = ranking_2025[ranking_2025['Team'].isin(wc_teams)]
print(f"منتخبات كاس العالم في الملف: {len(wc_ranking)}")
print(wc_ranking.to_string(index=False))

منتخبات كاس العالم في الملف: 32
Rank         Team  Points
   1        Spain 1877.18
   2    Argentina 1873.33
   3       France    1870
   4      England 1834.12
   5       Brazil 1760.46
   6     Portugal 1760.38
   7  Netherlands 1756.27
   8      Morocco 1736.57
   9      Belgium 1730.71
  10      Germany 1724.15
  11      Croatia 1716.88
  12      Senegal 1706.83
  13        Italy 1702.06
  14     Colombia  1701.3
  15          USA 1681.88
  16       Mexico 1675.75
  17      Uruguay 1672.62
  18  Switzerland 1654.69
  19        Japan 1650.12
  20         Iran 1617.02
  22  South Korea 1599.45
  23      Ecuador 1591.73
  24      Austria 1585.51
  27    Australia 1574.01
  28      Algeria 1560.91
  29       Canada 1559.15
  32       Norway 1553.14
  55 Saudi Arabia 1435.11
  56   Uzbekistan 1433.62
  57        Qatar 1432.15
  61       Jordan 1423.57
  66 South Africa 1409.33

In [47]:
"""
ملف ترتيب المنتخبات 2025:
- يحتوي على 213 منتخب
- الأعمدة: Rank, Team, Points
- سيُستخدم في الواجهة فقط لعرض الترتيب الحالي
- لن يُستخدم في الموديل
"""

'\nملف ترتيب المنتخبات 2025:\n- يحتوي على 213 منتخب\n- الأعمدة: Rank, Team, Points\n- سيُستخدم في الواجهة فقط لعرض الترتيب الحالي\n- لن يُستخدم في الموديل\n'

In [48]:
# ملف ترتيب الفيفا

In [49]:
try:
    fifa = pd.read_csv("data/raw/fifa_ranking-2024-06-20.csv")
except:
    fifa = pd.read_csv("data/raw/fifa_ranking.csv")

In [50]:
print(f" عدد السجلات              : {len(fifa):,}")
print(f" عدد الأعمدة              : {len(fifa.columns)}")
print(f" أقدم تاريخ               : {fifa['rank_date'].min()}")
print(f" أحدث تاريخ               : {fifa['rank_date'].max()}")
print(f" عدد المنتخبات            : {fifa['country_full'].nunique()}")

 عدد السجلات              : 67,472
 عدد الأعمدة              : 8
 أقدم تاريخ               : 1992-12-31
 أحدث تاريخ               : 2024-06-20
 عدد المنتخبات            : 216

In [51]:
print(" أسماء الأعمدة:")
for col in fifa.columns:
    print(f"   - {col}")

 أسماء الأعمدة:
   - rank
   - country_full
   - country_abrv
   - total_points
   - previous_points
   - rank_change
   - confederation
   - rank_date

In [52]:
"""rank → ترتيب المنتخب عالمياً حسب الفيفا

country_full → اسم المنتخب الكامل (مثلاً: Brazil)

country_abrv → اختصار المنتخب (BRA)

total_points → مجموع نقاط الفيفا الحالية للمنتخب

previous_points → نقاطه في التصنيف السابق

rank_change → مقدار تغير الترتيب عن الشهر السابق

رقم موجب = تحسن

رقم سالب = تراجع

confederation → الاتحاد القاري

UEFA → أوروبا

AFC → آسيا

CAF → أفريقيا

CONMEBOL → أمريكا الجنوبية

CONCACAF → أمريكا الشمالية

rank_date → تاريخ إصدار هذا التصنيف"""

'rank → ترتيب المنتخب عالمياً حسب الفيفا\n\ncountry_full → اسم المنتخب الكامل (مثلاً: Brazil)\n\ncountry_abrv → اختصار المنتخب (BRA)\n\ntotal_points → مجموع نقاط الفيفا الحالية للمنتخب\n\nprevious_points → نقاطه في التصنيف السابق\n\nrank_change → مقدار تغير الترتيب عن الشهر السابق\n\nرقم موجب = تحسن\n\nرقم سالب = تراجع\n\nconfederation → الاتحاد القاري\n\nUEFA → أوروبا\n\nAFC → آسيا\n\nCAF → أفريقيا\n\nCONMEBOL → أمريكا الجنوبية\n\nCONCACAF → أمريكا الشمالية\n\nrank_date → تاريخ إصدار هذا التصنيف'

In [53]:
print("أعلى 10 منتخبات (آخر تحديث):")
latest_date = fifa['rank_date'].max()
top10 = fifa[fifa['rank_date'] == latest_date].sort_values('rank').head(10)
print(top10[['rank', 'country_full', 'total_points']].to_string(index=False))

أعلى 10 منتخبات (آخر تحديث):
 rank country_full  total_points
  1.0    Argentina       1860.14
  2.0       France       1837.47
  3.0      Belgium       1797.98
  4.0       Brazil       1791.85
  5.0      England       1787.88
  6.0     Portugal       1747.04
  7.0  Netherlands       1746.66
  8.0        Spain       1729.92
  9.0      Croatia       1728.30
 10.0        Italy       1724.37

In [54]:
#ملف الهدافين

In [55]:
goals = pd.read_csv("data/raw/goalscorers.csv")

In [56]:
print(f" عدد الأهداف الكلي        : {len(goals):,}")

 عدد الأهداف الكلي        : 47,555

In [57]:
print("أسماء الأعمدة:")
for col in goals.columns:
    print(f"   - {col}")

أسماء الأعمدة:
   - date
   - home_team
   - away_team
   - team
   - scorer
   - minute
   - own_goal
   - penalty

In [58]:
"""date → تاريخ المباراة

home_team → الفريق صاحب الأرض

away_team → الفريق الضيف

team → الفريق الذي سجل الهدف

scorer → اسم اللاعب الذي سجل الهدف

minute → الدقيقة التي سجل فيها الهدف

own_goal → هل الهدف هدف عكسي

TRUE = هدف في مرمى فريقه

FALSE = هدف طبيعي

penalty → هل الهدف من ضربة جزاء

TRUE = ركلة جزاء

FALSE = هدف من اللعب

"""

'date → تاريخ المباراة\n\nhome_team → الفريق صاحب الأرض\n\naway_team → الفريق الضيف\n\nteam → الفريق الذي سجل الهدف\n\nscorer → اسم اللاعب الذي سجل الهدف\n\nminute → الدقيقة التي سجل فيها الهدف\n\nown_goal → هل الهدف هدف عكسي\n\nTRUE = هدف في مرمى فريقه\n\nFALSE = هدف طبيعي\n\npenalty → هل الهدف من ضربة جزاء\n\nTRUE = ركلة جزاء\n\nFALSE = هدف من اللعب\n\n'

In [59]:
print("أكثر 10 هدافين في التاريخ:")
top_scorers = goals[goals['own_goal'] == False]['scorer'].value_counts().head(10)
print(top_scorers.to_string())

أكثر 10 هدافين في التاريخ:
scorer
Cristiano Ronaldo      121
Harry Kane              69
Robert Lewandowski      68
Romelu Lukaku           64
Lionel Messi            63
Edin Džeko              57
Aleksandar Mitrović     52
Luis Suárez             51
Ali Daei                49
Miroslav Klose          48

In [60]:
#ملف البلنتيات

In [61]:
shootouts = pd.read_csv("data/raw/shootouts.csv")

In [62]:
print(f" عدد المباريات            : {len(shootouts):,}")

 عدد المباريات            : 665

In [63]:
print(" أسماء الأعمدة:")
for col in shootouts.columns:
    print(f"   - {col}")

 أسماء الأعمدة:
   - date
   - home_team
   - away_team
   - winner
   - first_shooter

In [64]:
"""date → تاريخ المباراة

home_team → الفريق صاحب الأرض

away_team → الفريق الضيف

winner → الفريق الذي فاز بركلات الترجيح

first_shooter → الفريق الذي سدد أول ركلة جزاء"""

'date → تاريخ المباراة\n\nhome_team → الفريق صاحب الأرض\n\naway_team → الفريق الضيف\n\nwinner → الفريق الذي فاز بركلات الترجيح\n\nfirst_shooter → الفريق الذي سدد أول ركلة جزاء'

In [65]:
# ملف اسماء الدول اللي تغيرت على مر التاريخ

In [66]:
former = pd.read_csv("data/raw/former_names.csv")
print(f"عدد السجلات: {len(former)}")
print(former)

عدد السجلات: 36
                current                                former  start_date  \
0                 Benin                               Dahomey  1959-11-08
1          Burkina Faso                           Upper Volta  1960-04-14
2               Curaçao                  Netherlands Antilles  1957-03-03
3        Czechoslovakia                               Bohemia  1903-04-05
4        Czechoslovakia                   Bohemia and Moravia  1939-01-01
5        Czechoslovakia  Representation of Czechs and Slovaks  1993-03-24
6              DR Congo                         Belgian Congo  1948-05-25
7              DR Congo                    Congo-Léopoldville  1963-04-12
8              DR Congo                        Congo-Kinshasa  1965-01-09
9              DR Congo                                 Zaïre  1971-01-10
10             Djibouti                     French Somaliland  1947-12-05
11                Egypt                  United Arab Republic  1958-02-22
12             Eswatini                             Swaziland  1968-05-01
13                Ghana                            Gold Coast  1950-05-28
14        Guinea-Bissau                     Portuguese Guinea  1953-06-02
15               Guyana                        British Guiana  1905-07-21
16            Indonesia                     Dutch East Indies  1934-05-13
17               Israel                   Mandatory Palestine  1934-03-16
18               Malawi                             Nyasaland  1957-08-28
19             Malaysia                                Malaya  1948-06-20
20              Myanmar                                 Burma  1952-03-14
21      North Macedonia                             Macedonia  1993-10-13
22     Northern Ireland                               Ireland  1882-02-18
23  Republic of Ireland                      Irish Free State  1924-05-28
24  Republic of Ireland                                  Éire  1937-01-01
25               Russia                          Soviet Union  1924-11-16
26               Russia                                   CIS  1992-01-25
27                Samoa                         Western Samoa  1979-08-31
28               Serbia                         FR Yugoslavia  1994-12-23
29               Serbia                 Serbia and Montenegro  2003-02-04
30            Sri Lanka                                Ceylon  1952-03-24
31             Suriname                          Dutch Guyana  1921-01-28
32             Tanzania                            Tanganyika  1945-01-01
33              Vanuatu                          New Hebrides  1951-10-04
34               Zambia                     Northern Rhodesia  1947-02-22
35             Zimbabwe                     Southern Rhodesia  1946-06-16

      end_date
0   1975-11-30
1   1984-08-04
2   2010-10-10
3   1919-01-01
4   1945-05-01
5   1993-11-17
6   1956-01-02
7   1964-07-19
8   1970-11-24
9   1997-04-27
10  1977-06-27
11  1971-09-11
12  2018-04-19
13  1957-03-06
14  1973-09-24
15  1967-08-02
16  1951-03-04
17  1940-04-27
18  1964-07-04
19  1963-08-16
20  1989-01-01
21  2018-11-19
22  1956-04-11
23  1936-12-06
24  1953-03-25
25  1991-11-13
26  1992-06-18
27  1996-11-15
28  2003-02-03
29  2006-06-21
30  1972-05-22
31  1975-11-25
32  1964-04-26
33  1980-07-30
34  1964-10-25
35  1980-04-18

In [67]:
print(f"    مباريات دولية         : {len(results):,}")
print(f"    سجلات ترتيب FIFA      : {len(fifa):,}")
print(f"    أهداف مسجلة           : {len(goals):,}")
print(f"    مباريات ركلات ترجيح   : {len(shootouts):,}")

    مباريات دولية         : 49,071
    سجلات ترتيب FIFA      : 67,472
    أهداف مسجلة           : 47,555
    مباريات ركلات ترجيح   : 665

In [68]:
"""شو عملت باكتشفا الداتا :
اولا عندي خمس ملفات الملف الاول اسمه result بحتوي  على كل مباريات المنتخبات شو عملت فيه اول اشي عملته هو فتحت الملف وشفت اول مباريات فيه يعني اول خمس مباريات وشفت اخر خمس مباريات وشفت   
وشفت الانفو اللي بعطيني معلومات عن الملف وشو في اماكن فارغة وشفت اسماء الاعمدة وهكذا 
 """
"""الملف الثاني بحتوي على ترتيب الفيفا وعملت نفس الخطوات اللي بالملف السابق """
"""والملفات الباقية ل الهدافين والبلنتيات واسماء المنتخبات اللي تغيرت """

'والملفات الباقية ل الهدافين والبلنتيات واسماء المنتخبات اللي تغيرت '

In [69]:
players = pd.read_csv("data/raw/EAFC26-Men.csv")

In [70]:
print(players.shape)

(16228, 59)

In [71]:
players.head()

,ID,Rank,Name,GENDER,OVR,PAC,SHO,PAS,DRI,DEF,...,League,Team,play style,url,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,card
0,209331,1,Mohamed Salah,M,91,89,88,86,90,45,...,Premier League,Liverpool,"['Finesse Shot+', 'First Touch', 'Gamechanger'...",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN,https://ratings-images-prod.pulse.ea.com/FC26/...
1,231747,3,Kylian Mbappé,M,91,97,90,81,92,37,...,LALIGA EA SPORTS,Real Madrid,"['Quick Step+', 'Acrobatic', 'Finesse Shot', '...",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN,https://ratings-images-prod.pulse.ea.com/FC26/...
2,231443,5,Ousmane Dembélé,M,90,91,88,83,93,50,...,Ligue 1 McDonald's,Paris SG,"['Rapid+', 'Inventive', 'Low Driven Shot', 'Pi...",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN,https://ratings-images-prod.pulse.ea.com/FC26/...
3,231866,6,Rodri,M,90,65,80,86,84,86,...,Premier League,Manchester City,"['Tiki Taka+', 'Aerial Fortress', 'Bruiser', '...",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN,https://ratings-images-prod.pulse.ea.com/FC26/...
4,203376,8,Virgil van Dijk,M,90,73,60,72,72,90,...,Premier League,Liverpool,"['Intercept+', 'Aerial Fortress', 'Anticipate'...",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN,https://ratings-images-prod.pulse.ea.com/FC26/...

In [72]:
players.dtypes

ID                         int64
Rank                       int64
Name                      object
GENDER                    object
OVR                        int64
PAC                        int64
SHO                        int64
PAS                        int64
DRI                        int64
DEF                        int64
PHY                        int64
Acceleration               int64
Sprint Speed               int64
Positioning                int64
Finishing                  int64
Shot Power                 int64
Long Shots                 int64
Volleys                    int64
Penalties                  int64
Vision                     int64
Crossing                   int64
Free Kick Accuracy         int64
Short Passing              int64
Long Passing               int64
Curve                      int64
Dribbling                  int64
Agility                    int64
Balance                    int64
Reactions                  int64
Ball Control               int64
Composure                  int64
Interceptions              int64
Heading Accuracy           int64
Def Awareness              int64
Standing Tackle            int64
Sliding Tackle             int64
Jumping                    int64
Stamina                    int64
Strength                   int64
Aggression                 int64
Position                  object
Weak foot                  int64
Skill moves                int64
Preferred foot            object
Height                    object
Weight                    object
Alternative positions     object
Age                        int64
Nation                    object
League                    object
Team                      object
play style                object
url                       object
GK Diving                float64
GK Handling              float64
GK Kicking               float64
GK Positioning           float64
GK Reflexes              float64
card                      object
dtype: object

In [73]:
players.isnull().sum()

ID                           0
Rank                         0
Name                         0
GENDER                       0
OVR                          0
PAC                          0
SHO                          0
PAS                          0
DRI                          0
DEF                          0
PHY                          0
Acceleration                 0
Sprint Speed                 0
Positioning                  0
Finishing                    0
Shot Power                   0
Long Shots                   0
Volleys                      0
Penalties                    0
Vision                       0
Crossing                     0
Free Kick Accuracy           0
Short Passing                0
Long Passing                 0
Curve                        0
Dribbling                    0
Agility                      0
Balance                      0
Reactions                    0
Ball Control                 0
Composure                    0
Interceptions                0
Heading Accuracy             0
Def Awareness                0
Standing Tackle              0
Sliding Tackle               0
Jumping                      0
Stamina                      0
Strength                     0
Aggression                   0
Position                     0
Weak foot                    0
Skill moves                  0
Preferred foot               0
Height                       0
Weight                       0
Alternative positions     5743
Age                          0
Nation                       0
League                       0
Team                         0
play style                   0
url                          0
GK Diving                14412
GK Handling              14412
GK Kicking               14412
GK Positioning           14412
GK Reflexes              14412
card                         0
dtype: int64

In [74]:
print(sorted(players['Nation'].unique()))

['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Benin', 'Bermuda', 'Bolivia', 'Bosnia and Herzegovina', 'Brazil', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cameroon', 'Canada', 'Cape Verde Islands', 'Central African Republic', 'Chad', 'Chile', 'China PR', 'Chinese Taipei', 'Colombia', 'Comoros', 'Congo', 'Congo DR', 'Costa Rica', 'Croatia', 'Cuba', 'Curaçao', 'Cyprus', 'Czech Republic', "Côte d'Ivoire", 'Denmark', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'England', 'Equatorial Guinea', 'Estonia', 'Faroe Islands', 'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Holland', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Korea Republic', 'Kosovo', 'Latvia', 'Lebanon', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Mali', 'Malta', 'Mauritania', 'Mexico', 'Moldova', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Namibia', 'New Zealand', 'Niger', 'Nigeria', 'North Macedonia', 'Northern Ireland', 'Norway', 'Pakistan', 'Palestine', 'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Republic of Ireland', 'Romania', 'Russia', 'Rwanda', 'Saudi Arabia', 'Scotland', 'Senegal', 'Serbia', 'Sierra Leone', 'Slovakia', 'Slovenia', 'Somalia', 'South Africa', 'Spain', 'Sri Lanka', 'St. Kitts and Nevis', 'St. Lucia', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Wales', 'Zambia', 'Zimbabwe']

In [75]:
len(players)

16228

In [76]:
len(players.columns)

59