In [1]:
import pandas as pd

In [2]:
results      = pd.read_csv("data/raw/results.csv")
fifa         = pd.read_csv("data/raw/fifa_ranking-2024-06-20.csv")
former_names = pd.read_csv("data/raw/former_names.csv")
players = pd.read_csv("data/raw/EAFC26-Men.csv")

In [3]:
players.head()

,ID,Rank,Name,GENDER,OVR,PAC,SHO,PAS,DRI,DEF,...,League,Team,play style,url,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,card
0,209331,1,Mohamed Salah,M,91,89,88,86,90,45,...,Premier League,Liverpool,"['Finesse Shot+', 'First Touch', 'Gamechanger'...",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN,https://ratings-images-prod.pulse.ea.com/FC26/...
1,231747,3,Kylian Mbappé,M,91,97,90,81,92,37,...,LALIGA EA SPORTS,Real Madrid,"['Quick Step+', 'Acrobatic', 'Finesse Shot', '...",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN,https://ratings-images-prod.pulse.ea.com/FC26/...
2,231443,5,Ousmane Dembélé,M,90,91,88,83,93,50,...,Ligue 1 McDonald's,Paris SG,"['Rapid+', 'Inventive', 'Low Driven Shot', 'Pi...",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN,https://ratings-images-prod.pulse.ea.com/FC26/...
3,231866,6,Rodri,M,90,65,80,86,84,86,...,Premier League,Manchester City,"['Tiki Taka+', 'Aerial Fortress', 'Bruiser', '...",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN,https://ratings-images-prod.pulse.ea.com/FC26/...
4,203376,8,Virgil van Dijk,M,90,73,60,72,72,90,...,Premier League,Liverpool,"['Intercept+', 'Aerial Fortress', 'Anticipate'...",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN,https://ratings-images-prod.pulse.ea.com/FC26/...

In [4]:
players.shape

(16228, 59)

In [5]:
players.columns.tolist()

['ID',
 'Rank',
 'Name',
 'GENDER',
 'OVR',
 'PAC',
 'SHO',
 'PAS',
 'DRI',
 'DEF',
 'PHY',
 'Acceleration',
 'Sprint Speed',
 'Positioning',
 'Finishing',
 'Shot Power',
 'Long Shots',
 'Volleys',
 'Penalties',
 'Vision',
 'Crossing',
 'Free Kick Accuracy',
 'Short Passing',
 'Long Passing',
 'Curve',
 'Dribbling',
 'Agility',
 'Balance',
 'Reactions',
 'Ball Control',
 'Composure',
 'Interceptions',
 'Heading Accuracy',
 'Def Awareness',
 'Standing Tackle',
 'Sliding Tackle',
 'Jumping',
 'Stamina',
 'Strength',
 'Aggression',
 'Position',
 'Weak foot',
 'Skill moves',
 'Preferred foot',
 'Height',
 'Weight',
 'Alternative positions',
 'Age',
 'Nation',
 'League',
 'Team',
 'play style',
 'url',
 'GK Diving',
 'GK Handling',
 'GK Kicking',
 'GK Positioning',
 'GK Reflexes',
 'card']

In [6]:
players.describe()

,ID,Rank,OVR,PAC,SHO,PAS,DRI,DEF,PHY,Acceleration,...,Strength,Aggression,Weak foot,Skill moves,Age,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes
count,16228.000000,16228.000000,16228.000000,16228.000000,16228.000000,16228.000000,16228.000000,16228.000000,16228.00000,16228.000000,...,16228.000000,16228.000000,16228.000000,16228.000000,16228.000000,1816.000000,1816.000000,1816.000000,1816.000000,1816.000000
mean,215646.635322,9360.295415,66.241126,68.151836,54.346069,58.602662,63.659354,50.563902,65.21124,64.666687,...,65.319509,56.353340,2.943493,2.375770,25.854449,65.078744,63.213106,62.340308,63.648678,65.838106
std,68202.909896,5050.951462,6.823219,10.435775,13.717709,9.615111,9.126835,16.533785,9.46065,15.465171,...,12.234758,16.636886,0.669765,0.774531,4.690417,7.457566,7.186018,7.439071,8.016507,7.889122
min,19541.000000,1.000000,47.000000,30.000000,21.000000,25.000000,29.000000,15.000000,32.00000,15.000000,...,25.000000,11.000000,1.000000,1.000000,17.000000,45.000000,45.000000,45.000000,41.000000,45.000000
25%,209219.750000,5119.750000,62.000000,62.000000,45.000000,52.000000,58.000000,36.000000,59.00000,57.000000,...,58.000000,47.000000,3.000000,2.000000,22.000000,60.000000,58.000000,57.000000,58.000000,60.000000
50%,241153.500000,9510.500000,66.000000,69.000000,57.000000,59.000000,64.000000,55.000000,66.00000,68.000000,...,66.000000,60.000000,3.000000,2.000000,25.000000,65.000000,63.000000,62.000000,64.000000,66.000000
75%,261788.000000,13707.250000,70.000000,75.000000,64.000000,65.000000,70.000000,64.000000,72.00000,75.000000,...,74.000000,68.000000,3.000000,3.000000,29.000000,70.000000,68.000000,67.000000,69.000000,71.000000
max,279948.000000,17873.000000,91.000000,97.000000,92.000000,92.000000,93.000000,90.000000,91.00000,97.000000,...,95.000000,94.000000,5.000000,5.000000,44.000000,90.000000,90.000000,91.000000,90.000000,90.000000

In [7]:
print(players['Nation'].value_counts().head(10))
"""اكثر عشر دول عندها لاعبين"""

Nation
England           1411
Germany           1122
Argentina          979
France             843
Spain              843
Italy              531
Holland            410
Korea Republic     400
United States      400
Norway             385
Name: count, dtype: int64

'اكثر عشر دول عندها لاعبين'

In [8]:
players['Position'].value_counts()

Position
CB     2950
ST     2233
CM     1976
GK     1816
RB     1273
CDM    1267
LB     1210
LM      971
CAM     963
RM      902
RW      338
LW      329
Name: count, dtype: int64

In [9]:
players[['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']].head(10)

              Name   Nation Position  OVR  PAC  SHO  PAS  DRI  DEF  PHY
0    Mohamed Salah    Egypt       RM   91   89   88   86   90   45   76
1    Kylian Mbappé   France       ST   91   97   90   81   92   37   76
2  Ousmane Dembélé   France       ST   90   91   88   83   93   50   69
3            Rodri    Spain      CDM   90   65   80   86   84   86   85
4  Virgil van Dijk  Holland       CB   90   73   60   72   72   90   87
5  Jude Bellingham  England      CAM   90   80   86   83   90   78   85
6   Erling Haaland   Norway       ST   90   86   91   70   80   45   88
7         Raphinha   Brazil       LM   89   91   84   85   87   53   75
8    Achraf Hakimi  Morocco       RB   89   92   79   82   83   82   79
9     Lamine Yamal    Spain       RM   89   85   81   86   90   23   53

In [10]:
results_teams = set(results['home_team'].unique()) | set(results['away_team'].unique())
players_nations = set(players['Nation'].unique())
fifa_teams = set(fifa['country_full'].unique())

print("نتائج vs لاعبين:")
print(results_teams - players_nations)
print("\nنتائج vs فيفا رانكينج:")
print(results_teams - fifa_teams)

نتائج vs لاعبين:
{'Niue', 'Eswatini', 'Czechoslovakia', 'Two Sicilies', 'Kazakhstan', 'Jersey', 'Mauritius', 'Donetsk PR', 'Sark', 'United States Virgin Islands', 'Saint Barthélemy', 'Seborga', 'North Korea', 'Bahrain', 'Parishes of Jersey', 'Shetland', 'Tibet', 'Elba Island', 'Singapore', 'Nepal', 'West Papua', 'Turks and Caicos Islands', 'Saugeais', 'Saint Martin', 'Réunion', 'Falkland Islands', 'Wallis Islands and Futuna', 'Frøya', 'Menorca', 'Ynys Môn', 'Åland Islands', 'Kabylia', 'Turkmenistan', 'Kárpátalja', 'Catalonia', 'Yugoslavia', 'Laos', 'Brunei', 'Sápmi', 'Qatar', 'Fiji', 'Mapuche', 'County of Nice', 'Yoruba Nation', 'Basque Country', 'Saint Lucia', 'Artsakh', 'Western Australia', 'Raetia', 'Martinique', 'French Guiana', 'Anguilla', 'Marshall Islands', 'Northern Mariana Islands', 'Sint Maarten', 'Yorkshire', 'DR Congo', 'Brittany', 'Crimea', 'Vietnam', 'Cilento', 'Saint Kitts and Nevis', 'Guadeloupe', 'Maldives', 'Iraqi Kurdistan', 'Isle of Wight', 'Sudan', 'Lesotho', 'Dominica', 'Netherlands', 'Bonaire', 'Guam', 'Aymara', 'Cayman Islands', 'Vatican City', 'Macau', 'Western Isles', 'Arameans Suryoye', 'Hitra', 'Luhansk PR', 'Asturias', 'Gotland', 'Oman', 'Saare County', 'Ellan Vannin', 'Puerto Rico', 'San Marino', 'Monaco', 'Saarland', 'Somaliland', 'Central Spain', 'Corsica', 'American Samoa', 'Djibouti', 'Belize', 'South Korea', 'Chechnya', 'Chagos Islands', 'Yemen', 'Alderney', 'Tahiti', 'Guernsey', 'Kernow', 'Franconia', 'Panjab', 'Mongolia', 'Tamil Eelam', 'British Virgin Islands', 'Orkney', 'Manchukuo', 'Greenland', 'Hmong', 'Provence', 'Mayotte', 'Republic of St. Pauli', 'Taiwan', 'Biafra', 'South Yemen', 'Padania', 'Northern Cyprus', 'Székely Land', 'São Tomé and Príncipe', 'Bahamas', 'Silesia', 'Cook Islands', 'Ethiopia', 'Western Sahara', 'United Koreans in Japan', 'Andalusia', 'Palau', 'South Sudan', 'Cape Verde', 'Botswana', 'Darfur', 'Maule Sur', 'Canary Islands', 'Kyrgyzstan', 'Kuwait', 'Matabeleland', 'Myanmar', 'Yemen DPR', 'Ryūkyū', 'Tonga', 'Samoa', 'Sealand', 'South Ossetia', 'Ticino', 'Ivory Coast', 'Madrid', 'Rhodes', 'Occitania', 'Micronesia', 'Saint Helena', 'Kiribati', 'Papua New Guinea', 'Abkhazia', 'North Vietnam', 'Cascadia', 'Zanzibar', 'Romani people', 'Cambodia', 'Western Armenia', 'Délvidék', 'Saint Vincent and the Grenadines', 'Ambazonia', 'Felvidék', 'Saint Pierre and Miquelon', 'Gozo', 'Tuvalu', 'Vietnam Republic', 'Solomon Islands', 'New Caledonia', 'Bhutan', 'Isle of Man', 'Timor-Leste', 'Barawa', 'Chameria', 'Galicia', 'Nicaragua', 'Găgăuzia', 'Surrey', 'German DR', 'Aruba', 'Seychelles', 'Eritrea'}

نتائج vs فيفا رانكينج:
{'Niue', 'Two Sicilies', 'Jersey', 'Donetsk PR', 'Sark', 'United States Virgin Islands', 'Saint Barthélemy', 'Seborga', 'North Korea', 'Parishes of Jersey', 'Shetland', 'Tibet', 'Elba Island', 'West Papua', 'Saugeais', 'Saint Martin', 'Réunion', 'Falkland Islands', 'Wallis Islands and Futuna', 'Frøya', 'Menorca', 'Ynys Môn', 'Åland Islands', 'Kabylia', 'Kárpátalja', 'Catalonia', 'Brunei', 'Sápmi', 'Mapuche', 'County of Nice', 'Yoruba Nation', 'Basque Country', 'Saint Lucia', 'Artsakh', 'Western Australia', 'Raetia', 'Martinique', 'French Guiana', 'Marshall Islands', 'Northern Mariana Islands', 'Sint Maarten', 'Yorkshire', 'DR Congo', 'Brittany', 'Crimea', 'Cilento', 'Saint Kitts and Nevis', 'Guadeloupe', 'Iraqi Kurdistan', 'Isle of Wight', 'Bonaire', 'Aymara', 'Vatican City', 'Western Isles', 'Arameans Suryoye', 'Hitra', 'Luhansk PR', 'Asturias', 'Gotland', 'Ellan Vannin', 'Saare County', 'Czech Republic', 'Monaco', 'Saarland', 'Somaliland', 'Central Spain', 'Corsica', 'South Korea', 'Chechnya', 'Chagos Islands', 'Alderney', 'Guernsey', 'Kernow', 'Franconia', 'Panjab', 'Tamil Eelam', 'Manchukuo', 'Orkney', 'Greenland', 'Hmong', 'Provence', 'Mayotte', 'Republic of St. Pauli', 'Taiwan', 'Biafra', 'South Yemen', 'Padania', 'Northern Cyprus', 'Székely Land', 'São Tomé and Príncipe', 'Silesia', 'Western Sahara', 'United Koreans in Japan', 'Andalusia', 'Palau', 'Cape Verde', 'Darfur', 'Maule Sur', 'Canary Islands', 'Kyrgyzstan', 'Matabeleland', 'Yemen DPR', 'Ryūkyū', 'Sealand', 'Iran', 'South Ossetia', 'Ticino', 'Ivory Coast', 'Madrid', 'Curaçao', 'Rhodes', 'Occitania', 'Micronesia', 'Saint Helena', 'Kiribati', 'United States', 'Abkhazia', 'North Vietnam', 'Cascadia', 'Zanzibar', 'Romani people', 'Western Armenia', 'Délvidék', 'Gambia', 'Saint Vincent and the Grenadines', 'Ambazonia', 'Felvidék', 'Saint Pierre and Miquelon', 'Gozo', 'Tuvalu', 'Vietnam Republic', 'Isle of Man', 'Barawa', 'Chameria', 'Galicia', 'Găgăuzia', 'Surrey', 'German DR'}

In [11]:
# القائمة الكاملة للمنتخبات المتأهلة لكأس العالم 2026 (48 منتخب)
wc_2026_teams = [
    # مضيفين
    'USA', 'Mexico', 'Canada',
    # أمريكا الجنوبية
    'Argentina', 'Brazil', 'Uruguay', 'Colombia', 'Ecuador', 'Paraguay',
    # آسيا
    'Japan', 'South Korea', 'Australia', 'IR Iran', 'Jordan', 'Uzbekistan',
    'Saudi Arabia', 'Qatar', 'Iraq',
    # أفريقيا
    'Morocco', 'Tunisia', 'Senegal', 'Ghana', 'Ivory Coast',
    'Egypt', 'Algeria', 'South Africa', 'Cabo Verde', 'DR Congo',
    # أوروبا
    'England', 'France', 'Spain', 'Portugal', 'Germany', 'Netherlands',
    'Belgium', 'Croatia', 'Switzerland', 'Norway', 'Scotland', 'Austria',
    'Bosnia and Herzegovina', 'Sweden', 'Turkey', 'Czech Republic',
    # كونكاكاف
    'Panama', 'Curaçao', 'Haiti',
    # أوقيانوسيا
    'New Zealand',
]

# توحيد أسماء players
players['Nation'] = players['Nation'].replace({
    'Holland': 'Netherlands',
    'Korea Republic': 'South Korea',
    "Côte d'Ivoire": 'Ivory Coast',
    'Iran': 'IR Iran',
    'United States': 'USA',
    'Cape Verde Islands': 'Cabo Verde',  # إصلاح: كان 'Cabe Verde' خطأ إملائي
    'Congo DR': 'DR Congo',
    'Curacao': 'Curaçao',
    'Türkiye': 'Turkey',
    'Czechia': 'Czech Republic',
    'Bosnia Herzegovina': 'Bosnia and Herzegovina',
})

# فلتر بس على منتخبات كاس العالم
players_wc = players[players['Nation'].isin(wc_2026_teams)]

print(f"عدد اللاعبين: {len(players_wc)}")
print(f"عدد المنتخبات: {players_wc['Nation'].nunique()}")
print(f"\nمنتخبات ناقصة:")
missing = [t for t in wc_2026_teams if t not in players_wc['Nation'].unique()]
print(missing)

# 48 منتخب متأهل رسمياً — الأسماء موحدة على results_features.csv
wc_2026_confirmed = [
    # مضيفين
    'USA', 'Mexico', 'Canada',
    # آسيا (9 منتخبات)
    'Australia', 'IR Iran', 'Japan', 'Jordan', 'South Korea',
    'Qatar', 'Saudi Arabia', 'Uzbekistan', 'Iraq',
    # أفريقيا (10 منتخبات)
    'Algeria', 'Cabo Verde', 'Ivory Coast', 'Egypt', 'Ghana',
    'Morocco', 'Senegal', 'South Africa', 'Tunisia', 'DR Congo',
    # كونكاكاف
    'Curaçao', 'Haiti', 'Panama',
    # أمريكا الجنوبية
    'Argentina', 'Brazil', 'Colombia', 'Ecuador', 'Paraguay', 'Uruguay',
    # أوقيانوسيا
    'New Zealand',
    # أوروبا (16 منتخب)
    'Austria', 'Belgium', 'Croatia', 'England', 'France', 'Germany',
    'Netherlands', 'Norway', 'Portugal', 'Scotland', 'Spain', 'Switzerland',
    'Bosnia and Herzegovina', 'Sweden', 'Turkey', 'Czech Republic',
]

print(f"متأهلون رسمياً: {len(wc_2026_confirmed)}")
assert len(wc_2026_confirmed) == 48, f"خطأ: عدد المنتخبات {len(wc_2026_confirmed)} وليس 48"

عدد اللاعبين: 11544
عدد المنتخبات: 47

منتخبات ناقصة:

['Qatar']
متأهلون رسمياً: 48

In [12]:
# فلتر players على الـ 48 المتأهلين فقط
players_wc = players[players['Nation'].isin(wc_2026_confirmed)]

print(f"عدد اللاعبين: {len(players_wc)}")
print(f"عدد المنتخبات: {players_wc['Nation'].nunique()}")
print(f"\nمنتخبات ناقصة:")
missing = [t for t in wc_2026_confirmed if t not in players_wc['Nation'].unique()]
print(missing)

عدد اللاعبين: 11544
عدد المنتخبات: 47

منتخبات ناقصة:
['Qatar']

In [13]:
#اورويا

In [14]:
england_squad_search = [
    # Goalkeepers
    'Jordan Pickford', 'Dean Henderson', 'Nick Pope',
    # Defenders
    'Ezri Konsa', 'Benjamin White', 'Marc Guéhi', 'Harry Maguire',
    'John Stones', 'Trent Alexander-Arnold', 'Levi Colwill',
    'Luke Shaw',
    # Midfielders
    'Jude Bellingham', 'Cole Palmer', 'Phil Foden', 'Declan Rice',
    'James Maddison', 'Morgan Gibbs-White', 'Eberechi Eze',
    'Adam Wharton',
    # Forwards
    'Harry Kane', 'Bukayo Saka', 'Anthony Gordon', 'Jarrod Bowen',
    'Ollie Watkins', 'Morgan Rogers', 'Jadon Sancho',
]

england_data = players[
    (players['Name'].isin(england_squad_search)) &
    (players['Nation'] == 'England')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]

england_data = england_data.drop_duplicates(subset='Name')
england_data['team'] = 'England'

print(f"عدد اللاعبين: {len(england_data)}")
print(england_data[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

عدد اللاعبين: 26
                  Name Position  OVR
       Jude Bellingham      CAM   90
            Harry Kane       ST   89
           Bukayo Saka       RW   88
           Cole Palmer      CAM   87
           Declan Rice      CDM   87
Trent Alexander-Arnold       RB   86
            Phil Foden       RW   85
       Jordan Pickford       GK   84
         Ollie Watkins       ST   84
        James Maddison       CM   84
          Jarrod Bowen       RM   83
        Benjamin White       RB   83
          Eberechi Eze      CAM   83
        Anthony Gordon       LW   83
         Morgan Rogers      CAM   82
    Morgan Gibbs-White      CAM   82
            Ezri Konsa       CB   82
           John Stones       CB   82
            Marc Guéhi       CB   82
        Dean Henderson       GK   81
             Nick Pope       GK   81
          Levi Colwill       CB   80
          Jadon Sancho       LW   80
         Harry Maguire       CB   80
             Luke Shaw       CB   79
          Adam Wharton      CDM   79

In [15]:
france_squad_search = [
    'Brice Samba', 'Mike Maignan', 'Lucas Chevalier',
    'Malo Gusto', 'Lucas Digne', 'Dayot Upamecano', 'Pierre Kalulu',
    'Ibrahima Konaté', 'Maxence Lacroix', 'Theo Hernández', 'William Saliba',
    'Eduardo Camavinga', 'Aurélien Tchouaméni', "N'Golo Kanté",
    'Adrien Rabiot', 'Warren Zaïre-Emery', 'Désiré Doué', 'Rayan Cherki',
    'Maghnes Akliouche',
    'Ousmane Dembélé', 'Michael Olise', 'Marcus Thuram',
    'Kylian Mbappé', 'Randal Kolo Muani', 'Hugo Ekitiké', 'Bradley Barcola'
]

france_data = players[players['Name'].isin(france_squad_search)][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
france_data['team'] = 'France'

print(f"عدد اللاعبين: {len(france_data)}")
print(france_data[['Name', 'Position', 'OVR']].to_string())

عدد اللاعبين: 26
                    Name Position  OVR
1          Kylian Mbappé       ST   91
2        Ousmane Dembélé       ST   90
39        William Saliba       CB   87
43          Mike Maignan       GK   87
51         Michael Olise       RM   86
57       Ibrahima Konaté       CB   86
73          N'Golo Kanté      CDM   85
74           Désiré Doué       RW   85
77         Marcus Thuram       ST   85
92       Dayot Upamecano       CB   85
95        Theo Hernández       LB   84
105  Aurélien Tchouaméni      CDM   84
131      Bradley Barcola       LW   84
140        Adrien Rabiot      CAM   83
141    Eduardo Camavinga       CM   83
156      Lucas Chevalier       GK   83
183         Hugo Ekitiké       ST   83
344    Randal Kolo Muani       ST   81
361         Rayan Cherki       RW   81
380   Warren Zaïre-Emery       CM   80
387          Brice Samba       GK   80
401          Lucas Digne       LB   80
433        Pierre Kalulu       CB   80
458    Maghnes Akliouche       RM   80
566           Malo Gusto       RB   79
610      Maxence Lacroix       CB   79

In [16]:
spain_squad_search = [
    'David Raya', 'Unai Simón', 'Joan García',
    'Mosquera', 'Grimaldo', 'Pau Cubarsí', 'Dean Huijsen',
    'Pedro Porro', 'Aymeric Laporte', 'Marc Cucurella',
    'Marcos Llorente', 'Carlos Soler', 'Rodri', 'Pablo Fornals',
    'Zubimendi', 'Pedri', 'Oyarzabal', 'Álex Baena',
    'Ferran Torres', 'Borja Iglesias', 'Dani Olmo', 'Yeremy Pino',
    'Lamine Yamal', 'Víctor Muñoz', 'Barrenetxea', 'Fabián Ruiz'
]

spain_data = players[players['Name'].isin(spain_squad_search)][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
spain_data['team'] = 'Spain'

print(f"عدد اللاعبين: {len(spain_data)}")
print(spain_data[['Name', 'Position', 'OVR']].to_string())

عدد اللاعبين: 26
                 Name Position  OVR
3               Rodri      CDM   90
9        Lamine Yamal       RM   89
12              Pedri       CM   89
45         David Raya       GK   87
76         Unai Simón       GK   85
84        Fabián Ruiz       CM   85
91          Dani Olmo      CAM   85
96    Marcos Llorente       RB   84
106    Marc Cucurella       LB   84
107          Grimaldo       LM   84
111        Álex Baena       LM   84
152       Joan García       GK   83
166         Zubimendi      CDM   83
179     Ferran Torres       LW   83
203       Pedro Porro       RB   82
245      Dean Huijsen       CB   82
247         Oyarzabal       ST   82
266       Pau Cubarsí       CB   82
274   Aymeric Laporte       CB   82
473    Borja Iglesias       ST   80
476       Yeremy Pino       RM   80
513     Pablo Fornals      CDM   79
890      Carlos Soler       CM   77
1065      Barrenetxea       LM   77
1094         Mosquera       CB   77
9746     Víctor Muñoz       LW   65

In [17]:
portugal_squad_search = [
    # Goalkeepers
    'Diogo Costa', 'Rui Silva', 'José Sá',
    # Defenders
    'Diogo Dalot', 'António Silva', 'Gonçalo Inácio',
    'João Cancelo', 'Nuno Mendes', 'Renato Veiga',
    # Midfielders
    'Matheus Nunes', 'Bruno Fernandes',
    'João Neves', 'Pedro Gonçalves', 'Rúben Neves',
    'Francisco Conceição', 'Ricardo Horta',
    'Vitinha', 'Samu',
    # Forwards
    'Gonçalo Ramos', 'João Félix', 'Rafael Leão',
    'Pedro Neto', 'Gonçalo Guedes', 'Rodrigo Mora',
    'Cristiano Ronaldo', 'Paulinho',
]

portugal_data = players[
    (players['Name'].isin(portugal_squad_search)) &
    (players['Nation'] == 'Portugal')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]

portugal_data = portugal_data.drop_duplicates(subset='Name')
portugal_data['team'] = 'Portugal'

print(f"عدد اللاعبين: {len(portugal_data)}")
print(portugal_data[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

عدد اللاعبين: 26
               Name Position  OVR
            Vitinha       CM   89
    Bruno Fernandes      CAM   87
        Nuno Mendes       LB   86
         João Neves       CM   85
  Cristiano Ronaldo       ST   85
       João Cancelo       RB   84
        Rúben Neves      CDM   84
        Diogo Costa       GK   84
        Rafael Leão       LW   84
    Pedro Gonçalves      CAM   83
      Ricardo Horta      CAM   81
          Rui Silva       GK   81
     Gonçalo Inácio       CB   81
      Gonçalo Ramos       ST   80
         Pedro Neto       RM   80
      Matheus Nunes       RB   79
        Diogo Dalot       RB   79
         João Félix      CAM   79
Francisco Conceição       RM   79
      António Silva       CB   78
            José Sá       GK   77
       Renato Veiga       CB   76
       Rodrigo Mora      CAM   76
     Gonçalo Guedes       ST   75
               Samu       CM   73
           Paulinho       ST   64

In [18]:
germany_squad_search = [
    'Joshua Kimmich', 'Florian Wirtz', 'Jamal Musiala',
    'Jonathan Tah', 'Antonio Rüdiger', 'Marc-André ter Stegen',
    'Nico Schlotterbeck', 'Manuel Neuer', 'Oliver Baumann',
    'Angelo Stiller', 'Leon Goretzka', 'Felix Nmecha',
    'David Raum', 'Leroy Sané', 'Serge Gnabry',
    'Kai Havertz', 'Waldemar Anton', 'Pascal Groß',
    'Deniz Undav', 'Anton Stach', 'Nick Woltemade',
    'Malick Thiaw', 'Kevin Schade', 'Chris Führich',
    'Nathaniel Brown', 'Jamie Leweling'
]

germany_data = players[players['Name'].isin(germany_squad_search)][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
germany_data = germany_data.drop_duplicates(subset='Name')
germany_data['team'] = 'Germany'

print(f"عدد اللاعبين: {len(germany_data)}")
print(germany_data[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string())

عدد اللاعبين: 26
                       Name Position  OVR
13           Joshua Kimmich      CDM   89
18            Florian Wirtz      CAM   89
23            Jamal Musiala      CAM   88
41             Jonathan Tah       CB   87
50          Antonio Rüdiger       CB   86
63    Marc-André ter Stegen       GK   86
81       Nico Schlotterbeck       CB   85
116            Manuel Neuer       GK   84
164          Oliver Baumann       GK   83
180          Angelo Stiller      CDM   83
262          Waldemar Anton       CB   82
244             Kai Havertz       ST   82
240            Serge Gnabry       LM   82
235              Leroy Sané       RM   82
213              David Raum       LB   82
198            Felix Nmecha      CDM   82
196           Leon Goretzka       CM   82
418             Pascal Groß      CDM   80
463             Deniz Undav       ST   80
521             Anton Stach      CDM   79
623          Nick Woltemade       ST   79
774            Malick Thiaw       CB   78
790            Kevin Schade       LM   78
1004          Chris Führich       LM   77
1047        Nathaniel Brown       LB   77
1507         Jamie Leweling       RM   75

In [19]:
netherlands_squad_search = [
    'Bart Verbruggen', 'Justin Bijlow', 'Mark Flekken',
    'Matthijs de Ligt', 'Jan Paul van Hecke', 'Virgil van Dijk',
    'Nathan Aké', 'Stefan de Vrij', 'Jeremie Frimpong',
    'Jurriën Timber', 'Micky van de Ven', 'Denzel Dumfries', 'Jorrel Hato',
    'Xavi Simons', 'Ryan Gravenberch', 'Frenkie de Jong',
    'Tijjani Reijnders', 'Jerdy Schouten', 'Teun Koopmeiners',
    'Quinten Timber', 'Wout Weghorst', 'Cody Gakpo',
    'Noa Lang', 'Donyell Malen', 'Brian Brobbey', 'Steven Bergwijn'
]

netherlands_data = players[players['Name'].isin(netherlands_squad_search)][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
netherlands_data['team'] = 'Netherlands'

print(f"عدد اللاعبين: {len(netherlands_data)}")
print(netherlands_data[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string())

عدد اللاعبين: 26
                    Name Position  OVR
4        Virgil van Dijk       CB   90
32       Frenkie de Jong       CM   87
62     Tijjani Reijnders       CM   86
68      Ryan Gravenberch      CDM   85
102      Denzel Dumfries       RB   84
115          Xavi Simons      CAM   84
118           Cody Gakpo       LM   84
138       Stefan de Vrij       CB   84
161     Jeremie Frimpong       RB   83
178           Nathan Aké       CB   83
234     Micky van de Ven       CB   82
238       Jurriën Timber       RB   82
263     Matthijs de Ligt       CB   82
295     Teun Koopmeiners      CAM   81
368       Quinten Timber       CM   80
423             Noa Lang       LW   80
429      Steven Bergwijn       LM   80
450       Jerdy Schouten      CDM   80
461   Jan Paul van Hecke       CB   80
590        Donyell Malen       RM   79
672      Bart Verbruggen       GK   78
751         Mark Flekken       GK   78
775          Jorrel Hato       LB   78
813        Wout Weghorst       ST   78
1079       Brian Brobbey       ST   77
1504       Justin Bijlow       GK   75

In [20]:
belgium_squad_search = [
    'Thibaut Courtois', 'Senne Lammens', 'Matz Sels',
    'Zeno Debast', 'Arthur Theate', 'Brandon Mechele',
    'Axel Witsel', 'Wout Faes', 'Joaquin Seys',
    'Nathan Ngoy', 'Timothy Castagne',
    'Maxim De Cuyper', 'Kevin De Bruyne', 'Youri Tielemans',
    'Jérémy Doku', 'Thomas Meunier', 'Charles De Ketelaere',
    'Leandro Trossard', 'Hans Vanaken', 'Alexis Saelemaekers',
    'Nicolas Raskin', 'Amadou Onana',
    'Loïs Openda', 'Romelu Lukaku', 'Dodi Lukébakio', 'Yannick Carrasco'
]

belgium_data = players[players['Name'].isin(belgium_squad_search)][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
belgium_data['team'] = 'Belgium'

print(f"عدد اللاعبين: {len(belgium_data)}")
print(belgium_data[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string())

عدد اللاعبين: 26
                      Name Position  OVR
19        Thibaut Courtois       GK   89
31         Kevin De Bruyne       CM   87
85         Youri Tielemans       CM   85
129          Romelu Lukaku       ST   84
167              Matz Sels       GK   83
172            Loïs Openda       ST   83
188       Leandro Trossard       LW   83
237   Charles De Ketelaere      CAM   82
258         Dodi Lukébakio       RM   82
300       Yannick Carrasco       LW   81
448            Jérémy Doku       LW   80
469          Arthur Theate       CB   80
443           Hans Vanaken      CAM   80
375        Maxim De Cuyper       LB   80
529           Amadou Onana      CDM   79
557    Alexis Saelemaekers       RM   79
733            Zeno Debast      CDM   78
821          Senne Lammens       GK   78
914         Nicolas Raskin      CDM   77
1095           Axel Witsel       CB   77
1134        Thomas Meunier       RB   76
1255      Timothy Castagne       RB   76
1371       Brandon Mechele       CB   76
2721             Wout Faes       CB   73
3142          Joaquin Seys       RB   72
7151           Nathan Ngoy       CB   67

In [21]:
croatia_squad_search = [
    'Dominik Livaković', 'Dominik Kotarski', 'Ivor Pandur',
    'Josip Stanišić', 'Marin Pongračić', 'Duje Ćaleta-Car',
    'Josip Šutalo', 'Luka Vušković', 'Martin Erlić',
    'Joško Gvardiol', 'Lovro Majer', 'Nikola Moro', 'Luka Modrić',
    'Nikola Vlašić', 'Ivan Perišić', 'Mario Pašalić', 'Martin Baturina',
    'Petar Sučić', 'Kristijan Jakić', 'Luka Sučić',
    'Mateo Kovačić', 'Marcelo Brozović',
    'Andrej Kramarić', 'Ante Budimir', 'Igor Matanović', 'Petar Musa'
]

croatia_data = players[players['Name'].isin(croatia_squad_search)][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
croatia_data['team'] = 'Croatia'

print(f"عدد اللاعبين: {len(croatia_data)}")
print(croatia_data[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string())

عدد اللاعبين: 26
                   Name Position  OVR
104      Joško Gvardiol       LB   84
162         Luka Modrić       CM   83
157       Mateo Kovačić       CM   83
278        Ante Budimir       ST   82
296        Ivan Perišić       RW   81
304    Marcelo Brozović      CDM   81
348     Andrej Kramarić      CAM   81
395       Mario Pašalić       CM   80
397   Dominik Livaković       GK   80
550       Nikola Vlašić      CAM   79
719     Martin Baturina      CAM   78
833        Josip Šutalo       CB   78
819      Josip Stanišić       CB   78
702         Lovro Majer       CM   78
662          Luka Sučić       CM   78
954    Dominik Kotarski       GK   77
1204    Kristijan Jakić      CDM   76
1263         Petar Musa       ST   76
1434        Nikola Moro      CDM   75
1842        Petar Sučić       CM   74
2186    Duje Ćaleta-Car       CB   74
2201    Marin Pongračić       CB   74
3084        Ivor Pandur       GK   72
3200      Luka Vušković       CB   72
3378       Martin Erlić       CB   72
3919     Igor Matanović       ST   71

In [22]:
switzerland_squad_search = [
    'Yann Sommer', 'Gregor Kobel', 'Marvin Keller',
    'Lucas Blondel', 'Miro Muheim', 'Silvan Widmer', 'Nico Elvedi',
    'Manuel Akanji', 'Ricardo Rodriguez', 'Cedric Zesiger',
    'Eray Cömert', 'Ulisses Garcia', 'Luca Jaquez', 'Isaac Schmidt',
    'Stefan Gartenmann',
    'Denis Zakaria', 'Remo Freuler',
    'Granit Xhaka', 'Ardon Jashari', 'Djibril Sow',
    'Vincent Sierro', 'Ruben Vargas', 'Michel Aebischer',
    'Fabian Rieder', 'Dan Ndoye', 'Zeki Amdouni', 'Noah Okafor',
    'Breel Embolo'
]

switzerland_data = players[players['Name'].isin(switzerland_squad_search)][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
switzerland_data['team'] = 'Switzerland'

print(f"عدد اللاعبين: {len(switzerland_data)}")
print(switzerland_data[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string())

عدد اللاعبين: 26
                   Name Position  OVR
36          Yann Sommer       GK   87
64         Gregor Kobel       GK   86
86         Granit Xhaka      CDM   85
204       Denis Zakaria      CDM   82
254       Manuel Akanji       CB   82
330        Remo Freuler      CDM   81
526           Dan Ndoye       LM   79
876       Ardon Jashari      CDM   77
930        Breel Embolo       ST   77
1091        Nico Elvedi       CB   77
1121        Djibril Sow       CM   76
1251        Noah Okafor       ST   76
1551     Ulisses Garcia       LB   75
1565       Zeki Amdouni       ST   75
1480       Ruben Vargas       LM   75
1499     Vincent Sierro       CM   75
1422        Miro Muheim       LB   75
1812   Michel Aebischer       CM   74
1995      Fabian Rieder      CAM   74
2798      Silvan Widmer       RB   72
2872      Lucas Blondel       RB   72
3006      Marvin Keller       GK   72
3193        Eray Cömert       CB   72
3247  Stefan Gartenmann       CB   72
3523      Isaac Schmidt       LB   71
5593        Luca Jaquez       CB   69

In [23]:
norway_squad_search = [
    'Ørjan Nyland', 'Egil Selvik', 'Viljar Myhra',
    'Kristoffer Ajer', 'Torbjørn L. Heggem', 'David Møller Wolfe',
    'Julian Ryerson', 'Fredrik Bjørkan', 'Marcus Pedersen',
    'Andreas Hanche-Olsen',
    'Morten Thorsby', 'Patrick Berg', 'Sander Berge',
    'Kristian Thorstvedt', 'Felix Horn Myhre', 'Antonio Nusa',
    'Andreas Schjelderup', 'Oscar Bobb', 'Martin Ødegaard',
    'Fredrik Aursnes',
    'Alexander Sørloth', 'Erling Haaland', 'Jens Petter Hauge',
    'Jørgen Strand Larsen', 'Joshua King', 'Mohamed Elyounoussi'
]

norway_data = players[players['Name'].isin(norway_squad_search)][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
norway_data['team'] = 'Norway'

print(f"عدد اللاعبين: {len(norway_data)}")
print(norway_data[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string())

عدد اللاعبين: 26
                      Name Position  OVR
6           Erling Haaland       ST   90
44         Martin Ødegaard       CM   87
136      Alexander Sørloth       ST   84
371        Fredrik Aursnes       CM   80
519         Julian Ryerson       RB   79
579           Sander Berge      CDM   79
830   Jørgen Strand Larsen       ST   78
893           Patrick Berg      CDM   77
1162   Mohamed Elyounoussi       RM   76
1195          Ørjan Nyland       GK   76
1245          Antonio Nusa       LM   76
1535       Kristoffer Ajer       RB   75
1687  Andreas Hanche-Olsen       CB   75
1428   Kristian Thorstvedt       CM   75
1813      Felix Horn Myhre       CM   74
1877       Fredrik Bjørkan       LB   74
1946           Joshua King       ST   74
2031     Jens Petter Hauge       LW   74
2082   Andreas Schjelderup       LW   74
2381    David Møller Wolfe       LB   73
2484    Torbjørn L. Heggem       CB   73
2905       Marcus Pedersen       RB   72
2932        Morten Thorsby       CM   72
3287            Oscar Bobb       RW   72
4722           Egil Selvik       GK   70
7215          Viljar Myhra       GK   67

In [24]:
scotland_squad_search = [
    'Angus Gunn', 'Liam Kelly', 'Scott Bain',
    'Nathan Patterson', 'Andrew Robertson', 'Grant Hanley',
    'Kieran Tierney', 'Jack Hendry', 'John Souttar',
    'Ross McCrorie', 'Max Johnston', 'Anthony Ralston',
    'Scott McKenna',
    'Scott McTominay', 'John McGinn', 'Billy Gilmour',
    'Ryan Christie', 'Lewis Miller', 'Lewis Ferguson',
    'Kenny McLean', 'Andy Irving', 'Callum McGregor', 'Ryan Gauld',
    'Lyndon Dykes', 'Ché Adams', 'George Hirst', 'Tommy Conway'
]

scotland_data = players[
    (players['Name'].isin(scotland_squad_search)) &
    (players['Nation'] == 'Scotland')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]

scotland_data = scotland_data.drop_duplicates(subset='Name')
scotland_data['team'] = 'Scotland'

print(f"عدد اللاعبين: {len(scotland_data)}")
print(scotland_data[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string())

عدد اللاعبين: 26
                  Name Position  OVR
67     Scott McTominay       CM   85
225   Andrew Robertson       LB   82
289        John McGinn       LM   81
488    Callum McGregor      CDM   79
512      Ryan Christie      CDM   79
657     Lewis Ferguson       CM   78
779         Ryan Gauld       LW   78
902     Kieran Tierney       LB   77
995          Ché Adams       ST   77
1740     Scott McKenna       CB   75
1934       Jack Hendry       CB   74
2047     Billy Gilmour       CM   74
2432      John Souttar       CB   73
3167      George Hirst       ST   72
2912        Angus Gunn       GK   72
2944      Kenny McLean      CDM   72
3420   Anthony Ralston       RB   71
3699  Nathan Patterson       RB   71
4035      Grant Hanley       CB   71
4093     Ross McCrorie       RB   70
4185       Andy Irving       CM   70
4735      Tommy Conway       ST   70
6172      Max Johnston       RB   68
6512      Lyndon Dykes       ST   68
7299        Liam Kelly       GK   67
7977        Scott Bain       GK   66

In [25]:
austria_squad_search = [
    'Alexander Schlager', 'Tobias Lawal', 'Patrick Pentz',
    'Kevin Danso', 'Stefan Posch', 'David Alaba',
    'Philipp Lienhart', 'Phillipp Mwene', 'Marco Friedl',
    'Maximilian Wöber', 'David Affengruber',
    'Xaver Schlager', 'Nicolas Seiwald', 'Marcel Sabitzer',
    'Florian Grillitsch', 'Karim Adeyemi', 'Romano Schmid',
    'Christoph Baumgartner', 'Konrad Laimer', 'Alexander Prass',
    'Alessandro Schöpf', 'Patrick Wimmer',
    'Michael Gregoritsch', 'Valentino Lazaro', 'Kevin Stöger', 'Marco Grüll'
]

austria_data = players[players['Name'].isin(austria_squad_search)][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
austria_data['team'] = 'Austria'

print(f"عدد اللاعبين: {len(austria_data)}")
print(austria_data[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string())

عدد اللاعبين: 26
                       Name Position  OVR
210           Konrad Laimer       RB   82
214             David Alaba       CB   82
336           Karim Adeyemi       RM   81
369         Marcel Sabitzer      CDM   80
400          Xaver Schlager      CDM   80
600            Stefan Posch       RB   79
643             Kevin Danso       CB   79
644        Philipp Lienhart       CB   79
768           Romano Schmid      CAM   78
915         Nicolas Seiwald      CDM   77
944          Patrick Wimmer      CAM   77
1037           Marco Friedl       CB   77
1040  Christoph Baumgartner      CAM   77
1271           Kevin Stöger      CAM   76
1184       Valentino Lazaro       RM   76
1227         Phillipp Mwene       LB   76
1561     Florian Grillitsch       CM   75
1600            Marco Grüll       LM   75
1629       Maximilian Wöber       CB   75
1640      David Affengruber       CB   75
1725    Michael Gregoritsch       ST   75
1784        Alexander Prass       LB   74
2399     Alexander Schlager       GK   73
2888          Patrick Pentz       GK   72
3135           Tobias Lawal       GK   72
5892      Alessandro Schöpf       CM   68

In [26]:
bosnia_squad_search = [
    # Goalkeepers
    'Nikola Vasilj', 'Vladan Kovacević', 'Asmir Begović',
    # Defenders
    'Sead Kolašinac', 'Amar Dedić', 'Nidal Čelik',
    'Anel Ahmedhodžić', 'Nikola Katić', 'Tarik Muharemović',
    'Nihad Mujakić', 'Adrian Barišić',
    # Midfielders
    'Amir Hadžiahmetović', 'Armin Gigović', 'Dženis Burnić',
    'Benjamin Tahirović', 'Amar Memić', 'Denis Huseinbašić',
    'Esmir Bajraktarević',
    # Forwards
    'Edin Džeko', 'Haris Tabaković', 'Ermedin Demirović',
    'Samed Baždar', 'Jovo Lukić', 'Kerim Alajbegović',
    'Milan Đurić', 'Luka Kulenović',
]

bosnia_final = players[
    (players['Name'].isin(bosnia_squad_search)) &
    (players['Nation'] == 'Bosnia and Herzegovina')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
bosnia_final['team'] = 'Bosnia and Herzegovina'

print(f"إجمالي اللاعبين: {len(bosnia_final)}")
print(bosnia_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
               Name Position  OVR
         Edin Džeko       ST   81
  Ermedin Demirović       ST   80
     Sead Kolašinac       CB   79
      Nikola Vasilj       GK   77
   Anel Ahmedhodžić       CB   74
         Amar Dedić       RB   73
Amir Hadžiahmetović      CDM   73
    Haris Tabaković       ST   73
      Armin Gigović       CM   72
  Denis Huseinbašić       CM   72
         Amar Memić       RM   72
     Adrian Barišić       CB   72
        Milan Đurić       ST   71
  Tarik Muharemović       CB   70
   Vladan Kovacević       GK   70
      Asmir Begović       GK   70
       Samed Baždar       ST   69
     Luka Kulenović       ST   69
       Nikola Katić       CB   69
      Dženis Burnić       CM   68
Esmir Bajraktarević       RW   67
 Benjamin Tahirović      CDM   67
      Nihad Mujakić       CB   67
         Jovo Lukić       ST   64
        Nidal Čelik       CB   64
  Kerim Alajbegović       LM   61

In [27]:
sweden_squad_search = [
    # Goalkeepers
    'Kristoffer Nordfeldt', 'Noel Törnqvist', 'Melker Ellborg',
    # Defenders
    'Carl Starfelt', 'Daniel Svensson', 'Isak Hien',
    'Gustaf Lagerbielke', 'Gabriel Gudmundsson', 'Emil Krafth',
    'Herman Johansson', 'Samuel Dahl',
    # Midfielders
    'Mattias Svanberg', 'Jesper Karlström', 'Yasin Ayari',
    'Hugo Larsson', 'Besfort Zeneli', 'Elliot Stroud',
    'Lucas Bergvall',
    # Forwards
    'Viktor Gyökeres', 'Gustaf Nilsson', 'Benjamin Nygren',
    'Anthony Elanga', 'Williot Swedberg', 'Roony Bardghji',
    'Gustav Lundgren', 'Taha Ali',
]

sweden_final = players[
    (players['Name'].isin(sweden_squad_search)) &
    (players['Nation'] == 'Sweden')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
sweden_final['team'] = 'Sweden'

print(f"إجمالي اللاعبين: {len(sweden_final)}")
print(sweden_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
                Name Position  OVR
     Viktor Gyökeres       ST   87
      Anthony Elanga       RW   81
        Hugo Larsson       CM   78
       Carl Starfelt       CB   78
           Isak Hien       CB   78
 Gabriel Gudmundsson       LB   77
      Lucas Bergvall       CM   77
     Daniel Svensson       LB   77
    Mattias Svanberg       CM   76
         Yasin Ayari       CM   75
    Jesper Karlström      CDM   75
      Gustaf Nilsson       ST   75
    Williot Swedberg       LW   74
         Emil Krafth       CB   73
         Samuel Dahl       LB   73
     Benjamin Nygren       CM   72
Kristoffer Nordfeldt       GK   72
      Besfort Zeneli       CM   72
       Elliot Stroud       LB   71
    Herman Johansson       RB   70
      Noel Törnqvist       GK   70
  Gustaf Lagerbielke       CB   70
     Gustav Lundgren       RW   69
      Roony Bardghji       RM   69
            Taha Ali       LM   68
      Melker Ellborg       GK   62

In [28]:
turkey_squad_search = [
    # Goalkeepers
    'Mert Günok', 'Altay Bayındır', 'Uğurcan Çakır',
    # Defenders
    'Zeki Çelik', 'Samet Akaydın', 'Abdülkerim Bardakcı',
    'Merih Demiral', 'Mert Müldür', 'Eren Elmalı',
    'Ozan Kabak', 'Atakan Karazor',
    # Midfielders
    'Salih Özcan', 'Orkun Kökçü', 'Hakan Çalhanoğlu',
    'İsmail Yüksek', 'Ferdi Kadıoğlu', 'İrfan Can Kahveci',
    'Mustafa Eskihellaç',
    # Forwards
    'Kerem Aktürkoğlu', 'Arda Güler', 'Kenan Yıldız',
    'Oğuz Aydın', 'Yunus Akgün', 'Semih Kılıçsoy',
    'Deniz Gül', 'Aral Şimşir',
]

turkey_final = players[
    (players['Name'].isin(turkey_squad_search)) &
    (players['Nation'] == 'Turkey')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
turkey_final['team'] = 'Turkey'

print(f"إجمالي اللاعبين: {len(turkey_final)}")
print(turkey_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
               Name Position  OVR
   Hakan Çalhanoğlu      CDM   86
        Orkun Kökçü       CM   82
         Arda Güler       RM   81
      Uğurcan Çakır       GK   80
   Kerem Aktürkoğlu       LW   80
Abdülkerim Bardakcı       CB   80
     Ferdi Kadıoğlu       RB   79
       Kenan Yıldız      CAM   79
         Mert Günok       GK   78
  İrfan Can Kahveci       RW   78
        Yunus Akgün       RM   78
      Merih Demiral       CB   78
      İsmail Yüksek      CDM   77
         Oğuz Aydın       LW   77
         Zeki Çelik       RB   76
     Atakan Karazor      CDM   76
        Eren Elmalı       LB   75
        Salih Özcan      CDM   75
     Altay Bayındır       GK   75
         Ozan Kabak       CB   75
        Mert Müldür       RB   74
        Aral Şimşir       LW   73
 Mustafa Eskihellaç       LB   71
     Semih Kılıçsoy       ST   70
      Samet Akaydın       CB   70
          Deniz Gül       ST   66

In [29]:
czech_squad_search = [
    # Goalkeepers
    'Matěj Kovář', 'Martin Jedlička', 'Lukas Hornicek',
    # Defenders
    'Tomáš Holeš', 'Vladimír Coufal', 'Ladislav Krejčí',
    'Jaroslav Zelený', 'Martin Vitík', 'David Jurásek',
    'Štěpán Chaloupek', 'Robin Hranáč',
    # Midfielders
    'Lukáš Červ', 'Lukáš Provod', 'Pavel Šulc',
    'Michal Sadílek', 'Tomáš Souček', 'Pavel Bucha',
    'Adam Karabec', 'Denis Višinský',
    # Forwards
    'Patrik Schick', 'Tomáš Chorý', 'Tomáš Ladra',
    'Adam Hložek', 'Václav Černý', 'Mojmír Chytil',
    'Jan Kuchta',
]

czech_final = players[
    (players['Name'].isin(czech_squad_search)) &
    (players['Nation'] == 'Czech Republic')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
czech_final['team'] = 'Czech Republic'

print(f"إجمالي اللاعبين: {len(czech_final)}")
print(czech_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
            Name Position  OVR
   Patrik Schick       ST   85
 Ladislav Krejčí       CB   78
    Tomáš Souček      CDM   78
    Lukáš Provod      CAM   78
     Adam Hložek       ST   77
    Václav Černý       RM   77
      Pavel Šulc      CAM   77
     Tomáš Holeš       CB   76
  Michal Sadílek      CDM   76
     Pavel Bucha       CM   75
     Matěj Kovář       GK   75
 Martin Jedlička       GK   75
     Tomáš Chorý       ST   75
   Mojmír Chytil       ST   74
      Lukáš Červ      CDM   74
    Martin Vitík       CB   74
   David Jurásek       LB   73
 Vladimír Coufal       RB   73
      Jan Kuchta       ST   73
 Jaroslav Zelený       CB   72
     Tomáš Ladra      CAM   72
  Lukas Hornicek       GK   72
    Adam Karabec      CAM   71
    Robin Hranáč       CB   71
Štěpán Chaloupek       CB   70
  Denis Višinský       LW   68

In [30]:
#افريقيا

In [31]:
morocco_squad_search = [
    'Yassine Bounou', 'Alaa Bellaarouch', 'Issam El Maach',
    'Achraf Hakimi', 'Noussair Mazraoui', 'Nayef Aguerd',
    'Jawad El Yamiq', 'Adam Masina', 'Neil El Aynaoui',
    'Sofyan Amrabat', 'Azzedine Ounahi', 'Brahim',
    'Ismael Saibari', 'Oussama Targhalline', 'Bilal El Khannouss',
    'Abdessamad Ezzalzouli', 'Youssef En-Nesyri',
    'Ayoub El Kaabi', 'Chemsdine Talbi', 'Hamza Igamane',
    'Soufiane Rahimi', 'Ilias Akhomach',
    'Abderrazak Hamdallah', 'Amine Adli', 'Sofiane Diop',
    'Eliesse Ben Seghir'
]

morocco_data = players[
    (players['Name'].isin(morocco_squad_search)) &
    (players['Nation'] == 'Morocco')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
morocco_data['team'] = 'Morocco'

print(f"عدد اللاعبين: {len(morocco_data)}")
print(morocco_data[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string())

عدد اللاعبين: 26
                        Name Position  OVR
8              Achraf Hakimi       RB   89
228           Yassine Bounou       GK   82
265        Youssef En-Nesyri       ST   82
272                   Brahim       RM   82
356             Nayef Aguerd       CB   81
396        Noussair Mazraoui       RB   80
441           Ayoub El Kaabi       ST   80
535           Ismael Saibari      CAM   79
633     Abderrazak Hamdallah       ST   79
703           Sofyan Amrabat      CDM   78
754               Amine Adli       ST   78
788          Soufiane Rahimi       LM   78
1069   Abdessamad Ezzalzouli       LM   77
971          Neil El Aynaoui       CM   77
1270         Azzedine Ounahi       CM   76
1276            Sofiane Diop       LW   76
1322      Bilal El Khannouss      CAM   76
1324      Eliesse Ben Seghir       LM   76
2127             Adam Masina       CB   74
2143          Ilias Akhomach       RM   74
2414          Jawad El Yamiq       CB   73
2506         Chemsdine Talbi       RM   73
2525           Hamza Igamane       ST   73
2609     Oussama Targhalline       CM   73
5873        Alaa Bellaarouch       GK   68
11092         Issam El Maach       GK   63

In [32]:
# 1. اللاعبين الموجودين في FC 26
senegal_squad_search = [
    'Édouard Mendy', 'Mory Diaw',
    'Kalidou Koulibaly', 'Ismail Jakobs', 'Moussa Niakhaté', 'Antoine Mendy',
    'Idrissa Gueye', 'Pape Matar Sarr', 'Habib Diarra',
    'Lamine Camara', 'Pape Gueye',
    'Sadio Mané', 'Nicolas Jackson', 'Iliman Ndiaye', 'Krépin Diatta',
    'Ismaïla Sarr', 'Ousseynou Niang', 'Boulaye Dia', 'Bamba Dieng',
]

senegal_data = players[
    (players['Name'].isin(senegal_squad_search)) &
    (players['Nation'] == 'Senegal')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]

# احذف النسخة الغلطة من Idrissa Gueye
senegal_data = senegal_data[~((senegal_data['Name'] == 'Idrissa Gueye') & (senegal_data['Position'] == 'ST'))]
senegal_data['team'] = 'Senegal'

# 2. اللاعبين الناقصين - تقييم افتراضي (7 لاعب)
default_ovr = 57
missing_players = pd.DataFrame([
    {'Name': 'Yahia Fofana',     'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'Mamadou Sarr',     'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Abdoulaye Seck',   'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'M. Diouf',         'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Cherif Ndiaye',    'Position': 'ST', 'OVR': default_ovr},
    {'Name': 'Cheikhou Kouyate', 'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Pape Gueye II',    'Position': 'CM', 'OVR': default_ovr},
])
missing_players['Nation'] = 'Senegal'
missing_players['team'] = 'Senegal'

# 3. دمج الكل
senegal_final = pd.concat([senegal_data, missing_players], ignore_index=True)

print(f"إجمالي اللاعبين: {len(senegal_final)}")
print(senegal_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
             Name Position  OVR
       Sadio Mané       LM   83
Kalidou Koulibaly       CB   82
      Boulaye Dia       ST   80
    Édouard Mendy       GK   80
  Nicolas Jackson       ST   80
  Pape Matar Sarr       CM   79
     Ismaïla Sarr      CAM   79
    Iliman Ndiaye       LM   79
    Idrissa Gueye      CDM   79
       Pape Gueye       CM   78
    Lamine Camara       CM   77
     Habib Diarra       CM   77
  Moussa Niakhaté       CB   77
    Ismail Jakobs       LB   75
    Krépin Diatta       RM   74
      Bamba Dieng       ST   71
  Ousseynou Niang       LM   70
        Mory Diaw       GK   70
    Antoine Mendy       CB   70
     Yahia Fofana       GK   57
     Mamadou Sarr       CB   57
   Abdoulaye Seck       CB   57
         M. Diouf       CM   57
    Cherif Ndiaye       ST   57
 Cheikhou Kouyate       CM   57
    Pape Gueye II       CM   57

In [33]:
# 1. اللاعبين الموجودين في FC 26
egypt_squad_search = [
    'Mohamed Salah', 'Omar Marmoush', 'Mostafa Mohamed',
    'Mohamed Abdelmonem', 'Ramy Rabia',
]

egypt_data = players[
    (players['Name'].isin(egypt_squad_search)) &
    (players['Nation'] == 'Egypt')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
egypt_data['team'] = 'Egypt'

# 2. اللاعبين الناقصين - تقييم افتراضي (21 لاعب)
default_ovr = 57
missing_players = pd.DataFrame([
    {'Name': 'Mohamed El-Shennawy',  'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'Mahdi Suleiman',       'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'Mostafa Shobeir',      'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'M. Alaa',              'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'Yasser Ibrahim',       'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Mohamed Hany',         'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Hussam Abdel Salam',   'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Ahmed Abou El Fotouh', 'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Khalid Sobhi',         'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Tarek Alaa',           'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Emam Ashour',          'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Hamdi Fathi',          'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Ahmed Koka',           'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Mohanad Lashin',       'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Islam Issa',           'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Marwan Attia',         'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Ahmed Sayed Zizo',     'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Mahmoud Saber',        'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Mahmoud Hassan',       'Position': 'LM', 'OVR': default_ovr},
    {'Name': 'Nasser Mansi',         'Position': 'ST', 'OVR': default_ovr},
    {'Name': 'Hayssem Hassan',       'Position': 'ST', 'OVR': default_ovr},
    {'Name': 'Ibrahim Adel',         'Position': 'LW', 'OVR': default_ovr},
])
missing_players['Nation'] = 'Egypt'
missing_players['team'] = 'Egypt'

# 3. دمج الكل
egypt_final = pd.concat([egypt_data, missing_players], ignore_index=True)

print(f"إجمالي اللاعبين: {len(egypt_final)}")
print(egypt_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 27
                Name Position  OVR
       Mohamed Salah       RM   91
       Omar Marmoush       ST   84
  Mohamed Abdelmonem       CB   74
     Mostafa Mohamed       ST   73
          Ramy Rabia       CB   67
         Hamdi Fathi       CM   57
      Hayssem Hassan       ST   57
        Nasser Mansi       ST   57
      Mahmoud Hassan       LM   57
       Mahmoud Saber       CM   57
    Ahmed Sayed Zizo       CM   57
        Marwan Attia       CM   57
          Islam Issa       CM   57
      Mohanad Lashin       CM   57
          Ahmed Koka       CM   57
        Khalid Sobhi       CB   57
         Emam Ashour       CM   57
          Tarek Alaa       CB   57
Ahmed Abou El Fotouh       CB   57
  Hussam Abdel Salam       CB   57
        Mohamed Hany       CB   57
      Yasser Ibrahim       CB   57
             M. Alaa       GK   57
     Mostafa Shobeir       GK   57
      Mahdi Suleiman       GK   57
 Mohamed El-Shennawy       GK   57
        Ibrahim Adel       LW   57

In [34]:
egypt_final = egypt_final[egypt_final['Name'] != 'Hamdi Fathi']

print(f"إجمالي اللاعبين: {len(egypt_final)}")
print(egypt_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
                Name Position  OVR
       Mohamed Salah       RM   91
       Omar Marmoush       ST   84
  Mohamed Abdelmonem       CB   74
     Mostafa Mohamed       ST   73
          Ramy Rabia       CB   67
         Emam Ashour       CM   57
      Hayssem Hassan       ST   57
        Nasser Mansi       ST   57
      Mahmoud Hassan       LM   57
       Mahmoud Saber       CM   57
    Ahmed Sayed Zizo       CM   57
        Marwan Attia       CM   57
          Islam Issa       CM   57
      Mohanad Lashin       CM   57
          Ahmed Koka       CM   57
        Khalid Sobhi       CB   57
          Tarek Alaa       CB   57
Ahmed Abou El Fotouh       CB   57
  Hussam Abdel Salam       CB   57
        Mohamed Hany       CB   57
      Yasser Ibrahim       CB   57
             M. Alaa       GK   57
     Mostafa Shobeir       GK   57
      Mahdi Suleiman       GK   57
 Mohamed El-Shennawy       GK   57
        Ibrahim Adel       LW   57

In [35]:
# 1. اللاعبين الموجودين في FC 26
algeria_squad_search = [
    # Defenders
    'Aïssa Mandi', 'Mehdi Dorval', 'Ramy Bensebaini',
    'Rayan Aït-Nouri', 'Jaouen Hadjam',
    # Midfielders
    'Ramiz Zerrouki', 'Houssem Aouar', 'Ismaël Bennacer',
    'Hicham Boudaoui', 'Farès Chaïbi', 'Adem Zorgane',
    'Ibrahim Maza', 'Ilan Kebbal', 'Saïd Benrahma',
    'Himad Abdelli', 'Badredine Bouanani', 'Nabil Bentaleb',
    # Forwards
    'Riyad Mahrez', 'Mohamed Amoura', 'Amine Gouiri',
    'Anis Hadj-Moussa', 'Mounsef Bakrar', 'Rafik Belghali',
]

algeria_data = players[
    (players['Name'].isin(algeria_squad_search)) &
    (players['Nation'] == 'Algeria')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
algeria_data['team'] = 'Algeria'

# 2. حراس المرمى بتقييم افتراضي (مش موجودين في FC 26)
default_ovr = 57
missing_gk = pd.DataFrame([
    {'Name': 'Anthony Mandrea', 'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'O. Benbot',       'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'Luca Zidane',     'Position': 'GK', 'OVR': default_ovr},
])
missing_gk['Nation'] = 'Algeria'
missing_gk['team'] = 'Algeria'

# 3. دمج الكل
algeria_final = pd.concat([algeria_data, missing_gk], ignore_index=True)

print(f"إجمالي اللاعبين: {len(algeria_final)}")
print(algeria_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
              Name Position  OVR
      Riyad Mahrez       RM   84
   Rayan Aït-Nouri       LB   81
   Ismaël Bennacer      CDM   80
    Mohamed Amoura       ST   80
   Ramy Bensebaini       LB   79
      Amine Gouiri       ST   79
      Adem Zorgane      CDM   78
   Hicham Boudaoui       CM   77
     Houssem Aouar      CAM   77
    Nabil Bentaleb      CDM   77
     Saïd Benrahma       LW   77
     Himad Abdelli      CAM   76
  Anis Hadj-Moussa       RW   76
       Ilan Kebbal      CAM   75
       Aïssa Mandi       CB   75
Badredine Bouanani       RW   75
      Farès Chaïbi      CAM   74
    Ramiz Zerrouki      CDM   73
      Mehdi Dorval       LB   71
      Ibrahim Maza      CAM   71
     Jaouen Hadjam       LB   69
    Rafik Belghali       RB   66
    Mounsef Bakrar       ST   63
   Anthony Mandrea       GK   57
         O. Benbot       GK   57
       Luca Zidane       GK   57

In [36]:
tunisia_squad_search = [
    # Defenders
    'Ali Abdi', 'Montassar Talbi', 'Dylan Bronn',
    'Yan Valery', 'Mortadha Ben Ouanes', 'Mohamed Dräger',

    # Midfielders
    'Ellyes Skhiri', 'Hannibal', 'Elias Achouri',
    'Mohamed Belhadj Mahmoud', 'Saîf-Eddine Khaoui',
    'Sebastian Tounekti', 'Hamza Rafia', 'Anis Slimane',

    # Forwards
    'Ismaël Gharbi', 'Elias Saad', 'Amor Layouni',
    'Sayfallah Ltaief',
]

extra_search = [
    'Idris El Mizouni',
    'Alaa Ghram',
    'Amin Cherni',
    'Chiheb Labidi',
]

# لاعبي المنتخب من الداتا
tunisia_data = players[
    (players['Name'].isin(tunisia_squad_search + extra_search)) &
    (players['Nation'] == 'Tunisia')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]

tunisia_data['team'] = 'Tunisia'

# حراس مرمى غير موجودين في FC26
default_ovr = 57

missing_gk = pd.DataFrame([
    {'Name': 'Noureddine Farhat', 'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'Aymen Dahmen', 'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'Bechir Ben Said', 'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'Sabri Ben Hassan', 'Position': 'GK', 'OVR': default_ovr},
])

missing_gk['Nation'] = 'Tunisia'
missing_gk['team'] = 'Tunisia'

# دمج كل اللاعبين
tunisia_final = pd.concat([tunisia_data, missing_gk], ignore_index=True)

# طباعة النتيجة النهائية
print(f"إجمالي اللاعبين: {len(tunisia_final)}")

print(
    tunisia_final[['Name', 'Position', 'OVR']]
    .sort_values('OVR', ascending=False)
    .to_string(index=False)
)

إجمالي اللاعبين: 26
                   Name Position  OVR
          Ellyes Skhiri      CDM   80
               Ali Abdi       LB   76
               Hannibal       CM   74
          Ismaël Gharbi       LM   73
        Montassar Talbi       CB   73
           Amor Layouni       RW   72
          Elias Achouri       LM   72
             Elias Saad       LW   72
             Yan Valery       RB   71
     Saîf-Eddine Khaoui      CAM   70
    Mortadha Ben Ouanes       LB   69
       Sayfallah Ltaief       LM   69
     Sebastian Tounekti       LM   69
            Hamza Rafia       CM   68
            Dylan Bronn       CB   68
       Idris El Mizouni       CM   68
           Anis Slimane       CM   67
Mohamed Belhadj Mahmoud      CDM   67
             Alaa Ghram       CB   67
            Amin Cherni       LB   66
         Mohamed Dräger       RB   65
          Chiheb Labidi       CM   64
      Noureddine Farhat       GK   57
           Aymen Dahmen       GK   57
        Bechir Ben Said       GK   57
       Sabri Ben Hassan       GK   57

In [37]:
ghana_squad_search = [
    # Goalkeepers
    'Lawrence Ati Zigi', 'Joseph Anang',
    # Defenders
    'Jonas Adjetey', 'Gideon Mensah', 'Jerome Opoku',
    'Abdul Mumin', 'Mohammed Salisu', 'Rahman Baba',
    'Joseph Aidoo', 'Alidu Seidu', 'Tariq Lamptey',
    # Midfielders
    'Thomas Partey', 'Elisha Owusu', 'Mohammed Kudus',
    'Ibrahim Sulemana', 'Salis Abdul Samed', 'Kwasi Sibo',
    'Caleb Yirenkyi',
    # Forwards
    'Iñaki Williams', 'Antoine Semenyo', 'Jordan Ayew',
    'Kamaldeen Sulemana', 'Ransford-Yeboah Königsdörffer',
    'Christopher Bonsu Baah', 'Prince Kwabena Adu',
    'Brandon Thomas-Asante',
]

ghana_data = players[
    (players['Name'].isin(ghana_squad_search)) &
    (players['Nation'] == 'Ghana')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
ghana_data['team'] = 'Ghana'

print(f"إجمالي اللاعبين: {len(ghana_data)}")
print(ghana_data[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
                         Name Position  OVR
               Iñaki Williams       RM   83
                Thomas Partey      CDM   83
               Mohammed Kudus       RW   80
              Antoine Semenyo       RM   80
                  Abdul Mumin       CB   77
                  Rahman Baba       LB   76
              Mohammed Salisu       CB   76
                 Joseph Aidoo       CB   75
                Gideon Mensah       LB   74
                  Alidu Seidu       CB   74
            Salis Abdul Samed      CDM   73
                 Elisha Owusu      CDM   73
                Tariq Lamptey       RB   73
       Christopher Bonsu Baah       LM   73
            Lawrence Ati Zigi       GK   73
                  Jordan Ayew       RM   73
                 Jerome Opoku       CB   72
             Ibrahim Sulemana      CDM   71
Ransford-Yeboah Königsdörffer       ST   71
           Kamaldeen Sulemana       LM   71
           Prince Kwabena Adu       ST   70
                Jonas Adjetey       CB   70
        Brandon Thomas-Asante       ST   69
                   Kwasi Sibo      CDM   69
               Caleb Yirenkyi       CM   67
                 Joseph Anang       GK   67

In [38]:
ivory_squad_search = [
    # Goalkeepers
    'Yahia Fofana', 'Alban Lafont', 'Mohamed Koné',
    # Defenders
    'Ousmane Diomande', 'Ghislain Konan', 'Wilfried Singo',
    'Odilon Kossounou', 'Clément Akpa', 'Guéla Doué',
    'Emmanuel Agbadou', 'Evan Ndicka',
    # Midfielders
    'Seko Fofana', 'Franck Yannick Kessié', 'Bénie Traoré',
    'Ibrahim Sangaré', 'Christ Ravynel Inao Oulaï', 'Parfait Guiagon',
    # Forwards
    'Simon Adingra', 'Amad', 'Evann Guessand',
    'Hamed Junior Traoré', 'Bazoumana Touré', 'Nicolas Pépé',
    'Martial Godo', 'Willy Boly', 'Ismaila Soro',
]

ivory_data = players[
    (players['Name'].isin(ivory_squad_search)) &
    (players['Nation'] == 'Ivory Coast')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
ivory_data['team'] = 'Ivory Coast'

ivory_final = ivory_data.copy()

print(f"إجمالي اللاعبين: {len(ivory_final)}")
print(ivory_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
                     Name Position  OVR
              Evan Ndicka       CB   81
           Wilfried Singo       CB   80
             Nicolas Pépé       RM   80
         Odilon Kossounou       CB   80
         Ousmane Diomande       CB   80
    Franck Yannick Kessié      CDM   80
           Evann Guessand       RW   79
                     Amad      CAM   79
         Emmanuel Agbadou       CB   79
              Seko Fofana       CM   77
          Ibrahim Sangaré      CDM   77
      Hamed Junior Traoré       LM   77
               Guéla Doué       RB   77
            Simon Adingra       RM   76
             Yahia Fofana       GK   76
             Alban Lafont       GK   75
             Bénie Traoré       LM   75
             Clément Akpa       CB   74
               Willy Boly       CB   73
           Ghislain Konan       LB   72
          Parfait Guiagon       LM   72
             Ismaila Soro      CDM   71
          Bazoumana Touré       LM   70
             Mohamed Koné       GK   68
Christ Ravynel Inao Oulaï      CAM   64
             Martial Godo       RM   63

In [39]:
sa_squad_search = [
    # Defenders
    'Siyabonga Ngezana', 'Gift Links', 'Bongokuhle Hlongwane',
    'Ime Okon', 'Samukele Kabini', 'Olwethu Makhanya',
    # Midfielders
    'Yusuf Maart', 'Luke Le Roux', 'Sphephelo Sithole',
    'Kegs Chauke', 'Kobamelo Kodisang',
    # Forwards
    'Lyle Foster', 'Shandre Campbell', 'Antonio van Wyk',
]

sa_data = players[
    (players['Name'].isin(sa_squad_search)) &
    (players['Nation'] == 'South Africa')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
sa_data['team'] = 'South Africa'

# لاعبين بتقييم افتراضي
default_ovr = 57
missing_players = pd.DataFrame([
    {'Name': 'Ronwen Williams', 'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'S. Chaine',       'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'Ricardo Goss',    'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'T. Smith',        'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'K. Ndamane',      'Position': 'RB', 'OVR': default_ovr},
    {'Name': 'M. Mbokazi',      'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'S. Kabini',       'Position': 'LB', 'OVR': default_ovr},
    {'Name': 'N. Sibisi',       'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'T. Matuludi',     'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'T. Moremi',       'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'R. Mofokeng',     'Position': 'RM', 'OVR': default_ovr},
    {'Name': 'M. Shabalala',    'Position': 'ST', 'OVR': default_ovr},
])
missing_players['Nation'] = 'South Africa'
missing_players['team'] = 'South Africa'

sa_final = pd.concat([sa_data, missing_players], ignore_index=True)

print(f"إجمالي اللاعبين: {len(sa_final)}")
print(sa_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
                Name Position  OVR
   Siyabonga Ngezana       CB   73
          Gift Links       LB   72
         Lyle Foster       ST   72
Bongokuhle Hlongwane       RB   71
   Kobamelo Kodisang       RM   68
         Yusuf Maart       CM   67
            Ime Okon       CB   67
        Luke Le Roux       CM   66
    Shandre Campbell       LW   65
   Sphephelo Sithole      CDM   65
     Samukele Kabini       LB   63
         Kegs Chauke       CM   61
     Antonio van Wyk       LW   61
          M. Mbokazi       CB   57
         R. Mofokeng       RM   57
           T. Moremi       CM   57
         T. Matuludi       CM   57
           N. Sibisi       CB   57
           S. Kabini       LB   57
    Olwethu Makhanya       CB   57
          K. Ndamane       RB   57
            T. Smith       CB   57
        Ricardo Goss       GK   57
           S. Chaine       GK   57
     Ronwen Williams       GK   57
        M. Shabalala       ST   57

In [40]:
default_ovr = 57
cabo_players = pd.DataFrame([
    # Goalkeepers
    {'Name': 'Vozinha',                   'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'Marcio Rosa',               'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'Bruno Varela',              'Position': 'GK', 'OVR': default_ovr},
    # Defenders
    {'Name': 'W. Pina',                   'Position': 'RB', 'OVR': default_ovr},
    {'Name': 'Stopira',                   'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Deni',                      'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Roberto Lopez',             'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'K. Pires',                  'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'S. Lopes Cabral',           'Position': 'LB', 'OVR': default_ovr},
    {'Name': 'Steven Moriera',            'Position': 'RB', 'OVR': default_ovr},
    # Midfielders
    {'Name': 'A. Tavares',                'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Kevin Linhares',            'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'A. Santos',                 'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Joao Paulo',                'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Jovane Cabral',             'Position': 'LM', 'OVR': default_ovr},
    {'Name': 'Jamiro Monteiro',           'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'D. Duarte',                 'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Laroys Duarte',             'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Y. Semedo',                 'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Telmo Arcanjo',             'Position': 'RM', 'OVR': default_ovr},
    {'Name': 'J. Correia',                'Position': 'CM', 'OVR': default_ovr},
    # Forwards
    {'Name': 'Djallon Livramento',        'Position': 'ST', 'OVR': default_ovr},
    {'Name': 'Garry Rodrigues',           'Position': 'RW', 'OVR': default_ovr},
    {'Name': 'Ryan Mendes',               'Position': 'LW', 'OVR': default_ovr},
    {'Name': 'Helio Varela',              'Position': 'ST', 'OVR': default_ovr},
    {'Name': 'Nuno Da Costa',             'Position': 'ST', 'OVR': default_ovr},
])
cabo_players['Nation'] = 'Cape Verde'
cabo_players['team'] = 'Cape Verde'

cabo_final = cabo_players.copy()

print(f"إجمالي اللاعبين: {len(cabo_final)}")
print(cabo_final[['Name', 'Position', 'OVR']].to_string(index=False))

إجمالي اللاعبين: 26

              Name Position  OVR
           Vozinha       GK   57
       Marcio Rosa       GK   57
      Bruno Varela       GK   57
           W. Pina       RB   57
           Stopira       CB   57
              Deni       CB   57
     Roberto Lopez       CB   57
          K. Pires       CB   57
   S. Lopes Cabral       LB   57
    Steven Moriera       RB   57
        A. Tavares       CM   57
    Kevin Linhares       CM   57
         A. Santos       CM   57
        Joao Paulo       CM   57
     Jovane Cabral       LM   57
   Jamiro Monteiro       CM   57
         D. Duarte       CM   57
     Laroys Duarte       CM   57
         Y. Semedo       CM   57
     Telmo Arcanjo       RM   57
        J. Correia       CM   57
Djallon Livramento       ST   57
   Garry Rodrigues       RW   57
       Ryan Mendes       LW   57
      Helio Varela       ST   57
     Nuno Da Costa       ST   57

In [41]:
dr_congo_squad_search = [
    # Goalkeepers
    'Lionel Mpasi',
    # Defenders
    'Aaron Wan-Bissaka', 'Arthur Masuaku', 'Axel Tuanzebe',
    'Dylan Batubinsika', 'Steve Kapuadi', 'Marcel Tisserand',
    'Jeremy Ngakia', 'Joris Kayembe',
    # Midfielders
    'Noah Sadiki', "Ngal'ayel Mukau", 'Edo Kayembe',
    'Charles Pickel', 'Beni Baningime', 'Pelly-Ruddock Mpanzu',
    'William Balikwisha',
    # Forwards
    'Yoane Wissa', 'Simon Banza', 'Cédric Bakambu',
    'Silas', 'Samuel Essende', 'Afimico Pululu',
    'Nathanaël Mbuku', 'Meschack Elia',
]

dr_congo_data = players[
    (players['Name'].isin(dr_congo_squad_search)) &
    (players['Nation'] == 'DR Congo')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
dr_congo_data['team'] = 'DR Congo'

missing_gk = pd.DataFrame([
    {'Name': 'Joel Kiassumbua', 'Position': 'GK', 'OVR': 57, 'Nation': 'DR Congo', 'team': 'DR Congo'},
    {'Name': 'Joris Delle',     'Position': 'GK', 'OVR': 57, 'Nation': 'DR Congo', 'team': 'DR Congo'},
])

dr_congo_final = pd.concat([dr_congo_data, missing_gk], ignore_index=True)

print(f"إجمالي اللاعبين: {len(dr_congo_final)}")
print(dr_congo_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
                Name Position  OVR
         Yoane Wissa       ST   82
         Simon Banza       ST   81
   Aaron Wan-Bissaka       RB   80
      Cédric Bakambu       ST   77
      Arthur Masuaku       LB   75
         Noah Sadiki       CM   74
       Joris Kayembe       LB   74
               Silas       RM   74
     Ngal'ayel Mukau      CDM   74
      Samuel Essende       ST   74
       Axel Tuanzebe       RB   73
      Afimico Pululu       ST   72
   Dylan Batubinsika       CB   71
       Steve Kapuadi       CB   71
      Charles Pickel       CM   71
      Beni Baningime      CDM   71
         Edo Kayembe       CM   71
    Marcel Tisserand       CB   70
       Meschack Elia       ST   70
     Nathanaël Mbuku       RM   70
       Jeremy Ngakia       RB   69
Pelly-Ruddock Mpanzu       CM   68
  William Balikwisha      CAM   68
        Lionel Mpasi       GK   67
     Joel Kiassumbua       GK   57
         Joris Delle       GK   57

In [42]:
#امريكا الجنوبية

In [43]:
argentina_squad_search = [
    # Goalkeepers
    'Emiliano Martínez', 'Gerónimo Rulli', 'Juan Musso',
    # Defenders
    'Lucas Martínez Quarta', 'Nicolás Tagliafico', 'Marcos Senesi',
    'Marcos Acuña', 'Cristian Romero', 'Nicolás Otamendi',
    'Nahuel Molina', 'Valentín Barco',
    # Midfielders
    'Leandro Paredes', 'Rodrigo De Paul', 'Thiago Almada',
    'Exequiel Palacios', 'Alexis Mac Allister', 'Enzo Fernández',
    'Nico Paz', 'Máximo Perrone',
    # Forwards
    'Julián Alvarez', 'Lionel Messi', 'Nico Gonzalez',
    'Giuliano Simeone', 'Lautaro Martínez', 'Franco Mastantuono',
    'Gianluca Prestianni',
]

argentina_data = players[
    (players['Name'].isin(argentina_squad_search)) &
    (players['Nation'] == 'Argentina')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
argentina_data['team'] = 'Argentina'

print(f"إجمالي اللاعبين: {len(argentina_data)}")
print(argentina_data[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
                 Name Position  OVR
     Lautaro Martínez       ST   88
  Alexis Mac Allister       CM   87
       Julián Alvarez       ST   87
         Lionel Messi       RW   86
    Emiliano Martínez       GK   85
      Rodrigo De Paul       CM   84
       Enzo Fernández       CM   84
    Exequiel Palacios       CM   84
       Gerónimo Rulli       GK   82
     Nicolás Otamendi       CB   82
      Cristian Romero       CB   82
     Giuliano Simeone       RM   81
        Thiago Almada      CAM   79
             Nico Paz      CAM   79
           Juan Musso       GK   79
        Nahuel Molina       RB   79
         Marcos Acuña       LB   78
      Leandro Paredes       CM   78
   Nicolás Tagliafico       LB   78
        Nico Gonzalez       RM   78
        Marcos Senesi       CB   78
Lucas Martínez Quarta       CB   77
   Franco Mastantuono      CAM   77
       Valentín Barco       LB   75
       Máximo Perrone      CDM   73
  Gianluca Prestianni       RM   71

In [44]:
brazil_squad_search = [
    # Goalkeepers
    'Ederson', 'Bento',
    # Defenders
    'Bremer', 'Renan Lodi', 'Carlos Augusto',
    'Éder Militão', 'Ibañez',
    # Midfielders
    'Casemiro', 'Fabinho', 'Gabriel Sara',
    'Andrey Santos', 'Bruno Guimarães', 'Lucas Paquetá',
    # Forwards
    'Vini Jr.', 'Raphinha', 'Endrick',
    'Gabriel Martinelli', 'Matheus Cunha',
    'Luis Henrique', 'Igor Thiago',
    'Savinho', 'Rodrygo',
]

brazil_data = players[
    (players['Name'].isin(brazil_squad_search)) &
    (players['Nation'] == 'Brazil')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
brazil_data['team'] = 'Brazil'

specific_brazil = players[
    (players['Nation'] == 'Brazil') &
    (
        ((players['Name'] == 'Marquinhos') & (players['Position'] == 'CB')) |
        ((players['Name'] == 'Wesley')     & (players['Position'] == 'RB')) |
        ((players['Name'] == 'João Pedro') & (players['Position'] == 'ST')) |
        ((players['Name'] == 'Yan Couto')  & (players['Position'] == 'RB'))
    )
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
specific_brazil['team'] = 'Brazil'

brazil_final = pd.concat([brazil_data, specific_brazil], ignore_index=True)

print(f"إجمالي اللاعبين: {len(brazil_final)}")
print(brazil_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
              Name Position  OVR
          Raphinha       LM   89
          Vini Jr.       LW   89
        Marquinhos       CB   87
   Bruno Guimarães       CM   86
           Ederson       GK   85
           Rodrygo       RW   85
            Bremer       CB   85
      Éder Militão       CB   84
     Matheus Cunha      CAM   83
           Fabinho      CDM   82
           Savinho       RW   82
            Ibañez       CB   82
    Carlos Augusto       LB   81
Gabriel Martinelli       LW   81
             Bento       GK   80
          Casemiro      CDM   80
      Gabriel Sara       CM   80
     Andrey Santos       CM   80
     Lucas Paquetá       CM   80
        João Pedro       ST   79
     Luis Henrique       RM   78
        Renan Lodi       LB   78
           Endrick       ST   77
            Wesley       RB   77
         Yan Couto       RB   77
       Igor Thiago       ST   75

In [45]:
colombia_squad_search = [
    # Goalkeepers
    'Aldair Quintana', 'Álvaro Montero', 'Devis Vásquez',
    # Defenders
    'Daniel Muñoz', 'Jhon Lucumí', 'Johan Mojica',
    'Deiver Machado', 'Davinson Sánchez', 'Yerson Mosquera',
    'Juan David Cabal',
    # Midfielders
    'Kevin Castaño', 'Richard Ríos', 'Jefferson Lerma',
    'Juan Fernando Quintero', 'Jhon Arias', 'Jaminton Campaz',
    'Gustavo Puerta', 'Mateus Uribe', 'Juan Cuadrado',
    'Nelson Deossa', 'Yáser Asprilla',
    # Forwards
    'Luis Díaz', 'Jhon Durán', 'Luis Javier Suárez',
    'Rafael Carrascal', 'Cucho',
]

colombia_final = players[
    (players['Name'].isin(colombia_squad_search)) &
    (players['Nation'] == 'Colombia')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
colombia_final['team'] = 'Colombia'

print(f"إجمالي اللاعبين: {len(colombia_final)}")
print(colombia_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
                  Name Position  OVR
             Luis Díaz       LM   85
      Davinson Sánchez       CB   82
          Daniel Muñoz       RB   81
          Richard Ríos       CM   79
            Jhon Durán       ST   79
          Johan Mojica       LB   78
                 Cucho       ST   78
            Jhon Arias       RW   78
         Kevin Castaño       CM   77
       Jefferson Lerma      CDM   77
    Luis Javier Suárez       ST   77
Juan Fernando Quintero      CAM   77
       Jaminton Campaz       LM   76
           Jhon Lucumí       CB   76
          Mateus Uribe       CM   76
         Juan Cuadrado       RM   76
        Deiver Machado       LB   76
         Nelson Deossa       CM   75
        Álvaro Montero       GK   75
        Yáser Asprilla       RM   75
      Juan David Cabal       LB   74
         Devis Vásquez       GK   72
       Aldair Quintana       GK   72
       Yerson Mosquera       CB   72
      Rafael Carrascal       CM   70
        Gustavo Puerta       CM   68

In [46]:
ecuador_squad_search = [
    # Goalkeepers
    'Hernán Galíndez', 'Gonzalo Valle',
    # Defenders
    'Willian Pacho', 'Piero Hincapié', 'Pervis Estupiñán',
    'Ángelo Preciado', 'Joel Ordoñez', 'Yaimar Medina',
    'Jhoanner Chávez',
    # Midfielders
    'Moisés Caicedo', 'Kendry Páez', 'Carlos Gruezo',
    'José Cifuentes', 'Janner Corozo', 'John Yeboah',
    'Alan Minda', 'Patrik Mercado', 'Denil Castillo',
    'Nilson Angulo', 'Jeremy Sarmiento', 'Junior Sornoza',
    # Forwards
    'Kevin Rodríguez', 'Leonardo Campana', 'Jordy Caicedo',
    'John Mercado', 'Anthony Valencia',
]

ecuador_final = players[
    (players['Name'].isin(ecuador_squad_search)) &
    (players['Nation'] == 'Ecuador')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
ecuador_final['team'] = 'Ecuador'

print(f"إجمالي اللاعبين: {len(ecuador_final)}")
print(ecuador_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
            Name Position  OVR
  Moisés Caicedo      CDM   87
   Willian Pacho       CB   86
  Piero Hincapié       CB   83
Pervis Estupiñán       LB   79
 Ángelo Preciado       RM   75
    Joel Ordoñez       CB   75
 Hernán Galíndez       GK   74
     Kendry Páez      CAM   73
  José Cifuentes       CM   72
 Jhoanner Chávez       LB   72
   Carlos Gruezo      CDM   72
  Junior Sornoza      CAM   72
Leonardo Campana       ST   72
   Janner Corozo       LM   71
   Yaimar Medina       LB   70
      Alan Minda       RM   70
     John Yeboah       ST   70
Jeremy Sarmiento       LM   70
    John Mercado       LW   70
   Gonzalo Valle       GK   70
  Patrik Mercado       CM   68
Anthony Valencia       RM   67
  Denil Castillo       CM   67
 Kevin Rodríguez       ST   67
   Nilson Angulo       LM   67
   Jordy Caicedo       ST   66

In [47]:
paraguay_squad_search = [
    # Goalkeepers
    'Roberto Fernández', 'Orlando Gill',
    # Defenders
    'Omar Alderete', 'Gustavo Velázquez', 'Saúl Salcedo',
    'Williams Riveros', 'José Canale', 'Juan Escobar',
    # Midfielders
    'Kaku', 'Miguel Almirón', 'Diego Gómez',
    'Matías Galarza', 'Richard Sánchez', 'Andrés Cubas',
    'Braian Ojeda', 'Gastón Giménez', 'Rodney Redes',
    'Cecilio Domínguez',
    # Forwards
    'Antonio Sanabria', 'Julio César Enciso', 'Gabriel Ávalos',
    'Alex Arce', 'Carlos González', 'Derlis González',
    'Lorenzo Melgarejo', 'Matías Rojas',
]

paraguay_final = players[
    (players['Name'].isin(paraguay_squad_search)) &
    (players['Nation'] == 'Paraguay')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
paraguay_final['team'] = 'Paraguay'

print(f"إجمالي اللاعبين: {len(paraguay_final)}")
print(paraguay_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
              Name Position  OVR
              Kaku      CAM   79
     Omar Alderete       CB   78
    Miguel Almirón       RW   76
  Antonio Sanabria       ST   76
   Richard Sánchez       CM   75
    Gabriel Ávalos       ST   75
         Alex Arce       ST   75
 Lorenzo Melgarejo       LW   74
      Matías Rojas       RW   74
      Andrés Cubas      CDM   74
 Gustavo Velázquez       CB   73
   Carlos González       ST   73
Julio César Enciso      CAM   73
    Matías Galarza       CM   73
 Cecilio Domínguez       LM   73
   Derlis González       ST   73
       Diego Gómez       CM   73
  Williams Riveros       CB   72
      Saúl Salcedo       CB   71
    Gastón Giménez      CDM   70
      Braian Ojeda      CDM   70
      Rodney Redes       RW   70
 Roberto Fernández       GK   70
      Juan Escobar       RB   69
       José Canale       CB   69
      Orlando Gill       GK   62

In [48]:
uruguay_squad_search = [
    # Goalkeepers
    'Sergio Rochet', 'Sebastián Sosa', 'Guillermo De Amores',
    # Defenders
    'Ronald Araújo', 'José María Giménez', 'Mathías Olivera',
    'Nahitan Nández', 'Santiago Bueno', 'Matías Viña',
    'Joaquín Piquerez', 'Fabricio Díaz',
    # Midfielders
    'Federico Valverde', 'Rodrigo Bentancur', 'Manuel Ugarte',
    'Nicolás De La Cruz', 'Matías Vecino', 'Lucas Torreira',
    'Franco Trinidad', 'Facundo Pellistri',
    # Forwards
    'Darwin Núñez', 'Luis Suárez', 'Edinson Cavani',
    'Maximiliano Araújo', 'Brian Rodríguez', 'Agustín Canobbio',
    'Santiago Rodríguez',
]

uruguay_final = players[
    (players['Name'].isin(uruguay_squad_search)) &
    (players['Nation'] == 'Uruguay')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
uruguay_final['team'] = 'Uruguay'

missing_uruguay = pd.DataFrame([
    # Goalkeepers
    {'Name': 'Sergio Rochet',       'Position': 'GK', 'OVR': 75},
    {'Name': 'Sebastián Sosa',      'Position': 'GK', 'OVR': 70},
    {'Name': 'Guillermo De Amores', 'Position': 'GK', 'OVR': 68},
    # Defenders
    {'Name': 'Ronald Araújo',       'Position': 'CB', 'OVR': 85},
    {'Name': 'Matías Viña',         'Position': 'LB', 'OVR': 74},
    {'Name': 'Joaquín Piquerez',    'Position': 'LB', 'OVR': 74},
    {'Name': 'Fabricio Díaz',       'Position': 'RB', 'OVR': 70},
    # Midfielders
    {'Name': 'Nicolás De La Cruz',  'Position': 'CM', 'OVR': 80},
    {'Name': 'Franco Trinidad',     'Position': 'CM', 'OVR': 68},
    # Forwards
    {'Name': 'Brian Rodríguez',     'Position': 'LW', 'OVR': 72},
    {'Name': 'Agustín Canobbio',    'Position': 'LW', 'OVR': 71},
    {'Name': 'Santiago Rodríguez',  'Position': 'CM', 'OVR': 72},
])
missing_uruguay['Nation'] = 'Uruguay'
missing_uruguay['team'] = 'Uruguay'

uruguay_final = pd.concat([uruguay_final, missing_uruguay], ignore_index=True)

print(f"إجمالي اللاعبين: {len(uruguay_final)}")
print(uruguay_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
               Name Position  OVR
  Federico Valverde       CM   89
      Ronald Araújo       CB   85
 José María Giménez       CB   83
     Lucas Torreira      CDM   83
  Rodrigo Bentancur      CDM   80
 Nicolás De La Cruz       CM   80
       Darwin Núñez       ST   79
      Manuel Ugarte      CDM   79
        Luis Suárez       ST   79
    Mathías Olivera       LB   78
 Maximiliano Araújo       LM   77
      Matías Vecino       CM   77
     Nahitan Nández       CM   76
     Edinson Cavani       ST   76
     Santiago Bueno       CB   76
      Sergio Rochet       GK   75
        Matías Viña       LB   74
   Joaquín Piquerez       LB   74
  Facundo Pellistri       RM   73
    Brian Rodríguez       LW   72
 Santiago Rodríguez       CM   72
   Agustín Canobbio       LW   71
      Fabricio Díaz       RB   70
     Sebastián Sosa       GK   70
Guillermo De Amores       GK   68
    Franco Trinidad       CM   68

In [49]:
uruguay_squad_search = [
    # Goalkeepers
    'Sergio Rochet', 'Santiago Mele',
    # Defenders
    'José María Giménez', 'Sebastián Cáceres',
    'Santiago Bueno', 'Guillermo Varela', 'Mathías Olivera',
    'Matías Viña', 'Joaquín Piquerez',
    # Midfielders
    'Manuel Ugarte', 'Nicolás De La Cruz', 'Federico Valverde',
    'Facundo Pellistri', 'Nicolás Fonseca',
    'Jorge De Arrascaeta', 'Rodrigo Bentancur', 'Lucas Torreira',
    # Forwards
    'Darwin Núñez', 'Agustín Canobbio', 'Brian Rodríguez',
    'Maximiliano Araújo', 'Facundo Torres', 'Agustín Álvarez',
    'Rodrigo Aguirre',
]

uruguay_final = players[
    (players['Name'].isin(uruguay_squad_search)) &
    (players['Nation'] == 'Uruguay')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
uruguay_final['team'] = 'Uruguay'

missing_uruguay = pd.DataFrame([
    {'Name': 'Sergio Rochet',       'Position': 'GK',  'OVR': 75},
    {'Name': 'Santiago Mele',       'Position': 'GK',  'OVR': 70},
    {'Name': 'Gastón Álvarez',      'Position': 'GK',  'OVR': 68},
    {'Name': 'Ronald Araújo',       'Position': 'CB',  'OVR': 85},  # مش في الداتا
    {'Name': 'Sebastián Cáceres',   'Position': 'CB',  'OVR': 72},
    {'Name': 'Guillermo Varela',    'Position': 'RB',  'OVR': 70},
    {'Name': 'Matías Viña',         'Position': 'LB',  'OVR': 74},
    {'Name': 'Nicolás Fonseca',     'Position': 'CM',  'OVR': 68},
    {'Name': 'Jorge De Arrascaeta', 'Position': 'CAM', 'OVR': 80},
    {'Name': 'Facundo Torres',      'Position': 'LW',  'OVR': 72},
    {'Name': 'Agustín Álvarez',     'Position': 'ST',  'OVR': 70},
    {'Name': 'Rodrigo Aguirre',     'Position': 'ST',  'OVR': 68},
    {'Name': 'Nicolás De La Cruz',  'Position': 'CM',  'OVR': 80},
    {'Name': 'Agustín Canobbio',    'Position': 'LW',  'OVR': 71},
    {'Name': 'Brian Rodríguez',     'Position': 'LW',  'OVR': 72},
    {'Name': 'Joaquín Piquerez',    'Position': 'LB',  'OVR': 74},
])
missing_uruguay['Nation'] = 'Uruguay'
missing_uruguay['team'] = 'Uruguay'

uruguay_final = pd.concat([uruguay_final, missing_uruguay], ignore_index=True)
uruguay_final = uruguay_final.drop_duplicates(subset='Name', keep='first')

print(f"إجمالي اللاعبين: {len(uruguay_final)}")
print(uruguay_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
               Name Position  OVR
  Federico Valverde       CM   89
      Ronald Araújo       CB   85
 José María Giménez       CB   83
     Lucas Torreira      CDM   83
  Rodrigo Bentancur      CDM   80
 Nicolás De La Cruz       CM   80
Jorge De Arrascaeta      CAM   80
       Darwin Núñez       ST   79
      Manuel Ugarte      CDM   79
    Mathías Olivera       LB   78
 Maximiliano Araújo       LM   77
     Santiago Bueno       CB   76
      Sergio Rochet       GK   75
        Matías Viña       LB   74
   Joaquín Piquerez       LB   74
  Facundo Pellistri       RM   73
  Sebastián Cáceres       CB   72
    Agustín Álvarez       ST   72
     Facundo Torres       LW   72
    Brian Rodríguez       LW   72
   Agustín Canobbio       LW   71
   Guillermo Varela       RB   70
      Santiago Mele       GK   70
    Nicolás Fonseca       CM   68
    Rodrigo Aguirre       ST   68
     Gastón Álvarez       GK   68

In [50]:
#اسيا

In [51]:
japan_squad_search = [
    # Goalkeepers
    'Zion Suzuki', 'Yohei Takaoka',
    # Defenders
    'Yukinari Sugawara', 'Shogo Taniguchi', 'Hiroki Ito',
    'Takuma Ominami', 'Tsuyoshi Watanabe', 'Daiki Hashioka',
    'Ko Itakura', 'Koki Machida',
    # Midfielders
    'Ayumu Seko', 'Kaoru Mitoma', 'Ritsu Doan',
    'Daichi Kamada', 'Ao Tanaka', 'Joel Chima Fujita',
    'Kaishū Sano', 'Wataru Endo', 'Kodai Sano',
    # Forwards
    'Daizen Maeda', 'Keito Nakamura', 'Junya Ito',
    'Ayase Ueda', 'Koki Ogawa', 'Shuto Machino',
    'Yuito Suzuki',
]

japan_final = players[
    (players['Name'].isin(japan_squad_search)) &
    (players['Nation'] == 'Japan')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
japan_final['team'] = 'Japan'

print(f"إجمالي اللاعبين: {len(japan_final)}")
print(japan_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26

             Name Position  OVR
     Kaoru Mitoma       LM   82
       Ritsu Doan       RM   82
     Daizen Maeda       LW   79
      Kaishū Sano      CDM   79
      Wataru Endo      CDM   79
       Hiroki Ito       CB   78
        Junya Ito       RM   77
    Daichi Kamada       CM   77
       Ko Itakura       CB   77
        Ao Tanaka      CDM   76
   Keito Nakamura       LM   76
     Koki Machida       CB   76
Tsuyoshi Watanabe       CB   75
    Shuto Machino       ST   75
      Zion Suzuki       GK   74
Yukinari Sugawara       RB   74
       Ayase Ueda       ST   74
    Yohei Takaoka       GK   72
     Yuito Suzuki      CAM   71
   Daiki Hashioka       RB   70
       Kodai Sano       CM   70
   Takuma Ominami       CB   70
Joel Chima Fujita       CM   69
  Shogo Taniguchi       CB   69
       Ayumu Seko       CB   68
       Koki Ogawa       ST   68

In [52]:
korea_squad_search = [
    # Goalkeepers
    'Jo Hyeon Woo', 'Song Bum Keun',
    # Defenders
    'Kim Min Jae', 'Lee Tae Seok', 'Park Jin Seob',
    'Kim Jin Su', 'Lee Han Beom', 'Yang Hyun Jun',
    # Midfielders
    'Hwang In Beom', 'Lee Jae Sung', 'Lee Kang In',
    'Jeong Woo Yeong', 'Paik Seung Ho', 'Hong Hyeon Seok',
    'Jens Castrop', 'Bae Jun Ho', 'Kwon Hyeok Kyu',
    # Forwards
    'Heung Min Son', 'Hwang Hee Chan', 'Oh Hyeon Gyu',
    'Cho Gue Sung', 'Eom Ji Sung', 'Moon Seon Min',
    'Yang Min Hyeok', 'Kim Moon Hwan',
]

korea_final = players[
    (players['Name'].isin(korea_squad_search)) &
    (players['Nation'] == 'South Korea')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
korea_final['team'] = 'South Korea'

print(f"إجمالي اللاعبين: {len(korea_final)}")
print(korea_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
           Name Position  OVR
  Heung Min Son       LW   85
    Kim Min Jae       CB   82
    Lee Kang In       RW   79
   Lee Jae Sung      CAM   77
  Hwang In Beom       CM   77
   Jo Hyeon Woo       GK   75
 Hwang Hee Chan       ST   75
  Song Bum Keun       GK   74
Hong Hyeon Seok      CAM   73
Jeong Woo Yeong      CAM   73
  Paik Seung Ho      CDM   72
     Bae Jun Ho       LM   71
    Eom Ji Sung       LM   71
   Oh Hyeon Gyu       ST   71
  Yang Hyun Jun       RW   71
  Park Jin Seob       CB   71
   Jens Castrop       CM   70
   Cho Gue Sung       ST   70
 Yang Min Hyeok       RM   70
  Kim Moon Hwan       RB   69
     Kim Jin Su       LB   69
  Moon Seon Min       LM   69
   Lee Tae Seok       LB   69
   Lee Han Beom       CB   69
 Kwon Hyeok Kyu      CDM   67
    Kim Min Jae      CDM   48

In [53]:
australia_squad_search = [
    # Goalkeepers
    'Paul Izzo', 'Patrick Beach',
    # Defenders
    'Cameron Burgess', 'Alessandro Circati', 'Fran Karačić',
    'Aziz Behich', 'Connor Metcalfe', 'Jordan Bos',
    'Kai Trewin', 'Jacob Italiano', 'Harry Souttar',
    'Kye Rowles',
    # Midfielders
    'Ajdin Hrustić', 'Aiden O\'Neill', 'Riley McGree',
    'Patrick Yazbek', 'Alex Robertson', 'Jackson Irvine',
    'Massimo Luongo', 'Cameron Devlin', 'Mathew Leckie',
    'Craig Goodwin',
    # Forwards
    'Martin Boyle', 'Nestory Irankunda', 'Nishan Velupillay',
    'Awer Mabil',
]

australia_final = players[
    (players['Name'].isin(australia_squad_search)) &
    (players['Nation'] == 'Australia')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
australia_final['team'] = 'Australia'

print(f"إجمالي اللاعبين: {len(australia_final)}")
print(australia_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
              Name Position  OVR
    Jackson Irvine       CM   75
   Cameron Burgess       CB   73
     Harry Souttar       CB   73
     Craig Goodwin       LM   73
      Riley McGree       LM   72
    Massimo Luongo      CDM   72
      Martin Boyle       ST   71
    Cameron Devlin      CDM   71
Alessandro Circati       CB   71
        Kye Rowles       CB   71
     Mathew Leckie       CM   70
     Aiden O'Neill      CDM   70
         Paul Izzo       GK   70
        Kai Trewin       CB   69
        Jordan Bos       LB   69
   Connor Metcalfe       CM   69
    Alex Robertson      CAM   68
      Fran Karačić       RB   68
 Nestory Irankunda       RM   67
       Aziz Behich       LB   67
     Ajdin Hrustić       CM   67
        Awer Mabil       RM   67
    Patrick Yazbek      CDM   66
 Nishan Velupillay       LM   65
     Patrick Beach       GK   65
    Jacob Italiano       LB   63

In [54]:
iran_squad_search = [
    'Mehdi Taremi', 'Allahyar Sayyadmanesh',
    'Ali Gholizadeh', 'Amir Abedzadeh',
    'Majid Hosseini', 'Ali Karimi',
]

iran_data = players[
    (players['Name'].isin(iran_squad_search)) &
    (players['Nation'] == 'IR Iran')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
iran_data['team'] = 'IR Iran'

default_ovr = 57
missing_iran = pd.DataFrame([
    {'Name': 'Alireza Beiranvand',        'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'Payam Niazmand',            'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'Shoja Khalilzadeh',         'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Ali Nemati',                'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Aria Yousefi',              'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'M. Zare Mohazabieh',        'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Mohammad Amin Hazbavi',     'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Omid Noorafkan',            'Position': 'LB', 'OVR': default_ovr},
    {'Name': 'Ramin Rezaeian',            'Position': 'RB', 'OVR': default_ovr},
    {'Name': 'Saeid Ezatolahi',           'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Alireza Jahanbakhsh',       'Position': 'LM', 'OVR': default_ovr},
    {'Name': 'Mohammad Mohebi',           'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Saman Ghoddos',            'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Mohammad Ghorbani',         'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Mohammad Hosseininejad',    'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Danial Esmaeilifar',        'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Mohammad Khodabandehloo',   'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Amirhossein Hosseininejad', 'Position': 'ST', 'OVR': default_ovr},
    {'Name': 'Ali Alipour',               'Position': 'ST', 'OVR': default_ovr},
    {'Name': 'K. Taheri',                 'Position': 'ST', 'OVR': default_ovr},
])
missing_iran['Nation'] = 'IR Iran'
missing_iran['team'] = 'IR Iran'

iran_final = pd.concat([iran_data, missing_iran], ignore_index=True)
iran_final = iran_final.drop_duplicates(subset='Name', keep='first')

print(f"إجمالي اللاعبين: {len(iran_final)}")
print(iran_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
                     Name Position  OVR
             Mehdi Taremi       ST   78
    Allahyar Sayyadmanesh       LM   74
           Ali Gholizadeh       RM   71
           Amir Abedzadeh       GK   68
           Majid Hosseini       CB   68
               Ali Karimi      CDM   67
      Alireza Jahanbakhsh       LM   57
              Ali Alipour       ST   57
Amirhossein Hosseininejad       ST   57
  Mohammad Khodabandehloo       CM   57
       Danial Esmaeilifar       CM   57
   Mohammad Hosseininejad       CM   57
        Mohammad Ghorbani       CM   57
            Saman Ghoddos       CM   57
          Mohammad Mohebi       CM   57
           Omid Noorafkan       LB   57
          Saeid Ezatolahi       CM   57
           Ramin Rezaeian       RB   57
    Mohammad Amin Hazbavi       CB   57
       M. Zare Mohazabieh       CB   57
             Aria Yousefi       CB   57
               Ali Nemati       CB   57
        Shoja Khalilzadeh       CB   57
           Payam Niazmand       GK   57
       Alireza Beiranvand       GK   57
                K. Taheri       ST   57

In [55]:
jordan_squad_search = [
    'Musa Al Tamari', 'Yazan Al Arab',
]

jordan_data = players[
    (players['Name'].isin(jordan_squad_search)) &
    (players['Nation'] == 'Jordan')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
jordan_data['team'] = 'Jordan'

default_ovr = 57
missing_jordan = pd.DataFrame([
    {'Name': 'Yazeed Abu Laila',    'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'M. Shalabiya',        'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'Nour Bani Atiyeh',    'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'M. Hasheesh',         'Position': 'RB', 'OVR': default_ovr},
    {'Name': 'A. Nasib',            'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Salim Obeid',         'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Hadi Al Hawrani',     'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Youssef Abu Jazar',   'Position': 'LB', 'OVR': default_ovr},
    {'Name': 'Mohammad Abu Al Nadi','Position': 'CB', 'OVR': default_ovr},
    {'Name': 'I. Smeeri',           'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'A. Hajabi',           'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Nour Al Rawabdeh',    'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Mahmoud Mardawi',     'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'I. Sami',             'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'A. Al-Salman',        'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Mohannad Abu Taha',   'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Nizar Al Rashdan',    'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Adham Al Qurashi',    'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Amer Jaamous',        'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Mohammad Abu Zreiq',  'Position': 'ST', 'OVR': default_ovr},
    {'Name': 'Ali Olwan',           'Position': 'ST', 'OVR': default_ovr},
    {'Name': 'Ibrahim Sabra',       'Position': 'ST', 'OVR': default_ovr},
    {'Name': 'Saad Al Rousan',      'Position': 'RB', 'OVR': default_ovr},
    {'Name': 'Rizq Bani Hani',      'Position': 'ST', 'OVR': default_ovr},
])
missing_jordan['Nation'] = 'Jordan'
missing_jordan['team'] = 'Jordan'

jordan_final = pd.concat([jordan_data, missing_jordan], ignore_index=True)

print(f"إجمالي اللاعبين: {len(jordan_final)}")
print(jordan_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
                Name Position  OVR
      Musa Al Tamari       RM   75
       Yazan Al Arab       CB   75
      Saad Al Rousan       RB   57
       Ibrahim Sabra       ST   57
           Ali Olwan       ST   57
  Mohammad Abu Zreiq       ST   57
        Amer Jaamous       CM   57
    Adham Al Qurashi       CM   57
    Nizar Al Rashdan       CM   57
   Mohannad Abu Taha       CM   57
        A. Al-Salman       CM   57
             I. Sami       CM   57
     Mahmoud Mardawi       CM   57
    Nour Al Rawabdeh       CM   57
           A. Hajabi       CB   57
           I. Smeeri       CB   57
Mohammad Abu Al Nadi       CB   57
   Youssef Abu Jazar       LB   57
     Hadi Al Hawrani       CB   57
         Salim Obeid       CB   57
            A. Nasib       CB   57
         M. Hasheesh       RB   57
    Nour Bani Atiyeh       GK   57
        M. Shalabiya       GK   57
    Yazeed Abu Laila       GK   57
      Rizq Bani Hani       ST   57

In [56]:
iraq_squad_search = [
    'Ali Adnan', 'Ibrahim Bayesh', 'Mohanad Jeahze',
    'Merchas Doski', 'Zidane Iqbal', 'Aimar Sher',
    'Kevin Yakob', 'Marko Farji', 'Montader Madjed',
    'Ali Al Hamadi', 'Amir Al-Ammari', 'Danilo Al Saed',
    'Ali Jasim', 'Mohamed Al-Taay', 'Amin Al-Hamawi',
]

iraq_data = players[
    (players['Name'].isin(iraq_squad_search)) &
    (players['Nation'] == 'Iraq')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
iraq_data['team'] = 'Iraq'

default_ovr = 57
missing_iraq = pd.DataFrame([
    {'Name': 'Fahad Talib',         'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'K. Al-Rekabe',        'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'Ahmed Basel',         'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'Rebin Sulaka',        'Position': 'RB', 'OVR': default_ovr},
    {'Name': 'Hussein Ali',         'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Zaid Tahseen',        'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Akam Hashim',         'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Manaf Younis',        'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Youssef Amyn',        'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Aymen Hussein',       'Position': 'ST', 'OVR': default_ovr},
    {'Name': 'Mohanad Ali Kadhim',  'Position': 'ST', 'OVR': default_ovr},
])
missing_iraq['Nation'] = 'Iraq'
missing_iraq['team'] = 'Iraq'

iraq_final = pd.concat([iraq_data, missing_iraq], ignore_index=True)

print(f"إجمالي اللاعبين: {len(iraq_final)}")
print(iraq_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
              Name Position  OVR
         Ali Adnan       LB   72
    Ibrahim Bayesh       LM   68
    Mohanad Jeahze       LB   68
     Merchas Doski       LB   68
      Zidane Iqbal      CDM   68
        Aimar Sher      CDM   67
       Kevin Yakob       CM   66
       Marko Farji       LW   66
   Montader Madjed       RM   66
     Ali Al Hamadi       ST   66
    Amir Al-Ammari       CM   65
    Danilo Al Saed       LM   65
         Ali Jasim       LM   62
   Mohamed Al-Taay      CDM   61
    Amin Al-Hamawi       ST   60
       Fahad Talib       GK   57
      K. Al-Rekabe       GK   57
       Ahmed Basel       GK   57
      Rebin Sulaka       RB   57
       Hussein Ali       CB   57
      Zaid Tahseen       CB   57
       Akam Hashim       CB   57
      Manaf Younis       CB   57
      Youssef Amyn       CM   57
     Aymen Hussein       ST   57
Mohanad Ali Kadhim       ST   57

In [57]:
uzbekistan_squad_search = [
    'Abdukodir Khusanov', 'Eldor Shomurodov',
    'Khusniddin Alikulov', 'Mukhammadali Urinboev',
]

uzbekistan_data = players[
    (players['Name'].isin(uzbekistan_squad_search)) &
    (players['Nation'] == 'Uzbekistan')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
uzbekistan_data['team'] = 'Uzbekistan'

default_ovr = 57
missing_uzbekistan = pd.DataFrame([
    {'Name': 'Abdulvohid Nematov',      'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'Utkir Yusupov',           'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'Bunyodbek Ergashev',      'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'K. Alidzhanov',           'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Farrukh Sayfiev',         'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Rustamjon Ashurmatov',    'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Jurab Jaloliddinov',      'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'S. Nasrulloev',           'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Oybek Ashmorodov',        'Position': 'LB', 'OVR': default_ovr},
    {'Name': 'Abdulloh Abdulloyev',     'Position': 'RB', 'OVR': default_ovr},
    {'Name': 'Zafarmurod Abdurakhmatov','Position': 'CB', 'OVR': default_ovr},
    {'Name': 'I. Tuhtahujaev',          'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Ibrohimhalil Yuldoshev',  'Position': 'RB', 'OVR': default_ovr},
    {'Name': 'Azizbek Jangiev',         'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Akmal Mirzayev',          'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Khozhimat Erkinov',       'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'A. Fayzullayev',          'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Otabek Shukurov',         'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Jamshid Iskandarov',      'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'O. Khamrobekov',          'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Jaloliddin Masharipov',   'Position': 'CAM', 'OVR': default_ovr},
    {'Name': 'Abdurauf Buriev',         'Position': 'CM', 'OVR': default_ovr},
])
missing_uzbekistan['Nation'] = 'Uzbekistan'
missing_uzbekistan['team'] = 'Uzbekistan'

uzbekistan_final = pd.concat([uzbekistan_data, missing_uzbekistan], ignore_index=True)

print(f"إجمالي اللاعبين: {len(uzbekistan_final)}")
print(uzbekistan_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
                    Name Position  OVR
      Abdukodir Khusanov       CB   77
        Eldor Shomurodov       ST   74
     Khusniddin Alikulov       CB   68
   Mukhammadali Urinboev       RW   63
          I. Tuhtahujaev       CM   57
   Jaloliddin Masharipov      CAM   57
          O. Khamrobekov       CM   57
      Jamshid Iskandarov       CM   57
         Otabek Shukurov       CM   57
          A. Fayzullayev       CM   57
       Khozhimat Erkinov       CM   57
          Akmal Mirzayev       CM   57
         Azizbek Jangiev       CM   57
  Ibrohimhalil Yuldoshev       RB   57
     Abdulloh Abdulloyev       RB   57
Zafarmurod Abdurakhmatov       CB   57
        Oybek Ashmorodov       LB   57
           S. Nasrulloev       CB   57
      Jurab Jaloliddinov       CB   57
    Rustamjon Ashurmatov       CB   57
         Farrukh Sayfiev       CB   57
           K. Alidzhanov       CB   57
      Bunyodbek Ergashev       GK   57
           Utkir Yusupov       GK   57
      Abdulvohid Nematov       GK   57
         Abdurauf Buriev       CM   57

In [58]:
saudi_squad_search = [
    # Goalkeepers
    'Nawaf Al Aqidi', 'Ahmed Al Kassar',
    # Defenders
    'Saud Abdulhamid', 'Hassan Tombakti', 'Ali Al Bulayhi',
    'Ali Lajami', 'Nawaf Boushal', 'Hassan Kadish',
    'Ali Majrashi', 'Abdulelah Al Amri', 'Rayan Hamed',
    # Midfielders
    'Salem Al Dawsari', 'Musab Al Juwair', 'Mohammed Kanno',
    'Abdullah Al Khaibari', 'Ziyad Al Johani', 'Turki Al Ammar',
    'Naif Masoud', 'Salman Al Faraj', 'Mohammed Al Buraik',
    # Forwards
    'Firas Al Birekan', 'Saleh Al Shehri', 'Marwan Al Sahafi',
    'Sultan Al Ghannam', 'Abdullah Al Hamdan', 'Sultan Mandash',
]

saudi_final = players[
    (players['Name'].isin(saudi_squad_search)) &
    (players['Nation'] == 'Saudi Arabia')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
saudi_final['team'] = 'Saudi Arabia'

print(f"إجمالي اللاعبين: {len(saudi_final)}")
print(saudi_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
                Name Position  OVR
    Salem Al Dawsari       LM   82
     Saud Abdulhamid       RB   75
    Firas Al Birekan       LM   75
     Musab Al Juwair       CM   75
      Mohammed Kanno       CM   72
   Sultan Al Ghannam       RB   72
      Nawaf Al Aqidi       GK   72
     Hassan Tombakti       CB   72
       Hassan Kadish       LB   71
        Ali Majrashi       RB   70
   Abdulelah Al Amri       CB   70
      Ali Al Bulayhi       CB   70
          Ali Lajami       CB   70
  Mohammed Al Buraik       LB   70
     Salman Al Faraj       CM   69
     Saleh Al Shehri       ST   69
Abdullah Al Khaibari      CDM   68
      Turki Al Ammar       LB   67
     Ziyad Al Johani      CDM   67
       Nawaf Boushal       LB   67
      Sultan Mandash       RW   67
  Abdullah Al Hamdan       ST   64
    Marwan Al Sahafi       ST   63
     Ahmed Al Kassar       GK   63
         Rayan Hamed       CB   59
         Naif Masoud      CDM   58

In [59]:
# متوسط تقييم قطر بناء على ترتيبها FIFA (~70)
qatar_avg = players_wc.groupby('Nation')['OVR'].mean().mean()

qatar_row = {
    'Nation': 'Qatar',
    'OVR': round(qatar_avg * 0.85),  # أضعف من المتوسط
    'PAC': round(qatar_avg * 0.85),
    'SHO': round(qatar_avg * 0.85),
    'PAS': round(qatar_avg * 0.85),
    'DRI': round(qatar_avg * 0.85),
    'DEF': round(qatar_avg * 0.85),
    'PHY': round(qatar_avg * 0.85),
}

print(f"تقييم قطر الافتراضي: {qatar_row['OVR']}")

تقييم قطر الافتراضي: 57

In [60]:
#كونكاكاف

In [61]:
usa_squad_search = [
    # Goalkeepers
    'Matt Turner', 'Matt Freese', 'Roman Celentano', 'Patrick Schulte',
    # Defenders
    'Antonee Robinson', 'Chris Richards', 'Tim Ream',
    'Joe Scally', 'Mark McKenzie', 'Miles Robinson',
    'Auston Trusty', 'Alex Freeman',
    # Midfielders
    'Christian Pulisic', 'Weston McKennie', 'Giovanni Reyna',
    'Brenden Aaronson', 'Sebastian Berhalter', 'Malik Tillman',
    'Johnny Cardoso', 'Aidan Morris', 'Cristian Roldan',
    'Tanner Tessmann',
    # Forwards
    'Ricardo Pepi', 'Folarin Balogun', 'Timothy Weah',
    'Patrick Agyemang',
]

usa_final = players[
    (players['Name'].isin(usa_squad_search)) &
    (players['Nation'] == 'USA')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
usa_final['team'] = 'USA'

print(f"إجمالي اللاعبين: {len(usa_final)}")
print(usa_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
               Name Position  OVR
  Christian Pulisic       RW   84
   Antonee Robinson       LB   82
      Malik Tillman      CAM   82
     Johnny Cardoso      CDM   81
    Weston McKennie       CM   78
       Timothy Weah       RM   77
    Folarin Balogun       ST   77
     Chris Richards       CB   77
       Ricardo Pepi       ST   76
    Tanner Tessmann      CDM   75
     Giovanni Reyna       RM   75
        Matt Turner       GK   74
      Mark McKenzie       CB   74
      Auston Trusty       CB   74
         Joe Scally       RB   74
   Brenden Aaronson      CAM   74
    Cristian Roldan      CDM   74
       Aidan Morris      CDM   73
     Miles Robinson       CB   73
    Roman Celentano       GK   72
           Tim Ream       CB   72
    Patrick Schulte       GK   71
        Matt Freese       GK   69
Sebastian Berhalter       CM   67
   Patrick Agyemang       ST   67
       Alex Freeman       RB   65

In [62]:
mexico_squad_search = [
    # Goalkeepers
    'Álex Padilla', 'Pablo Sisniega', 'David Ochoa', 'Abraham Romero',
    # Defenders
    'Johan Vásquez', 'Julian Araujo', 'Rodrigo Huescas',
    'Mateo Chávez', 'Jonathan Germán Gómez', 'Alán Montes',
    # Midfielders
    'Edson Álvarez', 'Orbelín Pineda', 'Obed Vargas',
    'Daniel Aguilar', 'Heriberto Jurado', 'Érik Dueñas',
    'César Garza',
    # Forwards
    'Julian Quiñones', 'Santiago Giménez', 'Hirving Lozano',
    'Raúl Jiménez', 'César Huerta', 'Luca Martínez Dupuy',
    'Santiago Muñoz', 'Daniel Ríos', 'Anthony Ramírez',
]

mexico_final = players[
    (players['Name'].isin(mexico_squad_search)) &
    (players['Nation'] == 'Mexico')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
mexico_final['team'] = 'Mexico'

print(f"إجمالي اللاعبين: {len(mexico_final)}")
print(mexico_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
                 Name Position  OVR
      Julian Quiñones       ST   80
     Santiago Giménez       ST   79
        Edson Álvarez      CDM   78
       Hirving Lozano       LW   78
       Orbelín Pineda      CAM   77
         Raúl Jiménez       ST   77
        Johan Vásquez       CB   75
        Julian Araujo       RB   74
         César Huerta       LW   73
      Rodrigo Huescas       RB   72
         Mateo Chávez       LB   72
          Obed Vargas       CM   69
         Álex Padilla       GK   68
  Luca Martínez Dupuy       ST   67
       Daniel Aguilar       CM   66
     Heriberto Jurado       LM   65
          Daniel Ríos       ST   65
       Pablo Sisniega       GK   64
Jonathan Germán Gómez       LB   64
       Santiago Muñoz       ST   63
          David Ochoa       GK   62
       Abraham Romero       GK   61
          César Garza      CDM   61
          Alán Montes       CB   60
          Érik Dueñas       CM   59
      Anthony Ramírez       RW   56

In [63]:
canada_squad_search = [
    # Goalkeepers
    'Dayne St. Clair', 'Maxime Crépeau', 'Jonathan Sirois',
    # Defenders
    'Alistair Johnston', 'Kamal Miller', 'Joel Waterman',
    'Derek Cornelius', 'Moïse Bombito', 'Niko Sigur',
    'Luc De Fougerolles', 'Jahkeele Marshall-Rutty',
    # Midfielders
    'Mathieu Choinière', 'Ismaël Koné', 'Tajon Buchanan',
    'Ali Ahmed', 'Richie Laryea', 'Jonathan Osorio',
    'Liam Millar', 'Nathan-Dylan Saliba', 'Ralph Priso',
    # Forwards
    'Jonathan David', 'Cyle Larin', 'Tani Oluwaseyi',
    'Junior Hoilett', 'Daniel Jebbison', 'Jacen Russell-Rowe',
]

canada_final = players[
    (players['Name'].isin(canada_squad_search)) &
    (players['Nation'] == 'Canada')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
canada_final['team'] = 'Canada'

print(f"إجمالي اللاعبين: {len(canada_final)}")
print(canada_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
                   Name Position  OVR
         Jonathan David       ST   82
      Alistair Johnston       RB   78
             Cyle Larin       ST   77
          Moïse Bombito       CB   76
         Tajon Buchanan       RM   74
        Derek Cornelius       CB   74
        Dayne St. Clair       GK   73
          Richie Laryea       RM   72
            Ismaël Koné       CM   72
            Liam Millar       LM   72
           Kamal Miller       CB   71
        Jonathan Osorio       CM   71
         Tani Oluwaseyi       ST   70
             Niko Sigur       RB   70
         Junior Hoilett       LM   69
         Maxime Crépeau       GK   69
              Ali Ahmed       CM   68
    Nathan-Dylan Saliba       CM   68
          Joel Waterman       CB   68
      Mathieu Choinière       CM   67
        Jonathan Sirois       GK   67
        Daniel Jebbison       ST   65
     Jacen Russell-Rowe       ST   64
Jahkeele Marshall-Rutty       RM   63
            Ralph Priso      CDM   60
     Luc De Fougerolles       CB   58

In [64]:
panama_squad_search = [
    'Amir Murillo', 'Luis Mejía', 'Orlando Mosquera',
    'Eduardo Guerrero', 'Aníbal Godoy', 'Andrés Andrade',
    'José Fajardo', 'José Córdoba', 'Carlos Harvey',
    'Leslie Heráldez', 'Omar Valencia',
]

panama_data = players[
    (players['Name'].isin(panama_squad_search)) &
    (players['Nation'] == 'Panama')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
panama_data['team'] = 'Panama'

default_ovr = 57
missing_panama = pd.DataFrame([
    {'Name': 'César Blackman',        'Position': 'CB',  'OVR': default_ovr},
    {'Name': 'Fidel Escobar',         'Position': 'CB',  'OVR': default_ovr},
    {'Name': 'Edgar Fariña',          'Position': 'CB',  'OVR': default_ovr},
    {'Name': 'Michael Murillo',       'Position': 'RB',  'OVR': default_ovr},
    {'Name': 'Eric Davis',            'Position': 'CB',  'OVR': default_ovr},
    {'Name': 'Giovanni Walsh',        'Position': 'CM',  'OVR': default_ovr},
    {'Name': 'Cristian Martínez',     'Position': 'CM',  'OVR': default_ovr},
    {'Name': 'Adalberto Carrasquilla','Position': 'CM',  'OVR': default_ovr},
    {'Name': 'José Luis Rodríguez',   'Position': 'CM',  'OVR': default_ovr},
    {'Name': 'Ismael Díaz',           'Position': 'ST',  'OVR': default_ovr},
    {'Name': 'Joel Barcenas',         'Position': 'LM',  'OVR': default_ovr},
    {'Name': 'Cecilio Waterman',      'Position': 'ST',  'OVR': default_ovr},
    {'Name': 'César Samudio',         'Position': 'GK',  'OVR': default_ovr},
    {'Name': 'Richard Peralta',       'Position': 'CB',  'OVR': default_ovr},
    {'Name': 'Kevin Galvan',          'Position': 'CB',  'OVR': default_ovr},
])
missing_panama['Nation'] = 'Panama'
missing_panama['team'] = 'Panama'

panama_final = pd.concat([panama_data, missing_panama], ignore_index=True)

print(f"إجمالي اللاعبين: {len(panama_final)}")
print(panama_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
                  Name Position  OVR
          Amir Murillo       RB   76
            Luis Mejía       GK   72
      Orlando Mosquera       GK   70
      Eduardo Guerrero       ST   70
          Aníbal Godoy       CM   70
        Andrés Andrade       CB   69
          José Fajardo       ST   68
          José Córdoba       CB   68
         Carlos Harvey       CB   65
       Leslie Heráldez      CDM   64
         Omar Valencia       LB   59
       Richard Peralta       CB   57
         César Samudio       GK   57
Adalberto Carrasquilla       CM   57
      Cecilio Waterman       ST   57
         Joel Barcenas       LM   57
           Ismael Díaz       ST   57
   José Luis Rodríguez       CM   57
          Edgar Fariña       CB   57
     Cristian Martínez       CM   57
        Giovanni Walsh       CM   57
            Eric Davis       CB   57
       Michael Murillo       RB   57
         Fidel Escobar       CB   57
        César Blackman       CB   57
          Kevin Galvan       CB   57

In [65]:
curacao_squad_search = [
    'Tahith Chong', 'Juninho Bacuna', 'Daijiro Chirino',
    'Shurandy Sambo', 'Brandley Kuwas', 'Sherel Floranus',
    'Ar\'jany Martha', 'Tyrique Mercera', 'Livano Comenencia',
    'Rayvien Rosario', 'Isaiah Ahmed', 'Giandro Sambo',
]

curacao_data = players[
    (players['Name'].isin(curacao_squad_search)) &
    (players['Nation'] == 'Curaçao')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
curacao_data['team'] = 'Curaçao'

default_ovr = 57
missing_curacao = pd.DataFrame([
    {'Name': 'Eloy Room',           'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'T. Bodak',            'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'Trevor Doornbusch',   'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'Rochon van Eijma',    'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Armando Obispo',      'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Joshua Brenet',       'Position': 'RB', 'OVR': default_ovr},
    {'Name': 'Richairo Zivkovic',   'Position': 'RB', 'OVR': default_ovr},
    {'Name': 'D. Fonville',         'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'T. Noslin',           'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Godfrid Roemeratoe',  'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Leandro Bacuna',      'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'J. Antonisse',        'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'J. Gaari',            'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Kevin Felida',        'Position': 'CM', 'OVR': default_ovr},
])
missing_curacao['Nation'] = 'Curaçao'
missing_curacao['team'] = 'Curaçao'

curacao_final = pd.concat([curacao_data, missing_curacao], ignore_index=True)

print(f"إجمالي اللاعبين: {len(curacao_final)}")
print(curacao_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
              Name Position  OVR
      Tahith Chong      CAM   71
    Juninho Bacuna      CDM   69
   Daijiro Chirino       CB   69
    Shurandy Sambo       RB   68
    Brandley Kuwas       LM   67
   Sherel Floranus       RB   66
    Ar'jany Martha       LB   64
   Tyrique Mercera       RB   64
 Livano Comenencia       RB   62
   Rayvien Rosario       LM   60
      Isaiah Ahmed      CDM   58
          J. Gaari       CM   57
      J. Antonisse       CM   57
 Richairo Zivkovic       RB   57
    Leandro Bacuna       CM   57
Godfrid Roemeratoe       CM   57
         T. Noslin       CB   57
       D. Fonville       CB   57
          T. Bodak       GK   57
     Joshua Brenet       RB   57
    Armando Obispo       CB   57
  Rochon van Eijma       CB   57
 Trevor Doornbusch       GK   57
         Eloy Room       GK   57
     Giandro Sambo       LW   57
      Kevin Felida       CM   57

In [66]:
haiti_squad_search = [
    'Frantzdy Pierrot', 'Carlens Arcus', 'Jean-Kévin Duverne',
    'Danley Jean Jacques', 'Johny Placide', 'Fafà Picault',
    'Derrick Etienne Jr.', 'Don Deedson Louicius', 'Martin Expérience',
    'Aleksandr Guboglo', 'Joseph Belmar', 'Wilguens Paugain',
]

haiti_data = players[
    (players['Name'].isin(haiti_squad_search)) &
    (players['Nation'] == 'Haiti')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
haiti_data['team'] = 'Haiti'

default_ovr = 57
missing_haiti = pd.DataFrame([
    {'Name': 'Alexandre Pierre',    'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'Josue Duverger',      'Position': 'GK', 'OVR': default_ovr},
    {'Name': 'Ricardo Ade',         'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Duke Lacroix',        'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Hannes Delcroix',     'Position': 'CB', 'OVR': default_ovr},
    {'Name': 'Stephan Lambese',     'Position': 'LB', 'OVR': default_ovr},
    {'Name': 'Leverton Pierre',     'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Ruben Providence',    'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Christopher Attys',   'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Jean Pellegarde',     'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Carl-Fred Sainte',    'Position': 'CM', 'OVR': default_ovr},
    {'Name': 'Dackens Nason',       'Position': 'ST', 'OVR': default_ovr},
    {'Name': 'Jose Casimir',        'Position': 'ST', 'OVR': default_ovr},
    {'Name': 'Mikael Cantave',      'Position': 'LM', 'OVR': default_ovr},
])
missing_haiti['Nation'] = 'Haiti'
missing_haiti['team'] = 'Haiti'

haiti_final = pd.concat([haiti_data, missing_haiti], ignore_index=True)

print(f"إجمالي اللاعبين: {len(haiti_final)}")
print(haiti_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
                Name Position  OVR
    Frantzdy Pierrot       ST   72
       Carlens Arcus       RB   71
  Jean-Kévin Duverne       LB   71
 Danley Jean Jacques       CM   70
       Johny Placide       GK   69
        Fafà Picault       LW   69
 Derrick Etienne Jr.       LM   66
Don Deedson Louicius       RW   65
   Martin Expérience       LB   62
   Aleksandr Guboglo       RM   59
        Jose Casimir       ST   57
       Dackens Nason       ST   57
    Carl-Fred Sainte       CM   57
     Leverton Pierre       CM   57
     Jean Pellegarde       CM   57
   Christopher Attys       CM   57
    Ruben Providence       CM   57
      Josue Duverger       GK   57
     Stephan Lambese       LB   57
     Hannes Delcroix       CB   57
        Duke Lacroix       CB   57
         Ricardo Ade       CB   57
    Alexandre Pierre       GK   57
      Mikael Cantave       LM   57
       Joseph Belmar       CM   56
    Wilguens Paugain       RB   55

In [67]:
#أوقيانوسيا

In [68]:
new_zealand_squad_search = [
    # Goalkeepers
    'Max Crocombe', 'Alex Paulsen', 'Oliver Sail',
    # Defenders
    'Bill Tuiloma', 'James McGarry', 'Tim Payne',
    'Ben Old', 'Finn Surman', 'Tyler Bindon',
    'Francis de Vries', 'Nando Pijnaker', 'Liberato Cacace',
    # Midfielders
    'Ryan Thomas', 'Alex Rufer', 'Callum McCowatt',
    'Joe Bell', 'Marko Stamenić', 'Lachlan Bayliss',
    'Matthew Garbett',
    # Forwards
    'Kosta Barbarouses', 'Elijah Just', 'Ben Waine',
    'Jesse Randall', 'Logan Rogerson', 'Chris Wood',
    'Callan Elliot',
]

new_zealand_final = players[
    (players['Name'].isin(new_zealand_squad_search)) &
    (players['Nation'] == 'New Zealand')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
new_zealand_final['team'] = 'New Zealand'

print(f"إجمالي اللاعبين: {len(new_zealand_final)}")
print(new_zealand_final[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))

إجمالي اللاعبين: 26
             Name Position  OVR
       Chris Wood       ST   82
         Joe Bell      CDM   74
  Liberato Cacace       LB   72
   Marko Stamenić      CDM   71
     Alex Paulsen       GK   71
 Francis de Vries       LB   69
     Tyler Bindon       CB   69
          Ben Old       LW   68
Kosta Barbarouses       ST   68
      Finn Surman       CB   68
       Alex Rufer      CDM   67
  Callum McCowatt      CAM   67
   Nando Pijnaker       CB   67
      Elijah Just       LW   66
      Ryan Thomas       CM   66
  Matthew Garbett      CAM   65
     Max Crocombe       GK   65
     Bill Tuiloma       CB   65
    James McGarry       LB   64
        Tim Payne       RB   64
   Logan Rogerson       RM   64
      Oliver Sail       GK   63
    Callan Elliot       RB   62
        Ben Waine       ST   62
  Lachlan Bayliss      CAM   62
    Jesse Randall       LM   60

In [69]:

# ==============================
# England
# ==============================
england_squad = [
    'Jordan Pickford', 'Dean Henderson', 'Nick Pope',
    'Ezri Konsa', 'Benjamin White', 'Marc Guéhi', 'Harry Maguire',
    'John Stones', 'Trent Alexander-Arnold', 'Levi Colwill',
    'Jude Bellingham', 'Cole Palmer', 'Phil Foden', 'Declan Rice',
    'James Maddison', 'Conor Gallagher', 'Morgan Gibbs-White', 'Eberechi Eze',
    'Harry Kane', 'Bukayo Saka', 'Anthony Gordon', 'Jarrod Bowen',
    'Ollie Watkins', 'Morgan Rogers', 'Jadon Sancho',
]
england_data = players[players['Name'].isin(england_squad)][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
england_data = england_data.drop_duplicates(subset='Name')
england_data['team'] = 'England'

# ==============================
# France
# ==============================
france_squad_search = [
    'Brice Samba', 'Mike Maignan', 'Lucas Chevalier',
    'Malo Gusto', 'Lucas Digne', 'Dayot Upamecano', 'Pierre Kalulu',
    'Ibrahima Konaté', 'Maxence Lacroix', 'Theo Hernández', 'William Saliba',
    'Eduardo Camavinga', 'Aurélien Tchouaméni', "N'Golo Kanté",
    'Adrien Rabiot', 'Warren Zaïre-Emery', 'Désiré Doué', 'Rayan Cherki',
    'Maghnes Akliouche',
    'Ousmane Dembélé', 'Michael Olise', 'Marcus Thuram',
    'Kylian Mbappé', 'Randal Kolo Muani', 'Hugo Ekitiké', 'Bradley Barcola',
]
france_data = players[players['Name'].isin(france_squad_search)][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
france_data['team'] = 'France'

# ==============================
# Spain
# ==============================
spain_squad_search = [
    'David Raya', 'Unai Simón', 'Joan García',
    'Mosquera', 'Grimaldo', 'Pau Cubarsí', 'Dean Huijsen',
    'Pedro Porro', 'Aymeric Laporte', 'Marc Cucurella',
    'Marcos Llorente', 'Carlos Soler', 'Rodri', 'Pablo Fornals',
    'Zubimendi', 'Pedri', 'Oyarzabal', 'Álex Baena',
    'Ferran Torres', 'Borja Iglesias', 'Dani Olmo', 'Yeremy Pino',
    'Lamine Yamal', 'Víctor Muñoz', 'Barrenetxea', 'Fabián Ruiz',
]
spain_data = players[players['Name'].isin(spain_squad_search)][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
spain_data['team'] = 'Spain'

# ==============================
# Portugal
# ==============================
portugal_squad_search = [
    'Diogo Costa', 'Rui Silva', 'José Sá',
    'Diogo Dalot', 'António Silva', 'Gonçalo Inácio',
    'João Cancelo', 'Nuno Mendes', 'Renato Veiga',
    'Matheus Nunes', 'Bruno Fernandes',
    'João Neves', 'Pedro Gonçalves', 'Rúben Neves',
    'Francisco Conceição', 'Ricardo Horta',
    'Gonçalo Ramos', 'João Félix', 'Rafael Leão',
    'Pedro Neto', 'Gonçalo Guedes', 'Rodrigo Mora',
    'Cristiano Ronaldo',
]
portugal_data = players[
    (players['Name'].isin(portugal_squad_search)) &
    (players['Nation'] == 'Portugal')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
extra = players.loc[[10, 2345, 10681]][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
portugal_data = pd.concat([portugal_data, extra])
portugal_data['team'] = 'Portugal'

# ==============================
# Germany
# ==============================
germany_squad_search = [
    'Joshua Kimmich', 'Florian Wirtz', 'Jamal Musiala',
    'Jonathan Tah', 'Antonio Rüdiger', 'Marc-André ter Stegen',
    'Nico Schlotterbeck', 'Manuel Neuer', 'Oliver Baumann',
    'Angelo Stiller', 'Leon Goretzka', 'Felix Nmecha',
    'David Raum', 'Leroy Sané', 'Serge Gnabry',
    'Kai Havertz', 'Waldemar Anton', 'Pascal Groß',
    'Deniz Undav', 'Anton Stach', 'Nick Woltemade',
    'Malick Thiaw', 'Kevin Schade', 'Chris Führich',
    'Nathaniel Brown', 'Jamie Leweling',
]
germany_data = players[players['Name'].isin(germany_squad_search)][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
germany_data = germany_data.drop_duplicates(subset='Name')
germany_data['team'] = 'Germany'

# ==============================
# Netherlands
# ==============================
netherlands_squad_search = [
    'Bart Verbruggen', 'Justin Bijlow', 'Mark Flekken',
    'Matthijs de Ligt', 'Jan Paul van Hecke', 'Virgil van Dijk',
    'Nathan Aké', 'Stefan de Vrij', 'Jeremie Frimpong',
    'Jurriën Timber', 'Micky van de Ven', 'Denzel Dumfries', 'Jorrel Hato',
    'Xavi Simons', 'Ryan Gravenberch', 'Frenkie de Jong',
    'Tijjani Reijnders', 'Jerdy Schouten', 'Teun Koopmeiners',
    'Quinten Timber', 'Wout Weghorst', 'Cody Gakpo',
    'Noa Lang', 'Donyell Malen', 'Brian Brobbey', 'Steven Bergwijn',
]
netherlands_data = players[players['Name'].isin(netherlands_squad_search)][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
netherlands_data['team'] = 'Netherlands'

# ==============================
# Belgium
# ==============================
belgium_squad_search = [
    'Thibaut Courtois', 'Senne Lammens', 'Matz Sels',
    'Zeno Debast', 'Arthur Theate', 'Brandon Mechele',
    'Axel Witsel', 'Wout Faes', 'Joaquin Seys',
    'Nathan Ngoy', 'Timothy Castagne',
    'Maxim De Cuyper', 'Kevin De Bruyne', 'Youri Tielemans',
    'Jérémy Doku', 'Thomas Meunier', 'Charles De Ketelaere',
    'Leandro Trossard', 'Hans Vanaken', 'Alexis Saelemaekers',
    'Nicolas Raskin', 'Amadou Onana',
    'Loïs Openda', 'Romelu Lukaku', 'Dodi Lukébakio', 'Yannick Carrasco',
]
belgium_data = players[players['Name'].isin(belgium_squad_search)][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
belgium_data['team'] = 'Belgium'

# ==============================
# Croatia
# ==============================
croatia_squad_search = [
    'Dominik Livaković', 'Dominik Kotarski', 'Ivor Pandur',
    'Josip Stanišić', 'Marin Pongračić', 'Duje Ćaleta-Car',
    'Josip Šutalo', 'Luka Vušković', 'Martin Erlić',
    'Joško Gvardiol', 'Lovro Majer', 'Nikola Moro', 'Luka Modrić',
    'Nikola Vlašić', 'Ivan Perišić', 'Mario Pašalić', 'Martin Baturina',
    'Petar Sučić', 'Kristijan Jakić', 'Luka Sučić',
    'Mateo Kovačić', 'Marcelo Brozović',
    'Andrej Kramarić', 'Ante Budimir', 'Igor Matanović', 'Petar Musa',
]
croatia_data = players[players['Name'].isin(croatia_squad_search)][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
croatia_data['team'] = 'Croatia'

# ==============================
# Switzerland
# ==============================
switzerland_squad_search = [
    'Yann Sommer', 'Gregor Kobel', 'Marvin Keller',
    'Lucas Blondel', 'Miro Muheim', 'Silvan Widmer', 'Nico Elvedi',
    'Manuel Akanji', 'Ricardo Rodriguez', 'Cedric Zesiger',
    'Eray Cömert', 'Ulisses Garcia', 'Luca Jaquez', 'Isaac Schmidt',
    'Stefan Gartenmann',
    'Denis Zakaria', 'Remo Freuler',
    'Granit Xhaka', 'Ardon Jashari', 'Djibril Sow',
    'Vincent Sierro', 'Ruben Vargas', 'Michel Aebischer',
    'Fabian Rieder', 'Dan Ndoye', 'Zeki Amdouni', 'Noah Okafor',
    'Breel Embolo',
]
switzerland_data = players[players['Name'].isin(switzerland_squad_search)][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
switzerland_data['team'] = 'Switzerland'

# ==============================
# Norway
# ==============================
norway_squad_search = [
    'Ørjan Nyland', 'Egil Selvik', 'Viljar Myhra',
    'Kristoffer Ajer', 'Torbjørn L. Heggem', 'David Møller Wolfe',
    'Julian Ryerson', 'Fredrik Bjørkan', 'Marcus Pedersen',
    'Andreas Hanche-Olsen',
    'Morten Thorsby', 'Patrick Berg', 'Sander Berge',
    'Kristian Thorstvedt', 'Felix Horn Myhre', 'Antonio Nusa',
    'Andreas Schjelderup', 'Oscar Bobb', 'Martin Ødegaard',
    'Fredrik Aursnes',
    'Alexander Sørloth', 'Erling Haaland', 'Jens Petter Hauge',
    'Jørgen Strand Larsen', 'Joshua King', 'Mohamed Elyounoussi',
]
norway_data = players[players['Name'].isin(norway_squad_search)][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
norway_data['team'] = 'Norway'

# ==============================
# Scotland
# ==============================
scotland_squad_search = [
    'Angus Gunn', 'Liam Kelly', 'Scott Bain',
    'Nathan Patterson', 'Andrew Robertson', 'Grant Hanley',
    'Kieran Tierney', 'Jack Hendry', 'John Souttar',
    'Ross McCrorie', 'Max Johnston', 'Anthony Ralston', 'Scott McKenna',
    'Scott McTominay', 'John McGinn', 'Billy Gilmour',
    'Ryan Christie', 'Lewis Ferguson', 'Kenny McLean',
    'Andy Irving', 'Callum McGregor', 'Ryan Gauld',
    'Lyndon Dykes', 'Ché Adams', 'George Hirst', 'Tommy Conway',
]
scotland_data = players[
    (players['Name'].isin(scotland_squad_search)) &
    (players['Nation'] == 'Scotland')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
scotland_data = scotland_data.drop_duplicates(subset='Name')
scotland_data['team'] = 'Scotland'

# ==============================
# Austria
# ==============================
austria_squad_search = [
    'Alexander Schlager', 'Tobias Lawal', 'Patrick Pentz',
    'Kevin Danso', 'Stefan Posch', 'David Alaba',
    'Philipp Lienhart', 'Phillipp Mwene', 'Marco Friedl',
    'Maximilian Wöber', 'David Affengruber',
    'Xaver Schlager', 'Nicolas Seiwald', 'Marcel Sabitzer',
    'Florian Grillitsch', 'Karim Adeyemi', 'Romano Schmid',
    'Christoph Baumgartner', 'Konrad Laimer', 'Alexander Prass',
    'Alessandro Schöpf', 'Patrick Wimmer',
    'Michael Gregoritsch', 'Valentino Lazaro', 'Kevin Stöger', 'Marco Grüll',
]
austria_data = players[players['Name'].isin(austria_squad_search)][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
austria_data['team'] = 'Austria'

# ==============================
# Bosnia and Herzegovina
# ==============================
bosnia_squad_search = [
    'Nikola Vasilj', 'Vladan Kovacević', 'Asmir Begović',
    'Sead Kolašinac', 'Amar Dedić', 'Nidal Čelik',
    'Anel Ahmedhodžić', 'Nikola Katić', 'Tarik Muharemović',
    'Nihad Mujakić', 'Adrian Barišić',
    'Amir Hadžiahmetović', 'Armin Gigović', 'Dženis Burnić',
    'Benjamin Tahirović', 'Amar Memić', 'Denis Huseinbašić',
    'Esmir Bajraktarević',
    'Edin Džeko', 'Haris Tabaković', 'Ermedin Demirović',
    'Samed Baždar', 'Jovo Lukić', 'Kerim Alajbegović',
    'Milan Đurić', 'Luka Kulenović',
]
bosnia_final = players[
    (players['Name'].isin(bosnia_squad_search)) &
    (players['Nation'] == 'Bosnia and Herzegovina')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
bosnia_final['team'] = 'Bosnia and Herzegovina'

# ==============================
# Sweden
# ==============================
sweden_squad_search = [
    'Kristoffer Nordfeldt', 'Noel Törnqvist', 'Melker Ellborg',
    'Carl Starfelt', 'Daniel Svensson', 'Isak Hien',
    'Gustaf Lagerbielke', 'Gabriel Gudmundsson', 'Emil Krafth',
    'Herman Johansson', 'Samuel Dahl',
    'Mattias Svanberg', 'Jesper Karlström', 'Yasin Ayari',
    'Hugo Larsson', 'Besfort Zeneli', 'Elliot Stroud', 'Lucas Bergvall',
    'Viktor Gyökeres', 'Gustaf Nilsson', 'Benjamin Nygren',
    'Anthony Elanga', 'Williot Swedberg', 'Roony Bardghji',
    'Gustav Lundgren', 'Taha Ali',
]
sweden_final = players[
    (players['Name'].isin(sweden_squad_search)) &
    (players['Nation'] == 'Sweden')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
sweden_final['team'] = 'Sweden'

# ==============================
# Turkey
# ==============================
turkey_squad_search = [
    'Mert Günok', 'Altay Bayındır', 'Uğurcan Çakır',
    'Zeki Çelik', 'Samet Akaydın', 'Abdülkerim Bardakcı',
    'Merih Demiral', 'Mert Müldür', 'Eren Elmalı',
    'Ozan Kabak', 'Atakan Karazor',
    'Salih Özcan', 'Orkun Kökçü', 'Hakan Çalhanoğlu',
    'İsmail Yüksek', 'Ferdi Kadıoğlu', 'İrfan Can Kahveci',
    'Mustafa Eskihellaç',
    'Kerem Aktürkoğlu', 'Arda Güler', 'Kenan Yıldız',
    'Oğuz Aydın', 'Yunus Akgün', 'Semih Kılıçsoy',
    'Deniz Gül', 'Aral Şimşir',
]
turkey_final = players[
    (players['Name'].isin(turkey_squad_search)) &
    (players['Nation'] == 'Turkey')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
turkey_final['team'] = 'Turkey'

# ==============================
# Czech Republic
# ==============================
czech_squad_search = [
    'Matěj Kovář', 'Martin Jedlička', 'Lukas Hornicek',
    'Tomáš Holeš', 'Vladimír Coufal', 'Ladislav Krejčí',
    'Jaroslav Zelený', 'Martin Vitík', 'David Jurásek',
    'Štěpán Chaloupek', 'Robin Hranáč',
    'Lukáš Červ', 'Lukáš Provod', 'Pavel Šulc',
    'Michal Sadílek', 'Tomáš Souček', 'Pavel Bucha',
    'Adam Karabec', 'Denis Višinský',
    'Patrik Schick', 'Tomáš Chorý', 'Tomáš Ladra',
    'Adam Hložek', 'Václav Černý', 'Mojmír Chytil', 'Jan Kuchta',
]
czech_final = players[
    (players['Name'].isin(czech_squad_search)) &
    (players['Nation'] == 'Czech Republic')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
czech_final['team'] = 'Czech Republic'


# طباعة ملخص
print("=== ملخص أوروبا ===")
print(f"England: {len(england_data)}")
print(f"France: {len(france_data)}")
print(f"Spain: {len(spain_data)}")
print(f"Portugal: {len(portugal_data)}")
print(f"Germany: {len(germany_data)}")
print(f"Netherlands: {len(netherlands_data)}")
print(f"Belgium: {len(belgium_data)}")
print(f"Croatia: {len(croatia_data)}")
print(f"Switzerland: {len(switzerland_data)}")
print(f"Norway: {len(norway_data)}")
print(f"Scotland: {len(scotland_data)}")
print(f"Austria: {len(austria_data)}")
print(f"Bosnia: {len(bosnia_final)}")
print(f"Sweden: {len(sweden_final)}")
print(f"Turkey: {len(turkey_final)}")
print(f"Czech Republic: {len(czech_final)}")

=== ملخص أوروبا ===
England: 25
France: 26
Spain: 26
Portugal: 26
Germany: 26
Netherlands: 26
Belgium: 26
Croatia: 26
Switzerland: 26
Norway: 26
Scotland: 26
Austria: 26
Bosnia: 26
Sweden: 26
Turkey: 26
Czech Republic: 26

In [70]:
# ==============================
# Morocco
# ==============================
morocco_squad_search = [
    'Yassine Bounou', 'Alaa Bellaarouch', 'Issam El Maach',
    'Achraf Hakimi', 'Noussair Mazraoui', 'Nayef Aguerd',
    'Jawad El Yamiq', 'Adam Masina', 'Neil El Aynaoui',
    'Sofyan Amrabat', 'Azzedine Ounahi', 'Brahim',
    'Ismael Saibari', 'Oussama Targhalline', 'Bilal El Khannouss',
    'Abdessamad Ezzalzouli', 'Youssef En-Nesyri',
    'Ayoub El Kaabi', 'Chemsdine Talbi', 'Hamza Igamane',
    'Soufiane Rahimi', 'Ilias Akhomach',
    'Abderrazak Hamdallah', 'Amine Adli', 'Sofiane Diop',
    'Eliesse Ben Seghir',
]
morocco_data = players[
    (players['Name'].isin(morocco_squad_search)) &
    (players['Nation'] == 'Morocco')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
morocco_data['team'] = 'Morocco'

# ==============================
# Senegal
# ==============================
senegal_squad_search = [
    'Édouard Mendy', 'Mory Diaw',
    'Kalidou Koulibaly', 'Ismail Jakobs', 'Moussa Niakhaté', 'Antoine Mendy',
    'Idrissa Gueye', 'Pape Matar Sarr', 'Habib Diarra',
    'Lamine Camara', 'Pape Gueye',
    'Sadio Mané', 'Nicolas Jackson', 'Iliman Ndiaye', 'Krépin Diatta',
    'Ismaïla Sarr', 'Ousseynou Niang', 'Boulaye Dia', 'Bamba Dieng',
]
senegal_data = players[
    (players['Name'].isin(senegal_squad_search)) &
    (players['Nation'] == 'Senegal')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
senegal_data = senegal_data[~((senegal_data['Name'] == 'Idrissa Gueye') & (senegal_data['Position'] == 'ST'))]
senegal_data['team'] = 'Senegal'
missing_senegal = pd.DataFrame([
    {'Name': 'Yahia Fofana',     'Position': 'GK', 'OVR': 57, 'Nation': 'Senegal', 'team': 'Senegal'},
    {'Name': 'Mamadou Sarr',     'Position': 'CB', 'OVR': 57, 'Nation': 'Senegal', 'team': 'Senegal'},
    {'Name': 'Abdoulaye Seck',   'Position': 'CB', 'OVR': 57, 'Nation': 'Senegal', 'team': 'Senegal'},
    {'Name': 'M. Diouf',         'Position': 'CM', 'OVR': 57, 'Nation': 'Senegal', 'team': 'Senegal'},
    {'Name': 'Cherif Ndiaye',    'Position': 'ST', 'OVR': 57, 'Nation': 'Senegal', 'team': 'Senegal'},
    {'Name': 'Cheikhou Kouyate', 'Position': 'CM', 'OVR': 57, 'Nation': 'Senegal', 'team': 'Senegal'},
    {'Name': 'Pape Gueye II',    'Position': 'CM', 'OVR': 57, 'Nation': 'Senegal', 'team': 'Senegal'},
])
senegal_final = pd.concat([senegal_data, missing_senegal], ignore_index=True)

# ==============================
# Egypt
# ==============================
egypt_squad_search = [
    'Mohamed Salah', 'Omar Marmoush', 'Mostafa Mohamed',
    'Mohamed Abdelmonem', 'Ramy Rabia',
]
egypt_data = players[
    (players['Name'].isin(egypt_squad_search)) &
    (players['Nation'] == 'Egypt')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
egypt_data['team'] = 'Egypt'
missing_egypt = pd.DataFrame([
    {'Name': 'Mohamed El-Shennawy',  'Position': 'GK', 'OVR': 57},
    {'Name': 'Mahdi Suleiman',       'Position': 'GK', 'OVR': 57},
    {'Name': 'Mostafa Shobeir',      'Position': 'GK', 'OVR': 57},
    {'Name': 'M. Alaa',              'Position': 'GK', 'OVR': 57},
    {'Name': 'Yasser Ibrahim',       'Position': 'CB', 'OVR': 57},
    {'Name': 'Mohamed Hany',         'Position': 'CB', 'OVR': 57},
    {'Name': 'Hussam Abdel Salam',   'Position': 'CB', 'OVR': 57},
    {'Name': 'Ahmed Abou El Fotouh', 'Position': 'CB', 'OVR': 57},
    {'Name': 'Khalid Sobhi',         'Position': 'CB', 'OVR': 57},
    {'Name': 'Tarek Alaa',           'Position': 'CB', 'OVR': 57},
    {'Name': 'Emam Ashour',          'Position': 'CM', 'OVR': 57},
    {'Name': 'Ahmed Koka',           'Position': 'CM', 'OVR': 57},
    {'Name': 'Mohanad Lashin',       'Position': 'CM', 'OVR': 57},
    {'Name': 'Islam Issa',           'Position': 'CM', 'OVR': 57},
    {'Name': 'Marwan Attia',         'Position': 'CM', 'OVR': 57},
    {'Name': 'Ahmed Sayed Zizo',     'Position': 'CM', 'OVR': 57},
    {'Name': 'Mahmoud Saber',        'Position': 'CM', 'OVR': 57},
    {'Name': 'Mahmoud Hassan',       'Position': 'LM', 'OVR': 57},
    {'Name': 'Nasser Mansi',         'Position': 'ST', 'OVR': 57},
    {'Name': 'Hayssem Hassan',       'Position': 'ST', 'OVR': 57},
    {'Name': 'Ibrahim Adel',         'Position': 'LW', 'OVR': 57},
])
missing_egypt['Nation'] = 'Egypt'
missing_egypt['team'] = 'Egypt'
egypt_final = pd.concat([egypt_data, missing_egypt], ignore_index=True)
egypt_final = egypt_final[egypt_final['Name'] != 'Hamdi Fathi']

# ==============================
# Algeria
# ==============================
algeria_squad_search = [
    'Aïssa Mandi', 'Mehdi Dorval', 'Ramy Bensebaini',
    'Rayan Aït-Nouri', 'Jaouen Hadjam',
    'Ramiz Zerrouki', 'Houssem Aouar', 'Ismaël Bennacer',
    'Hicham Boudaoui', 'Farès Chaïbi', 'Adem Zorgane',
    'Ibrahim Maza', 'Ilan Kebbal', 'Saïd Benrahma',
    'Himad Abdelli', 'Badredine Bouanani', 'Nabil Bentaleb',
    'Riyad Mahrez', 'Mohamed Amoura', 'Amine Gouiri',
    'Anis Hadj-Moussa', 'Mounsef Bakrar', 'Rafik Belghali',
]
algeria_data = players[
    (players['Name'].isin(algeria_squad_search)) &
    (players['Nation'] == 'Algeria')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
algeria_data['team'] = 'Algeria'
missing_algeria = pd.DataFrame([
    {'Name': 'Anthony Mandrea', 'Position': 'GK', 'OVR': 57, 'Nation': 'Algeria', 'team': 'Algeria'},
    {'Name': 'O. Benbot',       'Position': 'GK', 'OVR': 57, 'Nation': 'Algeria', 'team': 'Algeria'},
    {'Name': 'Luca Zidane',     'Position': 'GK', 'OVR': 57, 'Nation': 'Algeria', 'team': 'Algeria'},
])
algeria_final = pd.concat([algeria_data, missing_algeria], ignore_index=True)

# ==============================
# Tunisia
# ==============================
tunisia_squad_search = [
    'Ali Abdi', 'Montassar Talbi', 'Dylan Bronn',
    'Yan Valery', 'Mortadha Ben Ouanes', 'Mohamed Dräger',
    'Ellyes Skhiri', 'Hannibal', 'Elias Achouri',
    'Mohamed Belhadj Mahmoud', 'Saîf-Eddine Khaoui',
    'Sebastian Tounekti', 'Hamza Rafia', 'Anis Slimane',
    'Ismaël Gharbi', 'Elias Saad', 'Amor Layouni',
    'Sayfallah Ltaief', 'Idris El Mizouni', 'Alaa Ghram',
    'Amin Cherni', 'Chiheb Labidi',
]
tunisia_data = players[
    (players['Name'].isin(tunisia_squad_search)) &
    (players['Nation'] == 'Tunisia')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
tunisia_data['team'] = 'Tunisia'
missing_tunisia = pd.DataFrame([
    {'Name': 'Noureddine Farhat', 'Position': 'GK', 'OVR': 57, 'Nation': 'Tunisia', 'team': 'Tunisia'},
    {'Name': 'Aymen Dahmen',      'Position': 'GK', 'OVR': 57, 'Nation': 'Tunisia', 'team': 'Tunisia'},
    {'Name': 'Bechir Ben Said',   'Position': 'GK', 'OVR': 57, 'Nation': 'Tunisia', 'team': 'Tunisia'},
    {'Name': 'Sabri Ben Hassan',  'Position': 'GK', 'OVR': 57, 'Nation': 'Tunisia', 'team': 'Tunisia'},
])
tunisia_final = pd.concat([tunisia_data, missing_tunisia], ignore_index=True)

# ==============================
# Ghana
# ==============================
ghana_squad_search = [
    'Lawrence Ati Zigi', 'Joseph Anang',
    'Jonas Adjetey', 'Gideon Mensah', 'Jerome Opoku',
    'Abdul Mumin', 'Mohammed Salisu', 'Rahman Baba',
    'Joseph Aidoo', 'Alidu Seidu', 'Tariq Lamptey',
    'Thomas Partey', 'Elisha Owusu', 'Mohammed Kudus',
    'Ibrahim Sulemana', 'Salis Abdul Samed', 'Kwasi Sibo',
    'Caleb Yirenkyi',
    'Iñaki Williams', 'Antoine Semenyo', 'Jordan Ayew',
    'Kamaldeen Sulemana', 'Ransford-Yeboah Königsdörffer',
    'Christopher Bonsu Baah', 'Prince Kwabena Adu',
    'Brandon Thomas-Asante',
]
ghana_final = players[
    (players['Name'].isin(ghana_squad_search)) &
    (players['Nation'] == 'Ghana')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
ghana_final['team'] = 'Ghana'

# ==============================
# Ivory Coast
# ==============================
ivory_squad_search = [
    'Yahia Fofana', 'Alban Lafont', 'Mohamed Koné',
    'Ousmane Diomande', 'Ghislain Konan', 'Wilfried Singo',
    'Odilon Kossounou', 'Clément Akpa', 'Guéla Doué',
    'Emmanuel Agbadou', 'Evan Ndicka',
    'Seko Fofana', 'Franck Yannick Kessié', 'Bénie Traoré',
    'Ibrahim Sangaré', 'Christ Ravynel Inao Oulaï', 'Parfait Guiagon',
    'Simon Adingra', 'Amad', 'Evann Guessand',
    'Hamed Junior Traoré', 'Bazoumana Touré', 'Nicolas Pépé',
    'Martial Godo', 'Willy Boly', 'Ismaila Soro',
]
ivory_final = players[
    (players['Name'].isin(ivory_squad_search)) &
    (players['Nation'] == 'Ivory Coast')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
ivory_final['team'] = 'Ivory Coast'

# ==============================
# South Africa
# ==============================
sa_squad_search = [
    'Siyabonga Ngezana', 'Gift Links', 'Bongokuhle Hlongwane',
    'Ime Okon', 'Samukele Kabini', 'Olwethu Makhanya',
    'Yusuf Maart', 'Luke Le Roux', 'Sphephelo Sithole',
    'Kegs Chauke', 'Kobamelo Kodisang',
    'Lyle Foster', 'Shandre Campbell', 'Antonio van Wyk',
]
sa_data = players[
    (players['Name'].isin(sa_squad_search)) &
    (players['Nation'] == 'South Africa')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
sa_data['team'] = 'South Africa'
missing_sa = pd.DataFrame([
    {'Name': 'Ronwen Williams', 'Position': 'GK', 'OVR': 57},
    {'Name': 'S. Chaine',       'Position': 'GK', 'OVR': 57},
    {'Name': 'Ricardo Goss',    'Position': 'GK', 'OVR': 57},
    {'Name': 'T. Smith',        'Position': 'CB', 'OVR': 57},
    {'Name': 'K. Ndamane',      'Position': 'RB', 'OVR': 57},
    {'Name': 'M. Mbokazi',      'Position': 'CB', 'OVR': 57},
    {'Name': 'S. Kabini',       'Position': 'LB', 'OVR': 57},
    {'Name': 'N. Sibisi',       'Position': 'CB', 'OVR': 57},
    {'Name': 'T. Matuludi',     'Position': 'CM', 'OVR': 57},
    {'Name': 'T. Moremi',       'Position': 'CM', 'OVR': 57},
    {'Name': 'R. Mofokeng',     'Position': 'RM', 'OVR': 57},
    {'Name': 'M. Shabalala',    'Position': 'ST', 'OVR': 57},
])
missing_sa['Nation'] = 'South Africa'
missing_sa['team'] = 'South Africa'
sa_final = pd.concat([sa_data, missing_sa], ignore_index=True)

# ==============================
# Cape Verde
# ==============================
cabo_final = pd.DataFrame([
    {'Name': 'Vozinha',          'Position': 'GK', 'OVR': 57},
    {'Name': 'Marcio Rosa',      'Position': 'GK', 'OVR': 57},
    {'Name': 'Bruno Varela',     'Position': 'GK', 'OVR': 57},
    {'Name': 'W. Pina',          'Position': 'RB', 'OVR': 57},
    {'Name': 'Stopira',          'Position': 'CB', 'OVR': 57},
    {'Name': 'Deni',             'Position': 'CB', 'OVR': 57},
    {'Name': 'Roberto Lopez',    'Position': 'CB', 'OVR': 57},
    {'Name': 'K. Pires',         'Position': 'CB', 'OVR': 57},
    {'Name': 'S. Lopes Cabral',  'Position': 'LB', 'OVR': 57},
    {'Name': 'Steven Moriera',   'Position': 'RB', 'OVR': 57},
    {'Name': 'A. Tavares',       'Position': 'CM', 'OVR': 57},
    {'Name': 'Kevin Linhares',   'Position': 'CM', 'OVR': 57},
    {'Name': 'A. Santos',        'Position': 'CM', 'OVR': 57},
    {'Name': 'Joao Paulo',       'Position': 'CM', 'OVR': 57},
    {'Name': 'Jovane Cabral',    'Position': 'LM', 'OVR': 57},
    {'Name': 'Jamiro Monteiro',  'Position': 'CM', 'OVR': 57},
    {'Name': 'D. Duarte',        'Position': 'CM', 'OVR': 57},
    {'Name': 'Laroys Duarte',    'Position': 'CM', 'OVR': 57},
    {'Name': 'Y. Semedo',        'Position': 'CM', 'OVR': 57},
    {'Name': 'Telmo Arcanjo',    'Position': 'RM', 'OVR': 57},
    {'Name': 'J. Correia',       'Position': 'CM', 'OVR': 57},
    {'Name': 'Djallon Livramento','Position': 'ST', 'OVR': 57},
    {'Name': 'Garry Rodrigues',  'Position': 'RW', 'OVR': 57},
    {'Name': 'Ryan Mendes',      'Position': 'LW', 'OVR': 57},
    {'Name': 'Helio Varela',     'Position': 'ST', 'OVR': 57},
    {'Name': 'Nuno Da Costa',    'Position': 'ST', 'OVR': 57},
])
cabo_final['Nation'] = 'Cape Verde'
cabo_final['team'] = 'Cape Verde'

# ==============================
# DR Congo
# ==============================
dr_congo_squad_search = [
    'Lionel Mpasi',
    'Aaron Wan-Bissaka', 'Arthur Masuaku', 'Axel Tuanzebe',
    'Dylan Batubinsika', 'Steve Kapuadi', 'Marcel Tisserand',
    'Jeremy Ngakia', 'Joris Kayembe',
    'Noah Sadiki', "Ngal'ayel Mukau", 'Edo Kayembe',
    'Charles Pickel', 'Beni Baningime', 'Pelly-Ruddock Mpanzu',
    'William Balikwisha',
    'Yoane Wissa', 'Simon Banza', 'Cédric Bakambu',
    'Silas', 'Samuel Essende', 'Afimico Pululu',
    'Nathanaël Mbuku', 'Meschack Elia',
]
dr_congo_data = players[
    (players['Name'].isin(dr_congo_squad_search)) &
    (players['Nation'] == 'DR Congo')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
dr_congo_data['team'] = 'DR Congo'
missing_dr_congo = pd.DataFrame([
    {'Name': 'Joel Kiassumbua', 'Position': 'GK', 'OVR': 57, 'Nation': 'DR Congo', 'team': 'DR Congo'},
    {'Name': 'Joris Delle',     'Position': 'GK', 'OVR': 57, 'Nation': 'DR Congo', 'team': 'DR Congo'},
])
dr_congo_final = pd.concat([dr_congo_data, missing_dr_congo], ignore_index=True)

# ==============================
# ملخص أفريقيا
# ==============================
print("=== ملخص أفريقيا ===")
print(f"Morocco: {len(morocco_data)}")
print(f"Senegal: {len(senegal_final)}")
print(f"Egypt: {len(egypt_final)}")
print(f"Algeria: {len(algeria_final)}")
print(f"Tunisia: {len(tunisia_final)}")
print(f"Ghana: {len(ghana_final)}")
print(f"Ivory Coast: {len(ivory_final)}")
print(f"South Africa: {len(sa_final)}")
print(f"Cape Verde: {len(cabo_final)}")
print(f"DR Congo: {len(dr_congo_final)}")

=== ملخص أفريقيا ===
Morocco: 26
Senegal: 26
Egypt: 26
Algeria: 26
Tunisia: 26
Ghana: 26
Ivory Coast: 26
South Africa: 26
Cape Verde: 26
DR Congo: 26

In [71]:
# ==============================
# Argentina
# ==============================
argentina_squad_search = [
    'Emiliano Martínez', 'Gerónimo Rulli', 'Juan Musso',
    'Lucas Martínez Quarta', 'Nicolás Tagliafico', 'Marcos Senesi',
    'Marcos Acuña', 'Cristian Romero', 'Nicolás Otamendi',
    'Nahuel Molina', 'Valentín Barco',
    'Leandro Paredes', 'Rodrigo De Paul', 'Thiago Almada',
    'Exequiel Palacios', 'Alexis Mac Allister', 'Enzo Fernández',
    'Nico Paz', 'Máximo Perrone',
    'Julián Alvarez', 'Lionel Messi', 'Nico Gonzalez',
    'Giuliano Simeone', 'Lautaro Martínez', 'Franco Mastantuono',
    'Gianluca Prestianni',
]
argentina_final = players[
    (players['Name'].isin(argentina_squad_search)) &
    (players['Nation'] == 'Argentina')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
argentina_final['team'] = 'Argentina'

# ==============================
# Brazil
# ==============================
brazil_squad_search = [
    'Ederson', 'Bento',
    'Bremer', 'Renan Lodi', 'Carlos Augusto',
    'Éder Militão', 'Ibañez',
    'Casemiro', 'Fabinho', 'Gabriel Sara',
    'Andrey Santos', 'Bruno Guimarães', 'Lucas Paquetá',
    'Vini Jr.', 'Raphinha', 'Endrick',
    'Gabriel Martinelli', 'Matheus Cunha',
    'Luis Henrique', 'Igor Thiago',
    'Savinho', 'Rodrygo',
]
brazil_data = players[
    (players['Name'].isin(brazil_squad_search)) &
    (players['Nation'] == 'Brazil')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
brazil_data['team'] = 'Brazil'
specific_brazil = players[
    (players['Nation'] == 'Brazil') &
    (
        ((players['Name'] == 'Marquinhos') & (players['Position'] == 'CB')) |
        ((players['Name'] == 'Wesley')     & (players['Position'] == 'RB')) |
        ((players['Name'] == 'João Pedro') & (players['Position'] == 'ST')) |
        ((players['Name'] == 'Yan Couto')  & (players['Position'] == 'RB'))
    )
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
specific_brazil['team'] = 'Brazil'
brazil_final = pd.concat([brazil_data, specific_brazil], ignore_index=True)

# ==============================
# Colombia
# ==============================
colombia_squad_search = [
    'David Ospina', 'Álvaro Montero', 'Devis Vásquez',
    'Daniel Muñoz', 'Jhon Lucumí', 'Johan Mojica',
    'Deiver Machado', 'Davinson Sánchez', 'Yerson Mosquera',
    'Juan David Cabal',
    'Kevin Castaño', 'Richard Ríos', 'Jefferson Lerma',
    'Juan Fernando Quintero', 'Jhon Arias', 'Jaminton Campaz',
    'Gustavo Puerta', 'Mateus Uribe', 'Juan Cuadrado',
    'Nelson Deossa', 'Yáser Asprilla',
    'Luis Díaz', 'Jhon Durán', 'Luis Javier Suárez',
    'Rafael Carrascal', 'Cucho',
]
colombia_final = players[
    (players['Name'].isin(colombia_squad_search)) &
    (players['Nation'] == 'Colombia')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
colombia_final['team'] = 'Colombia'

# ==============================
# Ecuador
# ==============================
ecuador_squad_search = [
    'Hernán Galíndez', 'Gonzalo Valle',
    'Willian Pacho', 'Piero Hincapié', 'Pervis Estupiñán',
    'Ángelo Preciado', 'Joel Ordoñez', 'Yaimar Medina',
    'Jhoanner Chávez',
    'Moisés Caicedo', 'Kendry Páez', 'Carlos Gruezo',
    'José Cifuentes', 'Janner Corozo', 'John Yeboah',
    'Alan Minda', 'Patrik Mercado', 'Denil Castillo',
    'Nilson Angulo', 'Jeremy Sarmiento', 'Junior Sornoza',
    'Kevin Rodríguez', 'Leonardo Campana', 'Jordy Caicedo',
    'John Mercado', 'Anthony Valencia',
]
ecuador_final = players[
    (players['Name'].isin(ecuador_squad_search)) &
    (players['Nation'] == 'Ecuador')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
ecuador_final['team'] = 'Ecuador'

# ==============================
# Paraguay
# ==============================
paraguay_squad_search = [
    'Roberto Fernández', 'Orlando Gill',
    'Omar Alderete', 'Gustavo Velázquez', 'Saúl Salcedo',
    'Williams Riveros', 'José Canale', 'Juan Escobar',
    'Kaku', 'Miguel Almirón', 'Diego Gómez',
    'Matías Galarza', 'Richard Sánchez', 'Andrés Cubas',
    'Braian Ojeda', 'Gastón Giménez', 'Rodney Redes',
    'Cecilio Domínguez',
    'Antonio Sanabria', 'Julio César Enciso', 'Gabriel Ávalos',
    'Alex Arce', 'Carlos González', 'Derlis González',
    'Lorenzo Melgarejo', 'Matías Rojas',
]
paraguay_final = players[
    (players['Name'].isin(paraguay_squad_search)) &
    (players['Nation'] == 'Paraguay')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
paraguay_final['team'] = 'Paraguay'

# ==============================
# Uruguay
# ==============================
uruguay_squad_search = [
    # Goalkeepers
    'Sergio Rochet', 'Santiago Mele',
    # Defenders
    'José María Giménez', 'Sebastián Cáceres',
    'Santiago Bueno', 'Guillermo Varela', 'Mathías Olivera',
    'Matías Viña', 'Joaquín Piquerez',
    # Midfielders
    'Manuel Ugarte', 'Nicolás De La Cruz', 'Federico Valverde',
    'Facundo Pellistri', 'Nicolás Fonseca',
    'Jorge De Arrascaeta', 'Rodrigo Bentancur', 'Lucas Torreira',
    # Forwards
    'Darwin Núñez', 'Agustín Canobbio', 'Brian Rodríguez',
    'Maximiliano Araújo', 'Facundo Torres', 'Agustín Álvarez',
    'Rodrigo Aguirre',
]
uruguay_final = players[
    (players['Name'].isin(uruguay_squad_search)) &
    (players['Nation'] == 'Uruguay')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
uruguay_final['team'] = 'Uruguay'

missing_uruguay = pd.DataFrame([
    {'Name': 'Sergio Rochet',       'Position': 'GK',  'OVR': 75},
    {'Name': 'Santiago Mele',       'Position': 'GK',  'OVR': 70},
    {'Name': 'Gastón Álvarez',      'Position': 'GK',  'OVR': 68},
    {'Name': 'Ronald Araújo',       'Position': 'CB',  'OVR': 85},
    {'Name': 'Sebastián Cáceres',   'Position': 'CB',  'OVR': 72},
    {'Name': 'Guillermo Varela',    'Position': 'RB',  'OVR': 70},
    {'Name': 'Matías Viña',         'Position': 'LB',  'OVR': 74},
    {'Name': 'Nicolás Fonseca',     'Position': 'CM',  'OVR': 68},
    {'Name': 'Jorge De Arrascaeta', 'Position': 'CAM', 'OVR': 80},
    {'Name': 'Facundo Torres',      'Position': 'LW',  'OVR': 72},
    {'Name': 'Agustín Álvarez',     'Position': 'ST',  'OVR': 70},
    {'Name': 'Rodrigo Aguirre',     'Position': 'ST',  'OVR': 68},
    {'Name': 'Nicolás De La Cruz',  'Position': 'CM',  'OVR': 80},
    {'Name': 'Agustín Canobbio',    'Position': 'LW',  'OVR': 71},
    {'Name': 'Brian Rodríguez',     'Position': 'LW',  'OVR': 72},
    {'Name': 'Joaquín Piquerez',    'Position': 'LB',  'OVR': 74},
])
missing_uruguay['Nation'] = 'Uruguay'
missing_uruguay['team'] = 'Uruguay'

uruguay_final = pd.concat([uruguay_final, missing_uruguay], ignore_index=True)
uruguay_final = uruguay_final.drop_duplicates(subset='Name', keep='first')

# ==============================
# ملخص أمريكا الجنوبية
# ==============================
print("=== ملخص أمريكا الجنوبية ===")
print(f"Argentina: {len(argentina_final)}")
print(f"Brazil: {len(brazil_final)}")
print(f"Colombia: {len(colombia_final)}")
print(f"Ecuador: {len(ecuador_final)}")
print(f"Paraguay: {len(paraguay_final)}")
print(f"Uruguay: {len(uruguay_final)}")

=== ملخص أمريكا الجنوبية ===
Argentina: 26
Brazil: 26
Colombia: 26
Ecuador: 26
Paraguay: 26
Uruguay: 26

In [72]:
# ==============================
# Japan
# ==============================
japan_squad_search = [
    'Zion Suzuki', 'Yohei Takaoka',
    'Yukinari Sugawara', 'Shogo Taniguchi', 'Hiroki Ito',
    'Takuma Ominami', 'Tsuyoshi Watanabe', 'Daiki Hashioka',
    'Ko Itakura', 'Koki Machida',
    'Ayumu Seko', 'Kaoru Mitoma', 'Ritsu Doan',
    'Daichi Kamada', 'Ao Tanaka', 'Joel Chima Fujita',
    'Kaishū Sano', 'Wataru Endo', 'Kodai Sano',
    'Daizen Maeda', 'Keito Nakamura', 'Junya Ito',
    'Ayase Ueda', 'Koki Ogawa', 'Shuto Machino', 'Yuito Suzuki',
]
japan_final = players[
    (players['Name'].isin(japan_squad_search)) &
    (players['Nation'] == 'Japan')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
japan_final['team'] = 'Japan'

# ==============================
# South Korea
# ==============================
korea_squad_search = [
    'Jo Hyeon Woo', 'Song Bum Keun',
    'Kim Min Jae', 'Lee Tae Seok', 'Park Jin Seob',
    'Kim Jin Su', 'Lee Han Beom', 'Yang Hyun Jun',
    'Hwang In Beom', 'Lee Jae Sung', 'Lee Kang In',
    'Jeong Woo Yeong', 'Paik Seung Ho', 'Hong Hyeon Seok',
    'Jens Castrop', 'Bae Jun Ho', 'Kwon Hyeok Kyu',
    'Heung Min Son', 'Hwang Hee Chan', 'Oh Hyeon Gyu',
    'Cho Gue Sung', 'Eom Ji Sung', 'Moon Seon Min',
    'Yang Min Hyeok', 'Kim Moon Hwan',
]
korea_final = players[
    (players['Name'].isin(korea_squad_search)) &
    (players['Nation'] == 'South Korea')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
korea_final['team'] = 'South Korea'

# ==============================
# Australia
# ==============================
australia_squad_search = [
    'Paul Izzo', 'Patrick Beach',
    'Cameron Burgess', 'Alessandro Circati', 'Fran Karačić',
    'Aziz Behich', 'Connor Metcalfe', 'Jordan Bos',
    'Kai Trewin', 'Jacob Italiano', 'Harry Souttar', 'Kye Rowles',
    'Ajdin Hrustić', "Aiden O'Neill", 'Riley McGree',
    'Patrick Yazbek', 'Alex Robertson', 'Jackson Irvine',
    'Massimo Luongo', 'Cameron Devlin', 'Mathew Leckie', 'Craig Goodwin',
    'Martin Boyle', 'Nestory Irankunda', 'Nishan Velupillay', 'Awer Mabil',
]
australia_final = players[
    (players['Name'].isin(australia_squad_search)) &
    (players['Nation'] == 'Australia')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
australia_final['team'] = 'Australia'

# ==============================
# IR Iran
# ==============================
iran_squad_search = [
    'Mehdi Taremi', 'Allahyar Sayyadmanesh',
    'Ali Gholizadeh', 'Amir Abedzadeh',
    'Majid Hosseini', 'Ali Karimi',
]
iran_data = players[
    (players['Name'].isin(iran_squad_search)) &
    (players['Nation'] == 'IR Iran')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
iran_data['team'] = 'IR Iran'
missing_iran = pd.DataFrame([
    {'Name': 'Alireza Beiranvand',        'Position': 'GK', 'OVR': 57},
    {'Name': 'Payam Niazmand',            'Position': 'GK', 'OVR': 57},
    {'Name': 'Shoja Khalilzadeh',         'Position': 'CB', 'OVR': 57},
    {'Name': 'Ali Nemati',                'Position': 'CB', 'OVR': 57},
    {'Name': 'Aria Yousefi',              'Position': 'CB', 'OVR': 57},
    {'Name': 'M. Zare Mohazabieh',        'Position': 'CB', 'OVR': 57},
    {'Name': 'Mohammad Amin Hazbavi',     'Position': 'CB', 'OVR': 57},
    {'Name': 'Omid Noorafkan',            'Position': 'LB', 'OVR': 57},
    {'Name': 'Ramin Rezaeian',            'Position': 'RB', 'OVR': 57},
    {'Name': 'Saeid Ezatolahi',           'Position': 'CM', 'OVR': 57},
    {'Name': 'Alireza Jahanbakhsh',       'Position': 'LM', 'OVR': 57},
    {'Name': 'Mohammad Mohebi',           'Position': 'CM', 'OVR': 57},
    {'Name': 'Saman Ghoddos',            'Position': 'CM', 'OVR': 57},
    {'Name': 'Mohammad Ghorbani',         'Position': 'CM', 'OVR': 57},
    {'Name': 'Mohammad Hosseininejad',    'Position': 'CM', 'OVR': 57},
    {'Name': 'Danial Esmaeilifar',        'Position': 'CM', 'OVR': 57},
    {'Name': 'Mohammad Khodabandehloo',   'Position': 'CM', 'OVR': 57},
    {'Name': 'Amirhossein Hosseininejad', 'Position': 'ST', 'OVR': 57},
    {'Name': 'Ali Alipour',               'Position': 'ST', 'OVR': 57},
    {'Name': 'K. Taheri',                 'Position': 'ST', 'OVR': 57},
])
missing_iran['Nation'] = 'IR Iran'
missing_iran['team'] = 'IR Iran'
iran_final = pd.concat([iran_data, missing_iran], ignore_index=True)
iran_final = iran_final.drop_duplicates(subset='Name', keep='first')

# ==============================
# Jordan
# ==============================
jordan_squad_search = ['Musa Al Tamari', 'Yazan Al Arab']
jordan_data = players[
    (players['Name'].isin(jordan_squad_search)) &
    (players['Nation'] == 'Jordan')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
jordan_data['team'] = 'Jordan'
missing_jordan = pd.DataFrame([
    {'Name': 'Yazeed Abu Laila',    'Position': 'GK', 'OVR': 57},
    {'Name': 'M. Shalabiya',        'Position': 'GK', 'OVR': 57},
    {'Name': 'Nour Bani Atiyeh',    'Position': 'GK', 'OVR': 57},
    {'Name': 'M. Hasheesh',         'Position': 'RB', 'OVR': 57},
    {'Name': 'A. Nasib',            'Position': 'CB', 'OVR': 57},
    {'Name': 'Salim Obeid',         'Position': 'CB', 'OVR': 57},
    {'Name': 'Hadi Al Hawrani',     'Position': 'CB', 'OVR': 57},
    {'Name': 'Youssef Abu Jazar',   'Position': 'LB', 'OVR': 57},
    {'Name': 'Mohammad Abu Al Nadi','Position': 'CB', 'OVR': 57},
    {'Name': 'I. Smeeri',           'Position': 'CB', 'OVR': 57},
    {'Name': 'A. Hajabi',           'Position': 'CB', 'OVR': 57},
    {'Name': 'Nour Al Rawabdeh',    'Position': 'CM', 'OVR': 57},
    {'Name': 'Mahmoud Mardawi',     'Position': 'CM', 'OVR': 57},
    {'Name': 'I. Sami',             'Position': 'CM', 'OVR': 57},
    {'Name': 'A. Al-Salman',        'Position': 'CM', 'OVR': 57},
    {'Name': 'Mohannad Abu Taha',   'Position': 'CM', 'OVR': 57},
    {'Name': 'Nizar Al Rashdan',    'Position': 'CM', 'OVR': 57},
    {'Name': 'Adham Al Qurashi',    'Position': 'CM', 'OVR': 57},
    {'Name': 'Amer Jaamous',        'Position': 'CM', 'OVR': 57},
    {'Name': 'Mohammad Abu Zreiq',  'Position': 'ST', 'OVR': 57},
    {'Name': 'Ali Olwan',           'Position': 'ST', 'OVR': 57},
    {'Name': 'Ibrahim Sabra',       'Position': 'ST', 'OVR': 57},
    {'Name': 'Saad Al Rousan',      'Position': 'RB', 'OVR': 57},
    {'Name': 'Rizq Bani Hani',      'Position': 'ST', 'OVR': 57},
])
missing_jordan['Nation'] = 'Jordan'
missing_jordan['team'] = 'Jordan'
jordan_final = pd.concat([jordan_data, missing_jordan], ignore_index=True)

# ==============================
# Iraq
# ==============================
iraq_squad_search = [
    'Ali Adnan', 'Ibrahim Bayesh', 'Mohanad Jeahze',
    'Merchas Doski', 'Zidane Iqbal', 'Aimar Sher',
    'Kevin Yakob', 'Marko Farji', 'Montader Madjed',
    'Ali Al Hamadi', 'Amir Al-Ammari', 'Danilo Al Saed',
    'Ali Jasim', 'Mohamed Al-Taay', 'Amin Al-Hamawi',
]
iraq_data = players[
    (players['Name'].isin(iraq_squad_search)) &
    (players['Nation'] == 'Iraq')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
iraq_data['team'] = 'Iraq'
missing_iraq = pd.DataFrame([
    {'Name': 'Fahad Talib',         'Position': 'GK', 'OVR': 57},
    {'Name': 'K. Al-Rekabe',        'Position': 'GK', 'OVR': 57},
    {'Name': 'Ahmed Basel',         'Position': 'GK', 'OVR': 57},
    {'Name': 'Rebin Sulaka',        'Position': 'RB', 'OVR': 57},
    {'Name': 'Hussein Ali',         'Position': 'CB', 'OVR': 57},
    {'Name': 'Zaid Tahseen',        'Position': 'CB', 'OVR': 57},
    {'Name': 'Akam Hashim',         'Position': 'CB', 'OVR': 57},
    {'Name': 'Manaf Younis',        'Position': 'CB', 'OVR': 57},
    {'Name': 'Youssef Amyn',        'Position': 'CM', 'OVR': 57},
    {'Name': 'Aymen Hussein',       'Position': 'ST', 'OVR': 57},
    {'Name': 'Mohanad Ali Kadhim',  'Position': 'ST', 'OVR': 57},
])
missing_iraq['Nation'] = 'Iraq'
missing_iraq['team'] = 'Iraq'
iraq_final = pd.concat([iraq_data, missing_iraq], ignore_index=True)

# ==============================
# Uzbekistan
# ==============================
uzbekistan_squad_search = [
    'Abdukodir Khusanov', 'Eldor Shomurodov',
    'Khusniddin Alikulov', 'Mukhammadali Urinboev',
]
uzbekistan_data = players[
    (players['Name'].isin(uzbekistan_squad_search)) &
    (players['Nation'] == 'Uzbekistan')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
uzbekistan_data['team'] = 'Uzbekistan'
missing_uzbekistan = pd.DataFrame([
    {'Name': 'Abdulvohid Nematov',       'Position': 'GK',  'OVR': 57},
    {'Name': 'Utkir Yusupov',            'Position': 'GK',  'OVR': 57},
    {'Name': 'Bunyodbek Ergashev',       'Position': 'GK',  'OVR': 57},
    {'Name': 'K. Alidzhanov',            'Position': 'CB',  'OVR': 57},
    {'Name': 'Farrukh Sayfiev',          'Position': 'CB',  'OVR': 57},
    {'Name': 'Rustamjon Ashurmatov',     'Position': 'CB',  'OVR': 57},
    {'Name': 'Jurab Jaloliddinov',       'Position': 'CB',  'OVR': 57},
    {'Name': 'S. Nasrulloev',            'Position': 'CB',  'OVR': 57},
    {'Name': 'Oybek Ashmorodov',         'Position': 'LB',  'OVR': 57},
    {'Name': 'Abdulloh Abdulloyev',      'Position': 'RB',  'OVR': 57},
    {'Name': 'Zafarmurod Abdurakhmatov', 'Position': 'CB',  'OVR': 57},
    {'Name': 'I. Tuhtahujaev',           'Position': 'CM',  'OVR': 57},
    {'Name': 'Ibrohimhalil Yuldoshev',   'Position': 'RB',  'OVR': 57},
    {'Name': 'Azizbek Jangiev',          'Position': 'CM',  'OVR': 57},
    {'Name': 'Akmal Mirzayev',           'Position': 'CM',  'OVR': 57},
    {'Name': 'Khozhimat Erkinov',        'Position': 'CM',  'OVR': 57},
    {'Name': 'A. Fayzullayev',           'Position': 'CM',  'OVR': 57},
    {'Name': 'Otabek Shukurov',          'Position': 'CM',  'OVR': 57},
    {'Name': 'Jamshid Iskandarov',       'Position': 'CM',  'OVR': 57},
    {'Name': 'O. Khamrobekov',           'Position': 'CM',  'OVR': 57},
    {'Name': 'Jaloliddin Masharipov',    'Position': 'CAM', 'OVR': 57},
    {'Name': 'Abdurauf Buriev',          'Position': 'CM',  'OVR': 57},
])
missing_uzbekistan['Nation'] = 'Uzbekistan'
missing_uzbekistan['team'] = 'Uzbekistan'
uzbekistan_final = pd.concat([uzbekistan_data, missing_uzbekistan], ignore_index=True)

# ==============================
# Saudi Arabia
# ==============================
saudi_squad_search = [
    'Nawaf Al Aqidi', 'Ahmed Al Kassar',
    'Saud Abdulhamid', 'Hassan Tombakti', 'Ali Al Bulayhi',
    'Ali Lajami', 'Nawaf Boushal', 'Hassan Kadish',
    'Ali Majrashi', 'Abdulelah Al Amri', 'Rayan Hamed',
    'Salem Al Dawsari', 'Musab Al Juwair', 'Mohammed Kanno',
    'Abdullah Al Khaibari', 'Ziyad Al Johani', 'Turki Al Ammar',
    'Naif Masoud', 'Salman Al Faraj', 'Mohammed Al Buraik',
    'Firas Al Birekan', 'Saleh Al Shehri', 'Marwan Al Sahafi',
    'Sultan Al Ghannam', 'Abdullah Al Hamdan', 'Sultan Mandash',
]
saudi_final = players[
    (players['Name'].isin(saudi_squad_search)) &
    (players['Nation'] == 'Saudi Arabia')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
saudi_final['team'] = 'Saudi Arabia'

# ==============================
# Qatar
# ==============================
qatar_final = pd.DataFrame([
    {'Name': 'Salah Zakaria',      'Position': 'GK',  'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
    {'Name': 'Shehab Al Lithi',    'Position': 'GK',  'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
    {'Name': 'Meshaal Barsham',    'Position': 'GK',  'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
    {'Name': 'Pedro Miguel',       'Position': 'LB',  'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
    {'Name': 'Lucas',              'Position': 'CB',  'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
    {'Name': 'Bassam Al Rawi',     'Position': 'CB',  'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
    {'Name': 'Tariq Salman',       'Position': 'CB',  'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
    {'Name': 'Hamam Al Amin',      'Position': 'CB',  'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
    {'Name': 'Boualem Khoukhi',    'Position': 'CB',  'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
    {'Name': 'Sultan Al Braik',    'Position': 'RB',  'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
    {'Name': 'Ahmed Hamawiyandi',  'Position': 'CB',  'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
    {'Name': 'Jasim Jaber',        'Position': 'CB',  'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
    {'Name': 'Mohammed Waad',      'Position': 'CM',  'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
    {'Name': 'Abdullah Abdulaziz', 'Position': 'CM',  'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
    {'Name': 'Mohammed Muntari',   'Position': 'CM',  'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
    {'Name': 'Boudaoui Karim',     'Position': 'CM',  'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
    {'Name': 'Assim Madibo',       'Position': 'CDM', 'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
    {'Name': 'Ahmed Al Rawi',      'Position': 'CM',  'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
    {'Name': 'Guilherme',          'Position': 'CM',  'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
    {'Name': 'Akram Afif',         'Position': 'LW',  'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
    {'Name': 'Almoez Ali',         'Position': 'ST',  'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
    {'Name': 'Hassan Al Haydos',   'Position': 'CAM', 'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
    {'Name': 'Ahmed Alaaeldin',    'Position': 'ST',  'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
    {'Name': 'Ahmed Al Janahi',    'Position': 'ST',  'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
    {'Name': 'Ismail Mohammed',    'Position': 'ST',  'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
    {'Name': 'Edmilson Junior',    'Position': 'ST',  'OVR': 57, 'Nation': 'Qatar', 'team': 'Qatar'},
])

# ==============================
# New Zealand
# ==============================
new_zealand_squad_search = [
    'Max Crocombe', 'Alex Paulsen', 'Oliver Sail',
    'Bill Tuiloma', 'James McGarry', 'Tim Payne',
    'Ben Old', 'Finn Surman', 'Tyler Bindon',
    'Francis de Vries', 'Nando Pijnaker', 'Liberato Cacace',
    'Ryan Thomas', 'Alex Rufer', 'Callum McCowatt',
    'Joe Bell', 'Marko Stamenić', 'Lachlan Bayliss', 'Matthew Garbett',
    'Kosta Barbarouses', 'Elijah Just', 'Ben Waine',
    'Jesse Randall', 'Logan Rogerson', 'Chris Wood', 'Callan Elliot',
]
new_zealand_final = players[
    (players['Name'].isin(new_zealand_squad_search)) &
    (players['Nation'] == 'New Zealand')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
new_zealand_final['team'] = 'New Zealand'

# ==============================
# ملخص
# ==============================
print("=== ملخص آسيا + أوقيانوسيا ===")
print(f"Japan: {len(japan_final)}")
print(f"South Korea: {len(korea_final)}")
print(f"Australia: {len(australia_final)}")
print(f"IR Iran: {len(iran_final)}")
print(f"Jordan: {len(jordan_final)}")
print(f"Iraq: {len(iraq_final)}")
print(f"Uzbekistan: {len(uzbekistan_final)}")
print(f"Saudi Arabia: {len(saudi_final)}")
print(f"Qatar: {len(qatar_final)}")
print(f"New Zealand: {len(new_zealand_final)}")

=== ملخص آسيا + أوقيانوسيا ===
Japan: 26
South Korea: 26
Australia: 26
IR Iran: 26
Jordan: 26
Iraq: 26
Uzbekistan: 26
Saudi Arabia: 26
Qatar: 26
New Zealand: 26

In [73]:
# ==============================
# USA
# ==============================
usa_squad_search = [
    'Matt Turner', 'Matt Freese', 'Roman Celentano', 'Patrick Schulte',
    'Antonee Robinson', 'Chris Richards', 'Tim Ream',
    'Joe Scally', 'Mark McKenzie', 'Miles Robinson',
    'Auston Trusty', 'Alex Freeman',
    'Christian Pulisic', 'Weston McKennie', 'Giovanni Reyna',
    'Brenden Aaronson', 'Sebastian Berhalter', 'Malik Tillman',
    'Johnny Cardoso', 'Aidan Morris', 'Cristian Roldan', 'Tanner Tessmann',
    'Ricardo Pepi', 'Folarin Balogun', 'Timothy Weah', 'Patrick Agyemang',
]
usa_final = players[
    (players['Name'].isin(usa_squad_search)) &
    (players['Nation'] == 'USA')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
usa_final['team'] = 'USA'

# ==============================
# Mexico
# ==============================
mexico_squad_search = [
    'Álex Padilla', 'Pablo Sisniega', 'David Ochoa', 'Abraham Romero',
    'Johan Vásquez', 'Julian Araujo', 'Rodrigo Huescas',
    'Mateo Chávez', 'Jonathan Germán Gómez', 'Alán Montes',
    'Edson Álvarez', 'Orbelín Pineda', 'Obed Vargas',
    'Daniel Aguilar', 'Heriberto Jurado', 'Érik Dueñas', 'César Garza',
    'Julian Quiñones', 'Santiago Giménez', 'Hirving Lozano',
    'Raúl Jiménez', 'César Huerta', 'Luca Martínez Dupuy',
    'Santiago Muñoz', 'Daniel Ríos', 'Anthony Ramírez',
]
mexico_final = players[
    (players['Name'].isin(mexico_squad_search)) &
    (players['Nation'] == 'Mexico')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
mexico_final['team'] = 'Mexico'

# ==============================
# Canada
# ==============================
canada_squad_search = [
    'Dayne St. Clair', 'Maxime Crépeau', 'Jonathan Sirois',
    'Alistair Johnston', 'Kamal Miller', 'Joel Waterman',
    'Derek Cornelius', 'Moïse Bombito', 'Niko Sigur',
    'Luc De Fougerolles', 'Jahkeele Marshall-Rutty',
    'Mathieu Choinière', 'Ismaël Koné', 'Tajon Buchanan',
    'Ali Ahmed', 'Richie Laryea', 'Jonathan Osorio',
    'Liam Millar', 'Nathan-Dylan Saliba', 'Ralph Priso',
    'Jonathan David', 'Cyle Larin', 'Tani Oluwaseyi',
    'Junior Hoilett', 'Daniel Jebbison', 'Jacen Russell-Rowe',
]
canada_final = players[
    (players['Name'].isin(canada_squad_search)) &
    (players['Nation'] == 'Canada')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
canada_final['team'] = 'Canada'

# ==============================
# Panama
# ==============================
panama_squad_search = [
    'Amir Murillo', 'Luis Mejía', 'Orlando Mosquera',
    'Eduardo Guerrero', 'Aníbal Godoy', 'Andrés Andrade',
    'José Fajardo', 'José Córdoba', 'Carlos Harvey',
    'Leslie Heráldez', 'Omar Valencia',
]
panama_data = players[
    (players['Name'].isin(panama_squad_search)) &
    (players['Nation'] == 'Panama')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
panama_data['team'] = 'Panama'
missing_panama = pd.DataFrame([
    {'Name': 'César Blackman',         'Position': 'CB',  'OVR': 57},
    {'Name': 'Fidel Escobar',          'Position': 'CB',  'OVR': 57},
    {'Name': 'Edgar Fariña',           'Position': 'CB',  'OVR': 57},
    {'Name': 'Michael Murillo',        'Position': 'RB',  'OVR': 57},
    {'Name': 'Eric Davis',             'Position': 'CB',  'OVR': 57},
    {'Name': 'Giovanni Walsh',         'Position': 'CM',  'OVR': 57},
    {'Name': 'Cristian Martínez',      'Position': 'CM',  'OVR': 57},
    {'Name': 'Adalberto Carrasquilla', 'Position': 'CM',  'OVR': 57},
    {'Name': 'José Luis Rodríguez',    'Position': 'CM',  'OVR': 57},
    {'Name': 'Ismael Díaz',            'Position': 'ST',  'OVR': 57},
    {'Name': 'Joel Barcenas',          'Position': 'LM',  'OVR': 57},
    {'Name': 'Cecilio Waterman',       'Position': 'ST',  'OVR': 57},
    {'Name': 'César Samudio',          'Position': 'GK',  'OVR': 57},
    {'Name': 'Richard Peralta',        'Position': 'CB',  'OVR': 57},
    {'Name': 'Kevin Galvan',           'Position': 'CB',  'OVR': 57},
])
missing_panama['Nation'] = 'Panama'
missing_panama['team'] = 'Panama'
panama_final = pd.concat([panama_data, missing_panama], ignore_index=True)

# ==============================
# Curaçao
# ==============================
curacao_squad_search = [
    'Tahith Chong', 'Juninho Bacuna', 'Daijiro Chirino',
    'Shurandy Sambo', 'Brandley Kuwas', 'Sherel Floranus',
    "Ar'jany Martha", 'Tyrique Mercera', 'Livano Comenencia',
    'Rayvien Rosario', 'Isaiah Ahmed', 'Giandro Sambo',
]
curacao_data = players[
    (players['Name'].isin(curacao_squad_search)) &
    (players['Nation'] == 'Curaçao')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
curacao_data['team'] = 'Curaçao'
missing_curacao = pd.DataFrame([
    {'Name': 'Eloy Room',          'Position': 'GK', 'OVR': 57},
    {'Name': 'T. Bodak',           'Position': 'GK', 'OVR': 57},
    {'Name': 'Trevor Doornbusch',  'Position': 'GK', 'OVR': 57},
    {'Name': 'Rochon van Eijma',   'Position': 'CB', 'OVR': 57},
    {'Name': 'Armando Obispo',     'Position': 'CB', 'OVR': 57},
    {'Name': 'Joshua Brenet',      'Position': 'RB', 'OVR': 57},
    {'Name': 'Richairo Zivkovic',  'Position': 'RB', 'OVR': 57},
    {'Name': 'D. Fonville',        'Position': 'CB', 'OVR': 57},
    {'Name': 'T. Noslin',          'Position': 'CB', 'OVR': 57},
    {'Name': 'Godfrid Roemeratoe', 'Position': 'CM', 'OVR': 57},
    {'Name': 'Leandro Bacuna',     'Position': 'CM', 'OVR': 57},
    {'Name': 'J. Antonisse',       'Position': 'CM', 'OVR': 57},
    {'Name': 'J. Gaari',           'Position': 'CM', 'OVR': 57},
    {'Name': 'Kevin Felida',       'Position': 'CM', 'OVR': 57},
])
missing_curacao['Nation'] = 'Curaçao'
missing_curacao['team'] = 'Curaçao'
curacao_final = pd.concat([curacao_data, missing_curacao], ignore_index=True)

# ==============================
# Haiti
# ==============================
haiti_squad_search = [
    'Frantzdy Pierrot', 'Carlens Arcus', 'Jean-Kévin Duverne',
    'Danley Jean Jacques', 'Johny Placide', 'Fafà Picault',
    'Derrick Etienne Jr.', 'Don Deedson Louicius', 'Martin Expérience',
    'Aleksandr Guboglo', 'Joseph Belmar', 'Wilguens Paugain',
]
haiti_data = players[
    (players['Name'].isin(haiti_squad_search)) &
    (players['Nation'] == 'Haiti')
][['Name', 'Nation', 'Position', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']]
haiti_data['team'] = 'Haiti'
missing_haiti = pd.DataFrame([
    {'Name': 'Alexandre Pierre',  'Position': 'GK', 'OVR': 57},
    {'Name': 'Josue Duverger',    'Position': 'GK', 'OVR': 57},
    {'Name': 'Ricardo Ade',       'Position': 'CB', 'OVR': 57},
    {'Name': 'Duke Lacroix',      'Position': 'CB', 'OVR': 57},
    {'Name': 'Hannes Delcroix',   'Position': 'CB', 'OVR': 57},
    {'Name': 'Stephan Lambese',   'Position': 'LB', 'OVR': 57},
    {'Name': 'Leverton Pierre',   'Position': 'CM', 'OVR': 57},
    {'Name': 'Ruben Providence',  'Position': 'CM', 'OVR': 57},
    {'Name': 'Christopher Attys', 'Position': 'CM', 'OVR': 57},
    {'Name': 'Jean Pellegarde',   'Position': 'CM', 'OVR': 57},
    {'Name': 'Carl-Fred Sainte',  'Position': 'CM', 'OVR': 57},
    {'Name': 'Dackens Nason',     'Position': 'ST', 'OVR': 57},
    {'Name': 'Jose Casimir',      'Position': 'ST', 'OVR': 57},
    {'Name': 'Mikael Cantave',    'Position': 'LM', 'OVR': 57},
])
missing_haiti['Nation'] = 'Haiti'
missing_haiti['team'] = 'Haiti'
haiti_final = pd.concat([haiti_data, missing_haiti], ignore_index=True)

# ==============================
# ملخص
# ==============================
print("=== ملخص أمريكا الشمالية ===")
print(f"USA: {len(usa_final)}")
print(f"Mexico: {len(mexico_final)}")
print(f"Canada: {len(canada_final)}")
print(f"Panama: {len(panama_final)}")
print(f"Curaçao: {len(curacao_final)}")
print(f"Haiti: {len(haiti_final)}")

=== ملخص أمريكا الشمالية ===
USA: 26
Mexico: 26
Canada: 26
Panama: 26
Curaçao: 26
Haiti: 26

In [74]:
# ==============================
# دمج كل المنتخبات
# ==============================
all_squads = pd.concat([
    # أفريقيا
    morocco_data, senegal_final, egypt_final, algeria_final,
    tunisia_final, ghana_final, ivory_final, sa_final,
    cabo_final, dr_congo_final,
    # أمريكا الجنوبية
    argentina_final, brazil_final, colombia_final, ecuador_final,
    paraguay_final, uruguay_final,
    # أوروبا
    england_data, france_data, spain_data, portugal_data,
    germany_data, netherlands_data, belgium_data, croatia_data,
    switzerland_data, norway_data, scotland_data, austria_data,
    bosnia_final, sweden_final, turkey_final, czech_final,
    # آسيا
    japan_final, korea_final, iran_final, uzbekistan_final,
    jordan_final, saudi_final, qatar_final, iraq_final,
    # أمريكا الشمالية
    usa_final, mexico_final, canada_final, panama_final,
    curacao_final, haiti_final,
    # أوقيانوسيا
    new_zealand_final, australia_final,
], ignore_index=True)

print(f"إجمالي اللاعبين: {len(all_squads)}")
print(f"عدد المنتخبات: {all_squads['team'].nunique()}")
print(all_squads['team'].value_counts())

# حفظ كـ CSV
all_squads.to_csv('data/clean/all_squads.csv', index=False)
print("\nتم الحفظ في data/clean/all_squads.csv ✅")

إجمالي اللاعبين: 1247
عدد المنتخبات: 48
team
Morocco                   26
Senegal                   26
Scotland                  26
Austria                   26
Bosnia and Herzegovina    26
Sweden                    26
Turkey                    26
Czech Republic            26
Japan                     26
South Korea               26
IR Iran                   26
Uzbekistan                26
Jordan                    26
Saudi Arabia              26
Qatar                     26
Iraq                      26
USA                       26
Mexico                    26
Canada                    26
Panama                    26
Curaçao                   26
Haiti                     26
New Zealand               26
Norway                    26
Switzerland               26
Croatia                   26
Brazil                    26
Egypt                     26
Algeria                   26
Tunisia                   26
Ghana                     26
Ivory Coast               26
South Africa              26
Cape Verde                26
DR Congo                  26
Argentina                 26
Colombia                  26
Belgium                   26
Ecuador                   26
Paraguay                  26
Uruguay                   26
France                    26
Spain                     26
Portugal                  26
Germany                   26
Netherlands               26
Australia                 26
England                   25
Name: count, dtype: int64

تم الحفظ في data/clean/all_squads.csv ✅

In [75]:
print(england_data[['Name', 'Position', 'OVR']].sort_values('OVR', ascending=False).to_string(index=False))
print(f"\nعدد لاعبي إنجلترا: {len(england_data)}")

                  Name Position  OVR
       Jude Bellingham      CAM   90
            Harry Kane       ST   89
           Bukayo Saka       RW   88
           Cole Palmer      CAM   87
           Declan Rice      CDM   87
Trent Alexander-Arnold       RB   86
            Phil Foden       RW   85
       Jordan Pickford       GK   84
         Ollie Watkins       ST   84
        James Maddison       CM   84
        Benjamin White       RB   83
          Jarrod Bowen       RM   83
          Eberechi Eze      CAM   83
        Anthony Gordon       LW   83
         Morgan Rogers      CAM   82
    Morgan Gibbs-White      CAM   82
            Ezri Konsa       CB   82
           John Stones       CB   82
            Marc Guéhi       CB   82
       Conor Gallagher       CM   81
        Dean Henderson       GK   81
             Nick Pope       GK   81
          Levi Colwill       CB   80
          Jadon Sancho       LW   80
         Harry Maguire       CB   80

عدد لاعبي إنجلترا: 25

In [76]:
# نملأ الـ NaN قبل حساب المتوسطات
all_squads[['PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']] = all_squads[['PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']].fillna(57)

team_ratings = all_squads.groupby('team').agg(
    avg_ovr=('OVR', 'mean'),
    avg_pac=('PAC', 'mean'),
    avg_sho=('SHO', 'mean'),
    avg_pas=('PAS', 'mean'),
    avg_dri=('DRI', 'mean'),
    avg_def=('DEF', 'mean'),
    avg_phy=('PHY', 'mean'),
).reset_index()

print(team_ratings.sort_values('avg_ovr', ascending=False))

                      team    avg_ovr    avg_pac    avg_sho    avg_pas  \
16                 England  83.560000  74.120000  71.920000  78.800000
17                  France  83.500000  81.769231  68.884615  75.269231
40                   Spain  82.307692  74.000000  71.653846  77.692308
18                 Germany  82.192308  75.730769  69.846154  76.230769
6                   Brazil  81.615385  78.115385  70.500000  74.076923
28             Netherlands  81.538462  76.461538  66.923077  73.461538
1                Argentina  80.423077  74.461538  69.461538  75.307692
33                Portugal  80.346154  78.153846  71.076923  75.269231
4                  Belgium  79.500000  71.615385  67.500000  73.269231
10                 Croatia  77.576923  69.769231  65.769231  69.461538
27                 Morocco  76.807692  75.076923  68.423077  70.230769
3                  Austria  76.538462  71.807692  62.615385  70.576923
44                  Turkey  76.500000  73.923077  63.230769  69.615385
42             Switzerland  76.461538  73.576923  63.846154  69.461538
9                 Colombia  76.346154  76.500000  67.230769  70.807692
30                  Norway  76.000000  73.961538  66.230769  69.500000
46                 Uruguay  75.692308  63.961538  59.653846  62.384615
23             Ivory Coast  75.192308  75.153846  59.538462  66.615385
12          Czech Republic  74.576923  71.076923  65.115385  67.500000
45                     USA  74.500000  74.346154  60.961538  66.423077
24                   Japan  74.500000  74.307692  61.307692  66.076923
36                Scotland  73.846154  70.730769  62.461538  66.846154
41                  Sweden  73.807692  73.730769  62.230769  66.923077
19                   Ghana  73.576923  72.423077  58.269231  63.038462
0                  Algeria  73.230769  69.846154  66.153846  68.846154
32                Paraguay  72.692308  70.000000  62.846154  63.692308
14                 Ecuador  72.500000  76.769231  59.346154  63.538462
39             South Korea  71.807692  75.192308  60.692308  64.115385
13                DR Congo  71.576923  72.923077  59.846154  63.230769
37                 Senegal  71.500000  71.461538  64.153846  65.769231
5   Bosnia and Herzegovina  70.923077  65.269231  57.653846  60.076923
7                   Canada  69.923077  72.884615  59.615385  61.153846
2                Australia  69.307692  71.384615  56.769231  62.423077
35            Saudi Arabia  69.115385  71.961538  53.307692  61.000000
26                  Mexico  68.653846  71.115385  58.269231  61.500000
43                 Tunisia  68.000000  68.384615  58.500000  62.730769
29             New Zealand  66.961538  69.576923  58.884615  60.846154
22                    Iraq  62.115385  66.192308  58.192308  58.615385
38            South Africa  62.000000  66.884615  54.500000  56.923077
31                  Panama  61.769231  61.461538  56.000000  59.307692
15                   Egypt  61.000000  60.269231  58.961538  59.038462
20                   Haiti  60.884615  63.769231  54.730769  57.384615
11                 Curaçao  60.500000  64.846154  54.153846  57.846154
21                 IR Iran  60.230769  59.692308  58.076923  58.500000
47              Uzbekistan  59.076923  59.269231  56.346154  57.192308
25                  Jordan  58.384615  59.076923  56.384615  56.961538
8               Cape Verde  57.000000  57.000000  57.000000  57.000000
34                   Qatar  57.000000  57.000000  57.000000  57.000000

      avg_dri    avg_def    avg_phy
16  81.280000  64.120000  74.880000
17  81.038462  62.730769  76.346154
40  79.884615  61.692308  71.307692
18  79.115385  61.461538  75.384615
6   78.807692  60.961538  74.846154
28  77.961538  66.461538  76.269231
1   79.230769  63.038462  73.346154
33  79.461538  56.038462  72.500000
4   76.653846  59.384615  74.038462
10  74.576923  62.461538  74.461538
27  76.153846  51.384615  69.115385
3   73.807692  63.730769  72.230769
44  74.000000  59.730769  71.730769
42  73.730769  64.230769  74.653846
9   74.076923  59.730769  73.269231
30  73.846154  56.192308  73.576923
46  64.000000  61.692308  64.692308
23  72.923077  57.461538  70.000000
12  70.807692  53.461538  74.923077
45  71.846154  57.692308  73.769231
24  71.423077  60.192308  71.538462
36  71.038462  61.692308  73.307692
41  71.192308  57.653846  71.230769
19  69.961538  58.269231  72.038462
0   74.500000  56.500000  66.423077
32  69.961538  55.153846  68.884615
14  70.500000  52.884615  67.730769
39  70.692308  51.115385  68.961538
13  69.653846  55.423077  72.230769
37  69.846154  57.538462  68.115385
5   65.846154  51.423077  71.961538
7   67.730769  53.269231  68.576923
2   66.384615  59.307692  70.923077
35  65.192308  56.884615  69.576923
26  67.884615  49.461538  64.538462
43  67.115385  55.769231  66.692308
29  64.923077  54.423077  70.692308
22  62.692308  50.807692  61.538462
38  60.846154  54.653846  60.692308
31  60.692308  55.500000  61.769231
15  59.846154  55.923077  60.307692
20  60.076923  53.884615  60.615385
11  61.000000  55.153846  59.653846
21  59.538462  55.115385  60.192308
47  58.000000  56.576923  58.346154
25  57.692308  56.884615  58.230769
8   57.000000  57.000000  57.000000
34  57.000000  57.000000  57.000000

In [77]:
# نملأ الـ NaN بـ 57
team_ratings = team_ratings.fillna(57)

# نتأكد من Jordan
print(all_squads[all_squads['team'] == 'Jordan'][['Name', 'OVR', 'PAC', 'SHO']].to_string())

                     Name  OVR   PAC   SHO
935        Musa Al Tamari   75  89.0  69.0
936         Yazan Al Arab   75  79.0  29.0
937      Yazeed Abu Laila   57  57.0  57.0
938          M. Shalabiya   57  57.0  57.0
939      Nour Bani Atiyeh   57  57.0  57.0
940           M. Hasheesh   57  57.0  57.0
941              A. Nasib   57  57.0  57.0
942           Salim Obeid   57  57.0  57.0
943       Hadi Al Hawrani   57  57.0  57.0
944     Youssef Abu Jazar   57  57.0  57.0
945  Mohammad Abu Al Nadi   57  57.0  57.0
946             I. Smeeri   57  57.0  57.0
947             A. Hajabi   57  57.0  57.0
948      Nour Al Rawabdeh   57  57.0  57.0
949       Mahmoud Mardawi   57  57.0  57.0
950               I. Sami   57  57.0  57.0
951          A. Al-Salman   57  57.0  57.0
952     Mohannad Abu Taha   57  57.0  57.0
953      Nizar Al Rashdan   57  57.0  57.0
954      Adham Al Qurashi   57  57.0  57.0
955          Amer Jaamous   57  57.0  57.0
956    Mohammad Abu Zreiq   57  57.0  57.0
957             Ali Olwan   57  57.0  57.0
958         Ibrahim Sabra   57  57.0  57.0
959        Saad Al Rousan   57  57.0  57.0
960        Rizq Bani Hani   57  57.0  57.0

In [78]:
# نملأ الـ NaN في PAC, SHO, PAS, DRI, DEF, PHY بـ 57 قبل حساب المتوسطات
all_squads[['PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']] = all_squads[['PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']].fillna(57)

# إعادة حساب المتوسطات
team_ratings = all_squads.groupby('team').agg(
    avg_ovr=('OVR', 'mean'),
    avg_pac=('PAC', 'mean'),
    avg_sho=('SHO', 'mean'),
    avg_pas=('PAS', 'mean'),
    avg_dri=('DRI', 'mean'),
    avg_def=('DEF', 'mean'),
    avg_phy=('PHY', 'mean'),
).reset_index()

print(team_ratings.sort_values('avg_ovr', ascending=False).to_string())

                      team    avg_ovr    avg_pac    avg_sho    avg_pas    avg_dri    avg_def    avg_phy
16                 England  83.560000  74.120000  71.920000  78.800000  81.280000  64.120000  74.880000
17                  France  83.500000  81.769231  68.884615  75.269231  81.038462  62.730769  76.346154
40                   Spain  82.307692  74.000000  71.653846  77.692308  79.884615  61.692308  71.307692
18                 Germany  82.192308  75.730769  69.846154  76.230769  79.115385  61.461538  75.384615
6                   Brazil  81.615385  78.115385  70.500000  74.076923  78.807692  60.961538  74.846154
28             Netherlands  81.538462  76.461538  66.923077  73.461538  77.961538  66.461538  76.269231
1                Argentina  80.423077  74.461538  69.461538  75.307692  79.230769  63.038462  73.346154
33                Portugal  80.346154  78.153846  71.076923  75.269231  79.461538  56.038462  72.500000
4                  Belgium  79.500000  71.615385  67.500000  73.269231  76.653846  59.384615  74.038462
10                 Croatia  77.576923  69.769231  65.769231  69.461538  74.576923  62.461538  74.461538
27                 Morocco  76.807692  75.076923  68.423077  70.230769  76.153846  51.384615  69.115385
3                  Austria  76.538462  71.807692  62.615385  70.576923  73.807692  63.730769  72.230769
44                  Turkey  76.500000  73.923077  63.230769  69.615385  74.000000  59.730769  71.730769
42             Switzerland  76.461538  73.576923  63.846154  69.461538  73.730769  64.230769  74.653846
9                 Colombia  76.346154  76.500000  67.230769  70.807692  74.076923  59.730769  73.269231
30                  Norway  76.000000  73.961538  66.230769  69.500000  73.846154  56.192308  73.576923
46                 Uruguay  75.692308  63.961538  59.653846  62.384615  64.000000  61.692308  64.692308
23             Ivory Coast  75.192308  75.153846  59.538462  66.615385  72.923077  57.461538  70.000000
12          Czech Republic  74.576923  71.076923  65.115385  67.500000  70.807692  53.461538  74.923077
45                     USA  74.500000  74.346154  60.961538  66.423077  71.846154  57.692308  73.769231
24                   Japan  74.500000  74.307692  61.307692  66.076923  71.423077  60.192308  71.538462
36                Scotland  73.846154  70.730769  62.461538  66.846154  71.038462  61.692308  73.307692
41                  Sweden  73.807692  73.730769  62.230769  66.923077  71.192308  57.653846  71.230769
19                   Ghana  73.576923  72.423077  58.269231  63.038462  69.961538  58.269231  72.038462
0                  Algeria  73.230769  69.846154  66.153846  68.846154  74.500000  56.500000  66.423077
32                Paraguay  72.692308  70.000000  62.846154  63.692308  69.961538  55.153846  68.884615
14                 Ecuador  72.500000  76.769231  59.346154  63.538462  70.500000  52.884615  67.730769
39             South Korea  71.807692  75.192308  60.692308  64.115385  70.692308  51.115385  68.961538
13                DR Congo  71.576923  72.923077  59.846154  63.230769  69.653846  55.423077  72.230769
37                 Senegal  71.500000  71.461538  64.153846  65.769231  69.846154  57.538462  68.115385
5   Bosnia and Herzegovina  70.923077  65.269231  57.653846  60.076923  65.846154  51.423077  71.961538
7                   Canada  69.923077  72.884615  59.615385  61.153846  67.730769  53.269231  68.576923
2                Australia  69.307692  71.384615  56.769231  62.423077  66.384615  59.307692  70.923077
35            Saudi Arabia  69.115385  71.961538  53.307692  61.000000  65.192308  56.884615  69.576923
26                  Mexico  68.653846  71.115385  58.269231  61.500000  67.884615  49.461538  64.538462
43                 Tunisia  68.000000  68.384615  58.500000  62.730769  67.115385  55.769231  66.692308
29             New Zealand  66.961538  69.576923  58.884615  60.846154  64.923077  54.423077  70.692308
22                    Iraq  62.115385  66.192308  58.192308  58.615385  62.692308  50.807692  61.538462
38            South Africa  62.000000  66.884615  54.500000  56.923077  60.846154  54.653846  60.692308
31                  Panama  61.769231  61.461538  56.000000  59.307692  60.692308  55.500000  61.769231
15                   Egypt  61.000000  60.269231  58.961538  59.038462  59.846154  55.923077  60.307692
20                   Haiti  60.884615  63.769231  54.730769  57.384615  60.076923  53.884615  60.615385
11                 Curaçao  60.500000  64.846154  54.153846  57.846154  61.000000  55.153846  59.653846
21                 IR Iran  60.230769  59.692308  58.076923  58.500000  59.538462  55.115385  60.192308
47              Uzbekistan  59.076923  59.269231  56.346154  57.192308  58.000000  56.576923  58.346154
25                  Jordan  58.384615  59.076923  56.384615  56.961538  57.692308  56.884615  58.230769
8               Cape Verde  57.000000  57.000000  57.000000  57.000000  57.000000  57.000000  57.000000
34                   Qatar  57.000000  57.000000  57.000000  57.000000  57.000000  57.000000  57.000000

In [79]:
# حفظ team_ratings
team_ratings.to_csv('data/clean/team_ratings.csv', index=False)
print("تم حفظ team_ratings ✅")

# حفظ all_squads المحدث
all_squads.to_csv('data/clean/all_squads.csv', index=False)
print("تم حفظ all_squads ✅")

# الخطوة الجاية: دمج مع بيانات المباريات
# نقرأ بيانات المباريات المنظفة
df = pd.read_csv('data/clean/results_clean.csv')

# تجهيز تقييمات الفريق المضيف
home_ratings = team_ratings.rename(columns={
    'team':    'home_team',
    'avg_ovr': 'home_avg_ovr',
    'avg_pac': 'home_avg_pac',
    'avg_sho': 'home_avg_sho',
    'avg_pas': 'home_avg_pas',
    'avg_dri': 'home_avg_dri',
    'avg_def': 'home_avg_def',
    'avg_phy': 'home_avg_phy',
})

# تجهيز تقييمات الفريق الضيف
away_ratings = team_ratings.rename(columns={
    'team':    'away_team',
    'avg_ovr': 'away_avg_ovr',
    'avg_pac': 'away_avg_pac',
    'avg_sho': 'away_avg_sho',
    'avg_pas': 'away_avg_pas',
    'avg_dri': 'away_avg_dri',
    'avg_def': 'away_avg_def',
    'avg_phy': 'away_avg_phy',
})

# دمج تقييمات الفريق المضيف
df = df.merge(home_ratings, on='home_team', how='left')

# دمج تقييمات الفريق الضيف
df = df.merge(away_ratings, on='away_team', how='left')

print(f"شكل البيانات بعد الدمج: {df.shape}")
print(df.columns.tolist())

تم حفظ team_ratings ✅
تم حفظ all_squads ✅
شكل البيانات بعد الدمج: (5635, 27)
['date', 'home_team', 'away_team', 'home_score', 'away_score', 'tournament', 'city', 'country', 'neutral', 'result', 'tournament_weight', 'home_rank', 'away_rank', 'home_avg_ovr', 'home_avg_pac', 'home_avg_sho', 'home_avg_pas', 'home_avg_dri', 'home_avg_def', 'home_avg_phy', 'away_avg_ovr', 'away_avg_pac', 'away_avg_sho', 'away_avg_pas', 'away_avg_dri', 'away_avg_def', 'away_avg_phy']

In [80]:
# نشوف كم مباراة عندها NaN
print(f"مباريات بدون تقييمات: {df['home_avg_ovr'].isna().sum()}")
print(f"مباريات مع تقييمات: {df['home_avg_ovr'].notna().sum()}")

# نشوف أمثلة على المباريات اللي عندها تقييمات
print(df[df['home_avg_ovr'].notna()][['home_team', 'away_team', 'home_avg_ovr', 'away_avg_ovr', 'result']].head(10))

مباريات بدون تقييمات: 1880
مباريات مع تقييمات: 3755
       home_team   away_team  home_avg_ovr  away_avg_ovr  result
0          Qatar        Mali     57.000000           NaN       0
1          Egypt        Mali     61.000000           NaN       1
2          Ghana      Malawi     73.576923           NaN       0
7          Egypt     Nigeria     61.000000           NaN       1
10         Egypt  Mozambique     61.000000           NaN       1
15         Egypt       Benin     61.000000           NaN       1
20         Egypt    Cameroon     61.000000           NaN       1
21     Argentina  Costa Rica     80.423077           NaN       1
22  South Africa    Zimbabwe     62.000000           NaN       1
23       Algeria       Egypt     73.230769          61.0      -1

In [81]:
df_wc = df[df['home_avg_ovr'].notna() & df['away_avg_ovr'].notna()].copy()

print(f"عدد المباريات: {len(df_wc)}")
print(f"توزيع النتائج:")
print(df_wc['result'].value_counts())

عدد المباريات: 1378
توزيع النتائج:
result
 1    629
-1    413
 0    336
Name: count, dtype: int64